
= Receive Request from Gateway

== Process description
This process is triggered by a request received by the WS-endpoint.

It is the very starting point and without being in a workflow.

== Activity diagram

.Receive request from gateway activity diagram

[plantuml,receive_request_from_gateway,format=svg]
----
@startuml

start
:ReceiveRequest;
if (return)
    :Validate transition message;
    if (return)
        :Trigger workflow;
        if (return)
            stop
        else (Exception)
        endif
    else (Exception)
    endif
else (Exception)

endif

:throw WebService typed exception;


end




@enduml
----

== Process-steps

|===
| step | description | parameters | returns | on success | on fail | module responsibility

|Receive Request
|The WS Endpoint receives a request from the gateway
|DomibusConnectorMessageType
|
|Validate transition message
|Exception
|domibusConnectorLink

|Validate transition message
|The message in its transition model state is validated if the ebms data and message contents required are in place.
As a result of this step also the type of message is known. This could either be "business message" (BM) or "confirmation message" (CM).
|DomibusConnectorMessageType
|validation result
|Trigger Workflow
|Exception
|Link

|Trigger Workflow
|The workflow for this message is identified and the processes of the workflow are initialized.
|DomibusConnectorMessageType, messageType
|
|End process
|Exception
|Link
|===

== Sequence Diagram

[plantuml,receive_message_by_synchronous_request_sequence_diagram,format=svg]
----
@startuml


actor "LinkPartner (Gateway)" as LP

participant HttpServlet
collections CXF
participant WsBackendServiceEndpointImpl

collections LinkModule
collections WorkflowModule
collections PersistenceModule
collections TransitionService

database DB

activate HttpServlet
activate LP
LP -> HttpServlet: post(deliverMessageRequest)
create CXF
HttpServlet -> CXF++: create new Thread,\n deliverMessageRequest

CXF -> CXF: decrypt,\n check,\n validate
CXF -> CXF: deserialize
CXF -> WsBackendServiceEndpointImpl--++: submitMessage(DomibusConnectorMessageType)
WsBackendServiceEndpointImpl -> DomibusConnectorDomainMessageTransformerService--++: transform(DomibusConnectorMessageType)






@enduml
----