package eu.ecodex.connector.evidences.type;


public enum RejectionReason {

    SOAP_FAULT, SAML_TOKEN_VALIDATION, WS_ADDRESSING_FAULT, UNKNOWN_ORIGINATOR_ADDRESS, UNKNOWN_RECIPIENT_ADDRESS, UNSPECIFIC_PROCESSING_ERROR, WRONG_INPUT_DATA, DUPLICATE_MSG_ID, OTHER, UNREACHABLE
}
