//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.19 at 08:45:07 AM MESZ 
//


package org.etsi.uri._02640.soapbinding.v1;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.etsi.uri._02640.v2.EntityDetailsType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/02640/soapbinding/v1#}Recipient"/>
 *         &lt;element name="OtherRecipients">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="To" type="{http://uri.etsi.org/02640/v2#}EntityDetailsType" maxOccurs="unbounded"/>
 *                   &lt;element name="Cc" type="{http://uri.etsi.org/02640/v2#}EntityDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "recipient",
    "otherRecipients"
})
@XmlRootElement(name = "Destinations")
public class Destinations {

    @XmlElement(name = "Recipient", required = true)
    protected EntityDetailsType recipient;
    @XmlElement(name = "OtherRecipients", required = true)
    protected Destinations.OtherRecipients otherRecipients;

    /**
     * Gets the value of the recipient property.
     * 
     * @return
     *     possible object is
     *     {@link EntityDetailsType }
     *     
     */
    public EntityDetailsType getRecipient() {
        return recipient;
    }

    /**
     * Sets the value of the recipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityDetailsType }
     *     
     */
    public void setRecipient(EntityDetailsType value) {
        this.recipient = value;
    }

    /**
     * Gets the value of the otherRecipients property.
     * 
     * @return
     *     possible object is
     *     {@link Destinations.OtherRecipients }
     *     
     */
    public Destinations.OtherRecipients getOtherRecipients() {
        return otherRecipients;
    }

    /**
     * Sets the value of the otherRecipients property.
     * 
     * @param value
     *     allowed object is
     *     {@link Destinations.OtherRecipients }
     *     
     */
    public void setOtherRecipients(Destinations.OtherRecipients value) {
        this.otherRecipients = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="To" type="{http://uri.etsi.org/02640/v2#}EntityDetailsType" maxOccurs="unbounded"/>
     *         &lt;element name="Cc" type="{http://uri.etsi.org/02640/v2#}EntityDetailsType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "to",
        "cc"
    })
    public static class OtherRecipients {

        @XmlElement(name = "To", required = true)
        protected List<EntityDetailsType> to;
        @XmlElement(name = "Cc")
        protected List<EntityDetailsType> cc;

        /**
         * Gets the value of the to property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the to property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EntityDetailsType }
         * 
         * 
         */
        public List<EntityDetailsType> getTo() {
            if (to == null) {
                to = new ArrayList<EntityDetailsType>();
            }
            return this.to;
        }

        /**
         * Gets the value of the cc property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cc property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCc().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EntityDetailsType }
         * 
         * 
         */
        public List<EntityDetailsType> getCc() {
            if (cc == null) {
                cc = new ArrayList<EntityDetailsType>();
            }
            return this.cc;
        }

    }

}
