//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.19 at 08:45:07 AM MESZ 
//


package org.etsi.uri._02640.soapbinding.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/02640/soapbinding/v1#}DeliveryConstraints"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/soapbinding/v1#}Originators"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/soapbinding/v1#}Destinations"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/soapbinding/v1#}MsgIdentification"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deliveryConstraints",
    "originators",
    "destinations",
    "msgIdentification"
})
@XmlRootElement(name = "MsgMetaData")
public class MsgMetaData {

    @XmlElement(name = "DeliveryConstraints", required = true)
    protected DeliveryConstraints deliveryConstraints;
    @XmlElement(name = "Originators", required = true)
    protected Originators originators;
    @XmlElement(name = "Destinations", required = true)
    protected Destinations destinations;
    @XmlElement(name = "MsgIdentification", required = true)
    protected MsgIdentification msgIdentification;

    /**
     * Gets the value of the deliveryConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryConstraints }
     *     
     */
    public DeliveryConstraints getDeliveryConstraints() {
        return deliveryConstraints;
    }

    /**
     * Sets the value of the deliveryConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryConstraints }
     *     
     */
    public void setDeliveryConstraints(DeliveryConstraints value) {
        this.deliveryConstraints = value;
    }

    /**
     * Gets the value of the originators property.
     * 
     * @return
     *     possible object is
     *     {@link Originators }
     *     
     */
    public Originators getOriginators() {
        return originators;
    }

    /**
     * Sets the value of the originators property.
     * 
     * @param value
     *     allowed object is
     *     {@link Originators }
     *     
     */
    public void setOriginators(Originators value) {
        this.originators = value;
    }

    /**
     * Gets the value of the destinations property.
     * 
     * @return
     *     possible object is
     *     {@link Destinations }
     *     
     */
    public Destinations getDestinations() {
        return destinations;
    }

    /**
     * Sets the value of the destinations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Destinations }
     *     
     */
    public void setDestinations(Destinations value) {
        this.destinations = value;
    }

    /**
     * Gets the value of the msgIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link MsgIdentification }
     *     
     */
    public MsgIdentification getMsgIdentification() {
        return msgIdentification;
    }

    /**
     * Sets the value of the msgIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgIdentification }
     *     
     */
    public void setMsgIdentification(MsgIdentification value) {
        this.msgIdentification = value;
    }

}
