//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.19 at 08:45:07 AM MESZ 
//


package org.etsi.uri._02640.soapbinding.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import org.etsi.uri._02640.v2.EntityDetailsType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.etsi.uri._02640.soapbinding.v1_ package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _REMEvidenceList_QNAME = new QName("http://uri.etsi.org/02640/soapbinding/v1#", "REMEvidenceList");
    private final static QName _REMMDEvidenceList_QNAME = new QName("http://uri.etsi.org/02640/soapbinding/v1#", "REMMDEvidenceList");
    private final static QName _Recipient_QNAME = new QName("http://uri.etsi.org/02640/soapbinding/v1#", "Recipient");
    private final static QName _REMDispatch_QNAME = new QName("http://uri.etsi.org/02640/soapbinding/v1#", "REMDispatch");
    private final static QName _REMMDMessage_QNAME = new QName("http://uri.etsi.org/02640/soapbinding/v1#", "REMMDMessage");
    private final static QName _OriginalMsg_QNAME = new QName("http://uri.etsi.org/02640/soapbinding/v1#", "OriginalMsg");
    private final static QName _Attachment_QNAME = new QName("http://uri.etsi.org/02640/soapbinding/v1#", "Attachment");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.etsi.uri._02640.soapbinding.v1_
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KeywordType }
     * 
     */
    public KeywordType createKeywordType() {
        return new KeywordType();
    }

    /**
     * Create an instance of {@link OriginalREMMDEvidenceListType }
     * 
     */
    public OriginalREMMDEvidenceListType createOriginalREMMDEvidenceListType() {
        return new OriginalREMMDEvidenceListType();
    }

    /**
     * Create an instance of {@link OriginalMsgType }
     * 
     */
    public OriginalMsgType createOriginalMsgType() {
        return new OriginalMsgType();
    }

    /**
     * Create an instance of {@link NormalizedMsg.Text }
     * 
     */
    public NormalizedMsg.Text createNormalizedMsgText() {
        return new NormalizedMsg.Text();
    }

    /**
     * Create an instance of {@link Informational }
     * 
     */
    public Informational createInformational() {
        return new Informational();
    }

    /**
     * Create an instance of {@link MsgIdentification }
     * 
     */
    public MsgIdentification createMsgIdentification() {
        return new MsgIdentification();
    }

    /**
     * Create an instance of {@link DeliveryConstraints }
     * 
     */
    public DeliveryConstraints createDeliveryConstraints() {
        return new DeliveryConstraints();
    }

    /**
     * Create an instance of {@link REMMDMessageType }
     * 
     */
    public REMMDMessageType createREMMDMessageType() {
        return new REMMDMessageType();
    }

    /**
     * Create an instance of {@link MsgMetaData }
     * 
     */
    public MsgMetaData createMsgMetaData() {
        return new MsgMetaData();
    }

    /**
     * Create an instance of {@link REMDispatchType }
     * 
     */
    public REMDispatchType createREMDispatchType() {
        return new REMDispatchType();
    }

    /**
     * Create an instance of {@link NormalizedMsg }
     * 
     */
    public NormalizedMsg createNormalizedMsg() {
        return new NormalizedMsg();
    }

    /**
     * Create an instance of {@link AttachmentType }
     * 
     */
    public AttachmentType createAttachmentType() {
        return new AttachmentType();
    }

    /**
     * Create an instance of {@link Destinations.OtherRecipients }
     * 
     */
    public Destinations.OtherRecipients createDestinationsOtherRecipients() {
        return new Destinations.OtherRecipients();
    }

    /**
     * Create an instance of {@link Originators }
     * 
     */
    public Originators createOriginators() {
        return new Originators();
    }

    /**
     * Create an instance of {@link REMMDEvidenceListType }
     * 
     */
    public REMMDEvidenceListType createREMMDEvidenceListType() {
        return new REMMDEvidenceListType();
    }

    /**
     * Create an instance of {@link Destinations }
     * 
     */
    public Destinations createDestinations() {
        return new Destinations();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REMMDEvidenceListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/02640/soapbinding/v1#", name = "REMEvidenceList")
    public JAXBElement<REMMDEvidenceListType> createREMEvidenceList(REMMDEvidenceListType value) {
        return new JAXBElement<REMMDEvidenceListType>(_REMEvidenceList_QNAME, REMMDEvidenceListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REMMDEvidenceListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/02640/soapbinding/v1#", name = "REMMDEvidenceList")
    public JAXBElement<REMMDEvidenceListType> createREMMDEvidenceList(REMMDEvidenceListType value) {
        return new JAXBElement<REMMDEvidenceListType>(_REMMDEvidenceList_QNAME, REMMDEvidenceListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntityDetailsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/02640/soapbinding/v1#", name = "Recipient")
    public JAXBElement<EntityDetailsType> createRecipient(EntityDetailsType value) {
        return new JAXBElement<EntityDetailsType>(_Recipient_QNAME, EntityDetailsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REMDispatchType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/02640/soapbinding/v1#", name = "REMDispatch")
    public JAXBElement<REMDispatchType> createREMDispatch(REMDispatchType value) {
        return new JAXBElement<REMDispatchType>(_REMDispatch_QNAME, REMDispatchType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REMMDMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/02640/soapbinding/v1#", name = "REMMDMessage")
    public JAXBElement<REMMDMessageType> createREMMDMessage(REMMDMessageType value) {
        return new JAXBElement<REMMDMessageType>(_REMMDMessage_QNAME, REMMDMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OriginalMsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/02640/soapbinding/v1#", name = "OriginalMsg")
    public JAXBElement<OriginalMsgType> createOriginalMsg(OriginalMsgType value) {
        return new JAXBElement<OriginalMsgType>(_OriginalMsg_QNAME, OriginalMsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttachmentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/02640/soapbinding/v1#", name = "Attachment")
    public JAXBElement<AttachmentType> createAttachment(AttachmentType value) {
        return new JAXBElement<AttachmentType>(_Attachment_QNAME, AttachmentType.class, null, value);
    }

}
