//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.19 at 08:45:07 AM MESZ 
//


package org.etsi.uri._02640.soapbinding.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.etsi.uri._02640.v2.REMEvidenceType;


/**
 * <p>Java class for REMMDEvidenceListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REMMDEvidenceListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element ref="{http://uri.etsi.org/02640/v2#}SubmissionAcceptanceRejection" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v2#}RelayREMMDAcceptanceRejection" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v2#}RelayREMMDFailure" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v2#}DeliveryNonDeliveryToRecipient" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v2#}RetrievalNonRetrievalByRecipient" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v2#}AcceptanceRejectionByRecipient" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v2#}DownloadNonDownloadByRecipient" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v2#}RelayToNonREMSystem" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v2#}ReceivedFromNonREMSystem" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "submissionAcceptanceRejectionAndRelayREMMDAcceptanceRejectionAndRelayREMMDFailure"
})
@XmlSeeAlso({
    REMMDEvidenceListType.class
})
public class OriginalREMMDEvidenceListType {

    @XmlElementRefs({
        @XmlElementRef(name = "ReceivedFromNonREMSystem", namespace = "http://uri.etsi.org/02640/v2#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "RetrievalNonRetrievalByRecipient", namespace = "http://uri.etsi.org/02640/v2#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "RelayREMMDFailure", namespace = "http://uri.etsi.org/02640/v2#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DeliveryNonDeliveryToRecipient", namespace = "http://uri.etsi.org/02640/v2#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SubmissionAcceptanceRejection", namespace = "http://uri.etsi.org/02640/v2#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "AcceptanceRejectionByRecipient", namespace = "http://uri.etsi.org/02640/v2#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "RelayREMMDAcceptanceRejection", namespace = "http://uri.etsi.org/02640/v2#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DownloadNonDownloadByRecipient", namespace = "http://uri.etsi.org/02640/v2#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "RelayToNonREMSystem", namespace = "http://uri.etsi.org/02640/v2#", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<REMEvidenceType>> submissionAcceptanceRejectionAndRelayREMMDAcceptanceRejectionAndRelayREMMDFailure;
    @XmlAttribute(name = "Id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the submissionAcceptanceRejectionAndRelayREMMDAcceptanceRejectionAndRelayREMMDFailure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the submissionAcceptanceRejectionAndRelayREMMDAcceptanceRejectionAndRelayREMMDFailure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubmissionAcceptanceRejectionAndRelayREMMDAcceptanceRejectionAndRelayREMMDFailure().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link REMEvidenceType }{@code >}
     * {@link JAXBElement }{@code <}{@link REMEvidenceType }{@code >}
     * {@link JAXBElement }{@code <}{@link REMEvidenceType }{@code >}
     * {@link JAXBElement }{@code <}{@link REMEvidenceType }{@code >}
     * {@link JAXBElement }{@code <}{@link REMEvidenceType }{@code >}
     * {@link JAXBElement }{@code <}{@link REMEvidenceType }{@code >}
     * {@link JAXBElement }{@code <}{@link REMEvidenceType }{@code >}
     * {@link JAXBElement }{@code <}{@link REMEvidenceType }{@code >}
     * {@link JAXBElement }{@code <}{@link REMEvidenceType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<REMEvidenceType>> getSubmissionAcceptanceRejectionAndRelayREMMDAcceptanceRejectionAndRelayREMMDFailure() {
        if (submissionAcceptanceRejectionAndRelayREMMDAcceptanceRejectionAndRelayREMMDFailure == null) {
            submissionAcceptanceRejectionAndRelayREMMDAcceptanceRejectionAndRelayREMMDFailure = new ArrayList<JAXBElement<REMEvidenceType>>();
        }
        return this.submissionAcceptanceRejectionAndRelayREMMDAcceptanceRejectionAndRelayREMMDFailure;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
