//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.19 at 08:45:07 AM MESZ 
//


package org.etsi.uri._02640.soapbinding.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.etsi.uri._02640.v2.EntityDetailsType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="From" type="{http://uri.etsi.org/02640/v2#}EntityDetailsType"/>
 *         &lt;element name="Sender" type="{http://uri.etsi.org/02640/v2#}EntityDetailsType" minOccurs="0"/>
 *         &lt;element name="ReplyTo" type="{http://uri.etsi.org/02640/v2#}EntityDetailsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "from",
    "sender",
    "replyTo"
})
@XmlRootElement(name = "Originators")
public class Originators {

    @XmlElement(name = "From", required = true)
    protected EntityDetailsType from;
    @XmlElement(name = "Sender")
    protected EntityDetailsType sender;
    @XmlElement(name = "ReplyTo")
    protected EntityDetailsType replyTo;

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link EntityDetailsType }
     *     
     */
    public EntityDetailsType getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityDetailsType }
     *     
     */
    public void setFrom(EntityDetailsType value) {
        this.from = value;
    }

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link EntityDetailsType }
     *     
     */
    public EntityDetailsType getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityDetailsType }
     *     
     */
    public void setSender(EntityDetailsType value) {
        this.sender = value;
    }

    /**
     * Gets the value of the replyTo property.
     * 
     * @return
     *     possible object is
     *     {@link EntityDetailsType }
     *     
     */
    public EntityDetailsType getReplyTo() {
        return replyTo;
    }

    /**
     * Sets the value of the replyTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityDetailsType }
     *     
     */
    public void setReplyTo(EntityDetailsType value) {
        this.replyTo = value;
    }

}
