//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.19 at 08:45:07 AM MESZ 
//


package org.etsi.uri._02640.soapbinding.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for REMMDEvidenceListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REMMDEvidenceListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://uri.etsi.org/02640/soapbinding/v1#}REMMDEvidenceListType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/02640/v2#}SubmissionAcceptanceRejection" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v2#}RelayREMMDAcceptanceRejection" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v2#}RelayREMMDFailure" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v2#}DeliveryNonDeliveryToRecipient" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v2#}RetrievalNonRetrievalByRecipient" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02640/v2#}AcceptanceRejectionByRecipient" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "REMMDEvidenceListType")
public class REMMDEvidenceListType
    extends OriginalREMMDEvidenceListType
{


}
