CREATE TABLE ECODEX_WEBADMIN_USER (
  ID        NUMBER(10)    NOT NULL,
  USERNAME  VARCHAR2(30)  NOT NULL,
  PASSWORD  VARCHAR2(150)  NOT NULL,
  ROLE	    VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE ECODEX_WEBADMIN_PROPERTIES (
  PROPERTIES_KEY  VARCHAR2(30)  NOT NULL,
  PROPERTIES_VALUE  VARCHAR2(100),
  PRIMARY KEY (PROPERTIES_KEY)
);
