
package connector.domibus.eu.domibusconnectorgatewayservice._1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.3
 * 2017-06-13T09:53:22.671+02:00
 * Generated source version: 3.1.3
 */

@WebFault(name = "DomibusConnectorGatewayServiceFault", targetNamespace = "http://eu.domibus.connector/DomibusConnectorGatewayService/1.0/")
public class SendMessageFault extends Exception {
    
    private java.lang.String domibusConnectorGatewayServiceFault;

    public SendMessageFault() {
        super();
    }
    
    public SendMessageFault(String message) {
        super(message);
    }
    
    public SendMessageFault(String message, Throwable cause) {
        super(message, cause);
    }

    public SendMessageFault(String message, java.lang.String domibusConnectorGatewayServiceFault) {
        super(message);
        this.domibusConnectorGatewayServiceFault = domibusConnectorGatewayServiceFault;
    }

    public SendMessageFault(String message, java.lang.String domibusConnectorGatewayServiceFault, Throwable cause) {
        super(message, cause);
        this.domibusConnectorGatewayServiceFault = domibusConnectorGatewayServiceFault;
    }

    public java.lang.String getFaultInfo() {
        return this.domibusConnectorGatewayServiceFault;
    }
}
