--  *********************************************************************
--  Update Database Script
--  *********************************************************************
--  Change Log: db/changelog/v004/upgrade-3to4.xml
--  Ran at: 11.04.18 12:19
--  Against: domibus@localhost@jdbc:mysql://localhost/domibusconnector
--  Liquibase version: 3.5.3
--  *********************************************************************
-- This database migration script is based on LIQUIBASE
-- It
--



--  Create Database Lock Table
CREATE TABLE domibusconnector.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BIT(1) NOT NULL, LOCKGRANTED datetime NULL, LOCKEDBY VARCHAR(255) NULL, CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID));

--  Initialize Database Lock Table
DELETE FROM domibusconnector.DATABASECHANGELOGLOCK;

INSERT INTO domibusconnector.DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, 0);

--  Lock Database
UPDATE domibusconnector.DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = 'PC65589 (172.31.33.137)', LOCKGRANTED = '2018-04-11 12:19:44.854' WHERE ID = 1 AND LOCKED = 0;

--  Create Database Change Log Table
CREATE TABLE domibusconnector.DATABASECHANGELOG (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED datetime NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35) NULL, DESCRIPTION VARCHAR(255) NULL, COMMENTS VARCHAR(255) NULL, TAG VARCHAR(255) NULL, LIQUIBASE VARCHAR(20) NULL, CONTEXTS VARCHAR(255) NULL, LABELS VARCHAR(255) NULL, DEPLOYMENT_ID VARCHAR(10) NULL);

-- --  Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_001.0_pre_setup::StephanSpindler
-- --  WARNING The following SQL may change each run and therefore is possibly incorrect and/or invalid:
-- --  WARNING The following SQL may change each run and therefore is possibly incorrect and/or invalid:
-- --  WARNING The following SQL may change each run and therefore is possibly incorrect and/or invalid:
-- --  WARNING The following SQL may change each run and therefore is possibly incorrect and/or invalid:
-- ALTER TABLE domibusconnector.domibus_connector_evidences DROP FOREIGN KEY domibus_connector_evidences_ibfk_1;
-- 
-- --  WARNING The following SQL may change each run and therefore is possibly incorrect and/or invalid:
-- ALTER TABLE domibusconnector.domibus_connector_message_info DROP FOREIGN KEY domibus_connector_message_info_ibfk_1;
--
-- ALTER TABLE domibusconnector.domibus_connector_message_info DROP FOREIGN KEY domibus_connector_message_info_ibfk_2;
--
-- ALTER TABLE domibusconnector.domibus_connector_message_info DROP FOREIGN KEY domibus_connector_message_info_ibfk_3;
--
-- ALTER TABLE domibusconnector.domibus_connector_message_info DROP FOREIGN KEY domibus_connector_message_info_ibfk_4;
--
-- ALTER TABLE domibusconnector.domibus_connector_message_info DROP FOREIGN KEY domibus_connector_message_info_ibfk_5;
--
-- --  WARNING The following SQL may change each run and therefore is possibly incorrect and/or invalid:
-- --  WARNING The following SQL may change each run and therefore is possibly incorrect and/or invalid:
-- ALTER TABLE domibusconnector.domibus_connector_msg_error DROP FOREIGN KEY domibus_connector_msg_error_ibfk_1;

--  WARNING The following SQL may change each run and therefore is possibly incorrect and/or invalid:
INSERT INTO domibusconnector.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('3to4_upgrade_001.0_pre_setup', 'StephanSpindler', 'db/changelog/v004/upgrade-3to4.xml', NOW(), 1, '7:60d088bad0f7515adbff6bd46353a67d', 'dropAllForeignKeyConstraints baseTableName=DOMIBUS_CONNECTOR_SERVICE; dropAllForeignKeyConstraints baseTableName=DOMIBUS_CONNECTOR_PARTY; dropAllForeignKeyConstraints baseTableName=DOMIBUS_CONNECTOR_ACTION; dropAllForeignKeyConstraints baseTableNa...', '', 'EXECUTED', NULL, NULL, '3.5.3', '3441985564');

--  Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_001_tb_DOMIBUS_CONNECTOR_SERVICE::StephanSpindler
ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_SERVICE MODIFY SERVICE VARCHAR(255);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_SERVICE MODIFY SERVICE_TYPE VARCHAR(512);

INSERT INTO domibusconnector.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('3to4_upgrade_001_tb_DOMIBUS_CONNECTOR_SERVICE', 'StephanSpindler', 'db/changelog/v004/upgrade-3to4.xml', NOW(), 2, '7:cc419bfe193d3a061879f75ad35b8c95', 'modifyDataType columnName=SERVICE, tableName=DOMIBUS_CONNECTOR_SERVICE; modifyDataType columnName=SERVICE_TYPE, tableName=DOMIBUS_CONNECTOR_SERVICE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3441985564');

--  Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_002_tb_DOMIBUS_CONNECTOR_PARTY::StephanSpinlder
ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_PARTY MODIFY PARTY_ID VARCHAR(255);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_PARTY MODIFY ROLE VARCHAR(255);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_PARTY MODIFY PARTY_ID_TYPE VARCHAR(512);

INSERT INTO domibusconnector.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('3to4_upgrade_002_tb_DOMIBUS_CONNECTOR_PARTY', 'StephanSpinlder', 'db/changelog/v004/upgrade-3to4.xml', NOW(), 3, '7:cd1591ffd545beccca7fd236fd8eb6d4', 'modifyDataType columnName=PARTY_ID, tableName=DOMIBUS_CONNECTOR_PARTY; modifyDataType columnName=ROLE, tableName=DOMIBUS_CONNECTOR_PARTY; modifyDataType columnName=PARTY_ID_TYPE, tableName=DOMIBUS_CONNECTOR_PARTY', '', 'EXECUTED', NULL, NULL, '3.5.3', '3441985564');

--  Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_003_tb_DOMIBUS_CONNECTOR_MSG_ERROR::StephanSpindler
ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MSG_ERROR MODIFY ID numeric(10, 0);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MSG_ERROR MODIFY MESSAGE_ID numeric(10, 0);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MSG_ERROR MODIFY ERROR_MESSAGE VARCHAR(512);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MSG_ERROR MODIFY DETAILED_TEXT LONGTEXT;

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MSG_ERROR MODIFY ERROR_SOURCE LONGTEXT;

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MSG_ERROR MODIFY CREATED timestamp;

INSERT INTO domibusconnector.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('3to4_upgrade_003_tb_DOMIBUS_CONNECTOR_MSG_ERROR', 'StephanSpindler', 'db/changelog/v004/upgrade-3to4.xml', NOW(), 4, '7:2ef9e7f32ef02f3937f8b77860affad3', 'modifyDataType columnName=ID, tableName=DOMIBUS_CONNECTOR_MSG_ERROR; modifyDataType columnName=MESSAGE_ID, tableName=DOMIBUS_CONNECTOR_MSG_ERROR; modifyDataType columnName=ERROR_MESSAGE, tableName=DOMIBUS_CONNECTOR_MSG_ERROR; modifyDataType column...', '', 'EXECUTED', NULL, NULL, '3.5.3', '3441985564');

--  Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_004_tb_create_DOMIBUS_CONNECTOR_MSG_CONT::StephanSpindler
CREATE TABLE domibusconnector.DOMIBUS_CONNECTOR_MSG_CONT (ID numeric(10, 0) NOT NULL, MESSAGE_ID numeric(10, 0) NOT NULL, CONTENT_TYPE VARCHAR(255) NULL, CONTENT BLOB NULL);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MSG_CONT ADD PRIMARY KEY (ID);

INSERT INTO domibusconnector.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('3to4_upgrade_004_tb_create_DOMIBUS_CONNECTOR_MSG_CONT', 'StephanSpindler', 'db/changelog/v004/upgrade-3to4.xml', NOW(), 5, '7:4b9b18e511b53a3e26cc6c9540090c81', 'createTable tableName=DOMIBUS_CONNECTOR_MSG_CONT; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_MSG__01, tableName=DOMIBUS_CONNECTOR_MSG_CONT', '', 'EXECUTED', NULL, NULL, '3.5.3', '3441985564');

--  Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_005_tb_update_DOMIBUS_CONNECTOR_MESSAGE_INFO::StephanSpindler
ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY ID numeric(10, 0);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY MESSAGE_ID numeric(10, 0);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY FROM_PARTY_ID VARCHAR(255);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY FROM_PARTY_ROLE VARCHAR(255);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY TO_PARTY_ID VARCHAR(255);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY TO_PARTY_ROLE VARCHAR(255);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY ORIGINAL_SENDER VARCHAR(255);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY FINAL_RECIPIENT VARCHAR(255);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY SERVICE VARCHAR(255);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY ACTION VARCHAR(255);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY CREATED timestamp;

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY UPDATED timestamp;

INSERT INTO domibusconnector.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('3to4_upgrade_005_tb_update_DOMIBUS_CONNECTOR_MESSAGE_INFO', 'StephanSpindler', 'db/changelog/v004/upgrade-3to4.xml', NOW(), 6, '7:6a593648e94572f00d485e2d59ba2b18', 'modifyDataType columnName=ID, tableName=DOMIBUS_CONNECTOR_MESSAGE_INFO; modifyDataType columnName=MESSAGE_ID, tableName=DOMIBUS_CONNECTOR_MESSAGE_INFO; modifyDataType columnName=FROM_PARTY_ID, tableName=DOMIBUS_CONNECTOR_MESSAGE_INFO; modifyDataTy...', '', 'EXECUTED', NULL, NULL, '3.5.3', '3441985564');

--  Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_006_tb_rename_DOMIBUS_CONNECTOR_MESSAGE::StephanSpindler
ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGES RENAME domibusconnector.DOMIBUS_CONNECTOR_MESSAGE;

INSERT INTO domibusconnector.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('3to4_upgrade_006_tb_rename_DOMIBUS_CONNECTOR_MESSAGE', 'StephanSpindler', 'db/changelog/v004/upgrade-3to4.xml', NOW(), 7, '7:c1c6c87542e8303354a39c8a82d5e17a', 'renameTable newTableName=DOMIBUS_CONNECTOR_MESSAGE, oldTableName=DOMIBUS_CONNECTOR_MESSAGES', '', 'EXECUTED', NULL, NULL, '3.5.3', '3441985564');

--  Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_007_tb_update_DOMIBUS_CONNECTOR_MESSAGE::StephanSpindler
ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE MODIFY ID numeric(10, 0);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE CHANGE NAT_MESSAGE_ID BACKEND_MESSAGE_ID VARCHAR(255);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE MODIFY HASH_VALUE LONGTEXT;

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE MODIFY CONFIRMED timestamp;

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE MODIFY REJECTED timestamp;

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE MODIFY DELIVERED_GW timestamp;

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE MODIFY UPDATED timestamp;

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE CHANGE DELIVERED_NAT DELIVERED_BACKEND timestamp;

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE ADD BACKEND_NAME VARCHAR(255) NULL;

INSERT INTO domibusconnector.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('3to4_upgrade_007_tb_update_DOMIBUS_CONNECTOR_MESSAGE', 'StephanSpindler', 'db/changelog/v004/upgrade-3to4.xml', NOW(), 8, '7:d532c3fb8b3236a4b267ea6a5c86ccd3', 'modifyDataType columnName=ID, tableName=DOMIBUS_CONNECTOR_MESSAGE; renameColumn newColumnName=BACKEND_MESSAGE_ID, oldColumnName=NAT_MESSAGE_ID, tableName=DOMIBUS_CONNECTOR_MESSAGE; modifyDataType columnName=HASH_VALUE, tableName=DOMIBUS_CONNECTOR_...', '', 'EXECUTED', NULL, NULL, '3.5.3', '3441985564');

--  Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_008_tb_ren_DOMIBUS_CONNECTOR_EVIDENCE::StephanSpindler
ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_EVIDENCES RENAME domibusconnector.DOMIBUS_CONNECTOR_EVIDENCE;

INSERT INTO domibusconnector.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('3to4_upgrade_008_tb_ren_DOMIBUS_CONNECTOR_EVIDENCE', 'StephanSpindler', 'db/changelog/v004/upgrade-3to4.xml', NOW(), 9, '7:e380300222773aac95002fbc9e4d5919', 'renameTable newTableName=DOMIBUS_CONNECTOR_EVIDENCE, oldTableName=DOMIBUS_CONNECTOR_EVIDENCES', '', 'EXECUTED', NULL, NULL, '3.5.3', '3441985564');

--  Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_009_tb_update_DOMIBUS_CONNECTOR_EVIDENCE::StephanSpindler
ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_EVIDENCE MODIFY ID numeric(10, 0);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_EVIDENCE MODIFY MESSAGE_ID numeric(10, 0);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_EVIDENCE MODIFY EVIDENCE LONGTEXT;

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_EVIDENCE MODIFY DELIVERED_NAT timestamp;

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_EVIDENCE MODIFY DELIVERED_GW timestamp;

INSERT INTO domibusconnector.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('3to4_upgrade_009_tb_update_DOMIBUS_CONNECTOR_EVIDENCE', 'StephanSpindler', 'db/changelog/v004/upgrade-3to4.xml', NOW(), 10, '7:59c078809ef08acb898a08c879b4bc8e', 'modifyDataType columnName=ID, tableName=DOMIBUS_CONNECTOR_EVIDENCE; modifyDataType columnName=MESSAGE_ID, tableName=DOMIBUS_CONNECTOR_EVIDENCE; modifyDataType columnName=EVIDENCE, tableName=DOMIBUS_CONNECTOR_EVIDENCE; modifyDataType columnName=DEL...', '', 'EXECUTED', NULL, NULL, '3.5.3', '3441985564');

--  Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_010_tb_create_DOMIBUS_CONNECTOR_CONTENT_TYPE::StephanSpindler
CREATE TABLE domibusconnector.MESSAGE_CONTENT_TYPE (MESSAGE_CONTENT_TYPE VARCHAR(255) NOT NULL);

ALTER TABLE domibusconnector.MESSAGE_CONTENT_TYPE ADD PRIMARY KEY (MESSAGE_CONTENT_TYPE);

INSERT INTO domibusconnector.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('3to4_upgrade_010_tb_create_DOMIBUS_CONNECTOR_CONTENT_TYPE', 'StephanSpindler', 'db/changelog/v004/upgrade-3to4.xml', NOW(), 11, '7:9181d79e4fe0ea7a084b1eb4362aa21f', 'createTable tableName=MESSAGE_CONTENT_TYPE; addPrimaryKey constraintName=PK_DOMIBUS_CONN_02, tableName=MESSAGE_CONTENT_TYPE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3441985564');

--  Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_011_tb_create_DOMIBUS_CONNECTOR_BACKEND_INFO::StephanSpindler
CREATE TABLE domibusconnector.DOMIBUS_CONNECTOR_BACKEND_INFO (ID numeric(10, 0) NOT NULL, BACKEND_NAME VARCHAR(255) NOT NULL, BACKEND_KEY_ALIAS VARCHAR(255) NOT NULL, BACKEND_KEY_PASS VARCHAR(255) NOT NULL, BACKEND_SERVICE_TYPE VARCHAR(255) NULL, BACKEND_ENABLED BIT(1) NULL, BACKEND_DEFAULT BIT(1) NULL, BACKEND_DESCRIPTION LONGTEXT NULL, BACKEND_PUSH_ADDRESS VARCHAR(512) NULL);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_BACKEND_INFO ADD PRIMARY KEY (ID);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_BACKEND_INFO ADD CONSTRAINT UN_DOMIBUS_CONNECTOR_BACK_01 UNIQUE (BACKEND_NAME);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_BACKEND_INFO ADD CONSTRAINT UN_DOMIBUS_CONNECTOR_BACK_02 UNIQUE (BACKEND_KEY_ALIAS);

INSERT INTO domibusconnector.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('3to4_upgrade_011_tb_create_DOMIBUS_CONNECTOR_BACKEND_INFO', 'StephanSpindler', 'db/changelog/v004/upgrade-3to4.xml', NOW(), 12, '7:7485c1fc30423981d7e871b8f8cd94ce', 'createTable tableName=DOMIBUS_CONNECTOR_BACKEND_INFO; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_BACK_01, tableName=DOMIBUS_CONNECTOR_BACKEND_INFO; addUniqueConstraint constraintName=UN_DOMIBUS_CONNECTOR_BACK_01, tableName=DOMIBUS_CONNECTOR...', '', 'EXECUTED', NULL, NULL, '3.5.3', '3441985564');

--  Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_012_tb_create_DOMIBUS_CONNECTOR_BACK_2_S::StephanSpindler
CREATE TABLE domibusconnector.DOMIBUS_CONNECTOR_BACK_2_S (DOMIBUS_CONNECTOR_SERVICE_ID VARCHAR(255) NOT NULL, DOMIBUS_CONNECTOR_BACKEND_ID numeric(10, 0) NOT NULL);

INSERT INTO domibusconnector.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('3to4_upgrade_012_tb_create_DOMIBUS_CONNECTOR_BACK_2_S', 'StephanSpindler', 'db/changelog/v004/upgrade-3to4.xml', NOW(), 13, '7:6738c564ddf1050b2293afcaa665476e', 'createTable tableName=DOMIBUS_CONNECTOR_BACK_2_S', '', 'EXECUTED', NULL, NULL, '3.5.3', '3441985564');

--  Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_013_tb_update_DOMIBUS_CONNECTOR_ACTION::StephanSpindler
ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_ACTION MODIFY ACTION VARCHAR(255);

INSERT INTO domibusconnector.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('3to4_upgrade_013_tb_update_DOMIBUS_CONNECTOR_ACTION', 'StephanSpindler', 'db/changelog/v004/upgrade-3to4.xml', NOW(), 14, '7:73a2f99a837c4e1bebda8e5bf9752624', 'modifyDataType columnName=ACTION, tableName=DOMIBUS_CONNECTOR_ACTION', '', 'EXECUTED', NULL, NULL, '3.5.3', '3441985564');

--  Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_014_tb_create_DOMIBUS_CONNECTOR_BIGDATA::StephanSpindler
CREATE TABLE domibusconnector.DOMIBUS_CONNECTOR_BIGDATA (ID VARCHAR(255) NOT NULL, CHECKSUM LONGTEXT NULL, CREATED datetime NULL, MESSAGE_ID DECIMAL(10, 0) NULL, LAST_ACCESS datetime NULL, NAME LONGTEXT NULL, CONTENT LONGBLOB NULL, MIMETYPE VARCHAR(255) NULL);

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_BIGDATA ADD PRIMARY KEY (ID);

INSERT INTO domibusconnector.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('3to4_upgrade_014_tb_create_DOMIBUS_CONNECTOR_BIGDATA', 'StephanSpindler', 'db/changelog/v004/upgrade-3to4.xml', NOW(), 15, '7:62c6a7f71018321e1f1d1216bef5976d', 'createTable tableName=DOMIBUS_CONNECTOR_BIGDATA; addPrimaryKey tableName=DOMIBUS_CONNECTOR_BIGDATA', '', 'EXECUTED', NULL, NULL, '3.5.3', '3441985564');

--  Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_014_tb_create_DOMIBUS_CONNECTOR_BIGDATA_constraints::StephanSpindler
ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_BIGDATA ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_BIGDATA FOREIGN KEY (MESSAGE_ID) REFERENCES domibusconnector.DOMIBUS_CONNECTOR_MESSAGE (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

INSERT INTO domibusconnector.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('3to4_upgrade_014_tb_create_DOMIBUS_CONNECTOR_BIGDATA_constraints', 'StephanSpindler', 'db/changelog/v004/upgrade-3to4.xml', NOW(), 16, '7:34f4a9d6269a7dfa4e99b88a0fa71ee7', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_BIGDATA, constraintName=FK_DOMIBUS_CONNECTOR_BIGDATA, referencedTableName=DOMIBUS_CONNECTOR_MESSAGE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3441985564');

--  Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_020_fk_create::StephanSpindler
ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MSG_ERROR ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MSG_ERROR FOREIGN KEY (MESSAGE_ID) REFERENCES domibusconnector.DOMIBUS_CONNECTOR_MESSAGE (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MSG_CONT ADD CONSTRAINT FK_DOMIBUS_CONN_DOMIBUS_CON_03 FOREIGN KEY (CONTENT_TYPE) REFERENCES domibusconnector.MESSAGE_CONTENT_TYPE (MESSAGE_CONTENT_TYPE) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MSG_CONT ADD CONSTRAINT FK_DOMIBUS_CONN_DOMIBUS_CON_04 FOREIGN KEY (MESSAGE_ID) REFERENCES domibusconnector.DOMIBUS_CONNECTOR_MESSAGE (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_1 FOREIGN KEY (ACTION) REFERENCES domibusconnector.DOMIBUS_CONNECTOR_ACTION (ACTION) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_2 FOREIGN KEY (SERVICE) REFERENCES domibusconnector.DOMIBUS_CONNECTOR_SERVICE (service) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_3 FOREIGN KEY (FROM_PARTY_ID, FROM_PARTY_ROLE) REFERENCES domibusconnector.DOMIBUS_CONNECTOR_PARTY (PARTY_ID, ROLE) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_4 FOREIGN KEY (TO_PARTY_ID, TO_PARTY_ROLE) REFERENCES domibusconnector.DOMIBUS_CONNECTOR_PARTY (PARTY_ID, ROLE) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_I FOREIGN KEY (MESSAGE_ID) REFERENCES domibusconnector.DOMIBUS_CONNECTOR_MESSAGE (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_EVIDENCE ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_EVIDENCES FOREIGN KEY (MESSAGE_ID) REFERENCES domibusconnector.DOMIBUS_CONNECTOR_MESSAGE (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_BACK_2_S ADD CONSTRAINT FK_DOMIBUS_CONN_DOMIBUS_CON_01 FOREIGN KEY (DOMIBUS_CONNECTOR_BACKEND_ID) REFERENCES domibusconnector.DOMIBUS_CONNECTOR_BACKEND_INFO (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE domibusconnector.DOMIBUS_CONNECTOR_BACK_2_S ADD CONSTRAINT FK_DOMIBUS_CONN_DOMIBUS_CON_02 FOREIGN KEY (DOMIBUS_CONNECTOR_SERVICE_ID) REFERENCES domibusconnector.DOMIBUS_CONNECTOR_SERVICE (SERVICE) ON UPDATE NO ACTION ON DELETE NO ACTION;

INSERT INTO domibusconnector.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('3to4_upgrade_020_fk_create', 'StephanSpindler', 'db/changelog/v004/upgrade-3to4.xml', NOW(), 17, '7:a2a9651503e0c06089584f20dae034e3', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_MSG_ERROR, constraintName=FK_DOMIBUS_CONNECTOR_MSG_ERROR, referencedTableName=DOMIBUS_CONNECTOR_MESSAGE; addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_MSG_CONT, constraintName=FK_DO...', '', 'EXECUTED', NULL, NULL, '3.5.3', '3441985564');

--  Changeset db/changelog/v004/upgrade-3to4.xml::tag-db-domibus-4.0::StephanSpindler
INSERT INTO domibusconnector.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID, TAG) VALUES ('tag-db-domibus-4.0', 'StephanSpindler', 'db/changelog/v004/upgrade-3to4.xml', NOW(), 18, '7:9154cc53e107d3186ebc05f34ddc6844', 'tagDatabase', '', 'EXECUTED', NULL, NULL, '3.5.3', '3441985564', 'DOMIBUS_DB_V4.0');

--  Release Database Lock
UPDATE domibusconnector.DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;
