-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: db/changelog/v004/upgrade-3to4.xml
-- Ran at: 11.04.18 14:12
-- Against: WEBCONNECTOR@jdbc:oracle:thin:webconnector//@localhost:1521/xe
-- Liquibase version: 3.5.3
-- *********************************************************************

SET DEFINE OFF;

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_001_tb_DOMIBUS_CONNECTOR_SERVICE::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_SERVICE MODIFY SERVICE VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_SERVICE MODIFY SERVICE_TYPE VARCHAR2(512);

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_002_tb_DOMIBUS_CONNECTOR_PARTY::StephanSpinlder
ALTER TABLE DOMIBUS_CONNECTOR_PARTY MODIFY PARTY_ID VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_PARTY MODIFY ROLE VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_PARTY MODIFY PARTY_ID_TYPE VARCHAR2(512);

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_003_tb_DOMIBUS_CONNECTOR_MSG_ERROR::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR MODIFY ID NUMBER(10);
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR MODIFY MESSAGE_ID NUMBER(10);
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR MODIFY ERROR_MESSAGE VARCHAR2(512);
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR MODIFY CREATED TIMESTAMP;


-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_003_tb_DOMIBUS_CONNECTOR_MSG_ERROR_convert_error_source_to_clob::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR ADD ERROR_SOURCE_TEMP CLOB;
UPDATE DOMIBUS_CONNECTOR_MSG_ERROR SET ERROR_SOURCE_TEMP=ERROR_SOURCE;
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR DROP COLUMN ERROR_SOURCE;
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR RENAME COLUMN ERROR_SOURCE_TEMP TO ERROR_SOURCE;



-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_004_tb_create_DOMIBUS_CONNECTOR_MSG_CONT::StephanSpindler
CREATE TABLE DOMIBUS_CONNECTOR_MSG_CONT (ID NUMBER(10) NOT NULL, MESSAGE_ID NUMBER(10) NOT NULL, CONTENT_TYPE VARCHAR2(255), CONTENT BLOB);
ALTER TABLE DOMIBUS_CONNECTOR_MSG_CONT ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_MSG__01 PRIMARY KEY (ID);

-- Changeset db/changelog/v004/upgrade-3toINFO 11.04.18 14:12: liquibase: db/changelog/v004/upgrade-3to4.xml: db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_005_tb_update_DOMIBUS_CONNECTOR_MESSAGE_INFO::StephanSpindler: DOMIBUS_CONNECTOR_MESSAGE_INFO.ID datatype was changed to NUMBER(10)
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY ID NUMBER(10);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY MESSAGE_ID NUMBER(10);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY FROM_PARTY_ID VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY FROM_PARTY_ROLE VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY TO_PARTY_ID VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY TO_PARTY_ROLE VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY ORIGINAL_SENDER VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY FINAL_RECIPIENT VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY SERVICE VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY ACTION VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY CREATED TIMESTAMP;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY UPDATED TIMESTAMP;

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_006_tb_rename_DOMIBUS_CONNECTOR_MESSAGE::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGES RENAME TO DOMIBUS_CONNECTOR_MESSAGE;

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_007_tb_update_DOMIBUS_CONNECTOR_MESSAGE_modify_id::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE MODIFY ID NUMBER(10);

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_007_tb_update_DOMIBUS_CONNECTOR_MESSAGE_rename_nat_message_id::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE RENAME COLUMN NAT_MESSAGE_ID TO BACKEND_MESSAGE_ID;

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_007_tb_update_DOMIBUS_CONNECTOR_MESSAGE_confirmed_timestamp::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE MODIFY CONFIRMED TIMESTAMP;

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_007_tb_update_DOMIBUS_CONNECTOR_MESSAGE_rejected_timestamp::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE MODIFY REJECTED TIMESTAMP;

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_007_tb_update_DOMIBUS_CONNECTOR_MESSAGE_delivered_gw_timestamp::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE MODIFY DELIVERED_GW TIMESTAMP;

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_007_tb_update_DOMIBUS_CONNECTOR_MESSAGE_updated_timestamp::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE MODIFY UPDATED TIMESTAMP;

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_007_tb_update_DOMIBUS_CONNECTOR_MESSAGE_delivered_backend_timestamp::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE RENAME COLUMN DELIVERED_NAT TO DELIVERED_BACKEND;

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_007_tb_update_DOMIBUS_CONNECTOR_MESSAGE_add_Column_backend_name::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE ADD BACKEND_NAME VARCHAR2(255);

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_007_tb_update_DOMIBUS_CONNECTOR_MESSAGE_hashValue_oracle::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE ADD HASH_VALUE_TEMP CLOB;
UPDATE DOMIBUS_CONNECTOR_MESSAGE SET HASH_VALUE_TEMP=HASH_VALUE;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE DROP COLUMN HASH_VALUE;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE RENAME COLUMN HASH_VALUE_TEMP TO HASH_VALUE;

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_008_tb_ren_DOMIBUS_CONNECTOR_EVIDENCE::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCES RENAME TO DOMIBUS_CONNECTOR_EVIDENCE;

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_009_tb_update_DOMIBUS_CONNECTOR_EVIDENCE_mod_id_type::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE MODIFY ID NUMBER(10);

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_009_tb_update_DOMIBUS_CONNECTOR_EVIDENCE_mod_message_id_type::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE MODIFY MESSAGE_ID NUMBER(10);

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_009_tb_update_DOMIBUS_CONNECTOR_EVIDENCE_mode_evidence_oracle::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE ADD EVIDENCE_TEMP CLOB;
UPDATE DOMIBUS_CONNECTOR_EVIDENCE SET EVIDENCE_TEMP = EVIDENCE;
ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE DROP COLUMN EVIDENCE;
ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE RENAME COLUMN EVIDENCE_TEMP TO EVIDENCE;

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_009_tb_update_DOMIBUS_CONNECTOR_EVIDENCE_delivered_nat_timestamp::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE MODIFY DELIVERED_NAT TIMESTAMP;

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_009_tb_update_DOMIBUS_CONNECTOR_EVIDENCE_delivered_gw_timestamp::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE MODIFY DELIVERED_GW TIMESTAMP;

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_010_tb_create_DOMIBUS_CONNECTOR_CONTENT_TYPE::StephanSpindler
CREATE TABLE MESSAGE_CONTENT_TYPE (MESSAGE_CONTENT_TYPE VARCHAR2(255) NOT NULL);
ALTER TABLE MESSAGE_CONTENT_TYPE ADD CONSTRAINT PK_DOMIBUS_CONN_02 PRIMARY KEY (MESSAGE_CONTENT_TYPE);


-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_011_tb_create_DOMIBUS_CONNECTOR_BACKEND_INFO::StephanSpindler
CREATE TABLE DOMIBUS_CONNECTOR_BACKEND_INFO (ID NUMBER(10) NOT NULL, BACKEND_NAME VARCHAR2(255) NOT NULL, BACKEND_KEY_ALIAS VARCHAR2(255) NOT NULL, BACKEND_KEY_PASS VARCHAR2(255) NOT NULL, BACKEND_SERVICE_TYPE VARCHAR2(255), BACKEND_ENABLED NUMBER(1), BACKEND_DEFAULT NUMBER(1), BACKEND_DESCRIPTION CLOB, BACKEND_PUSH_ADDRESS VARCHAR2(512));
ALTER TABLE DOMIBUS_CONNECTOR_BACKEND_INFO ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_BACK_01 PRIMARY KEY (ID);
ALTER TABLE DOMIBUS_CONNECTOR_BACKEND_INFO ADD CONSTRAINT UN_DOMIBUS_CONNECTOR_BACK_01 UNIQUE (BACKEND_NAME);
ALTER TABLE DOMIBUS_CONNECTOR_BACKEND_INFO ADD CONSTRAINT UN_DOMIBUS_CONNECTOR_BACK_02 UNIQUE (BACKEND_KEY_ALIAS);

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_012_tb_create_DOMIBUS_CONNECTOR_BACK_2_S::StephanSpindler
CREATE TABLE DOMIBUS_CONNECTOR_BACK_2_S (DOMIBUS_CONNECTOR_SERVICE_ID VARCHAR2(255) NOT NULL, DOMIBUS_CONNECTOR_BACKEND_ID NUMBER(10) NOT NULL);

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_013_tb_update_DOMIBUS_CONNECTOR_ACTION::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_ACTION MODIFY ACTION VARCHAR2(255);

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_014_tb_create_DOMIBUS_CONNECTOR_BIGDATA::StephanSpindler
CREATE TABLE DOMIBUS_CONNECTOR_BIGDATA (ID VARCHAR2(255) NOT NULL, CHECKSUM CLOB, CREATED TIMESTAMP, MESSAGE_ID DECIMAL(10, 0), LAST_ACCESS TIMESTAMP, NAME CLOB, CONTENT BLOB, MIMETYPE VARCHAR2(255));
ALTER TABLE DOMIBUS_CONNECTOR_BIGDATA ADD PRIMARY KEY (ID);

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_014_tb_create_DOMIBUS_CONNECTOR_BIGDATA_constraints::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_BIGDATA ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_BIGDATA FOREIGN KEY (MESSAGE_ID) REFERENCES WEBCONNECTOR.DOMIBUS_CONNECTOR_MESSAGE (ID);

-- Changeset db/changelog/v004/upgrade-3to4.xml::3to4_upgrade_020_fk_create::StephanSpindler
-- Create all Foreign Keys
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MSG_ERROR FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID);
ALTER TABLE DOMIBUS_CONNECTOR_MSG_CONT ADD CONSTRAINT FK_DOMIBUS_CONN_DOMIBUS_CON_03 FOREIGN KEY (CONTENT_TYPE) REFERENCES MESSAGE_CONTENT_TYPE (MESSAGE_CONTENT_TYPE);
ALTER TABLE DOMIBUS_CONNECTOR_MSG_CONT ADD CONSTRAINT FK_DOMIBUS_CONN_DOMIBUS_CON_04 FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_1 FOREIGN KEY (ACTION) REFERENCES DOMIBUS_CONNECTOR_ACTION (ACTION);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_2 FOREIGN KEY (SERVICE) REFERENCES DOMIBUS_CONNECTOR_SERVICE (service);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_3 FOREIGN KEY (FROM_PARTY_ID, FROM_PARTY_ROLE) REFERENCES DOMIBUS_CONNECTOR_PARTY (PARTY_ID, ROLE);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_4 FOREIGN KEY (TO_PARTY_ID, TO_PARTY_ROLE) REFERENCES DOMIBUS_CONNECTOR_PARTY (PARTY_ID, ROLE);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_I FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID);
ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_EVIDENCES FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID);
ALTER TABLE DOMIBUS_CONNECTOR_BACK_2_S ADD CONSTRAINT FK_DOMIBUS_CONN_DOMIBUS_CON_01 FOREIGN KEY (DOMIBUS_CONNECTOR_BACKEND_ID) REFERENCES DOMIBUS_CONNECTOR_BACKEND_INFO (ID);
ALTER TABLE DOMIBUS_CONNECTOR_BACK_2_S ADD CONSTRAINT FK_DOMIBUS_CONN_DOMIBUS_CON_02 FOREIGN KEY (DOMIBUS_CONNECTOR_SERVICE_ID) REFERENCES DOMIBUS_CONNECTOR_SERVICE (SERVICE);
