--  *********************************************************************
--  Create MYSQL Database Script for DomibusConnector 4.1.x
--  *********************************************************************


CREATE TABLE DOMIBUS_CONNECTOR_SEQ_STORE
(
    SEQ_NAME  VARCHAR(255) NOT NULL,
    SEQ_VALUE BIGINT       NOT NULL
);
ALTER TABLE DOMIBUS_CONNECTOR_SEQ_STORE
    ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_SEQ_STORE PRIMARY KEY (SEQ_NAME);

INSERT INTO DOMIBUS_CONNECTOR_SEQ_STORE
VALUES ('DOMIBUS_CONNECTOR_MESSAGES.ID', 1000);
INSERT INTO DOMIBUS_CONNECTOR_SEQ_STORE
VALUES ('DOMIBUS_CONNECTOR_EVIDENCES.ID', 1000);
INSERT INTO DOMIBUS_CONNECTOR_SEQ_STORE
VALUES ('DOMIBUS_CONNECTOR_MESSAGE_INFO.ID', 1000);
INSERT INTO DOMIBUS_CONNECTOR_SEQ_STORE
VALUES ('DOMIBUS_CONNECTOR_MSG_ERROR.ID', 1000);
-- because of the default users (see below): ADMIN and USER the sequence starts with 1000 + 2
INSERT INTO DOMIBUS_CONNECTOR_SEQ_STORE
VALUES ('DOMIBUS_CONNECTOR_USER.ID', 1002);
INSERT INTO DOMIBUS_CONNECTOR_SEQ_STORE
VALUES ('DOMIBUS_CONNECTOR_USER_PWD.ID', 1002);
INSERT INTO DOMIBUS_CONNECTOR_SEQ_STORE
VALUES ('DOMIBUS_CONNECTOR_PROPERTY.ID', 1000);

CREATE TABLE DOMIBUS_CONNECTOR_SERVICE
(
    SERVICE      VARCHAR(255) NOT NULL,
    SERVICE_TYPE VARCHAR(255) NOT NULL
);
ALTER TABLE DOMIBUS_CONNECTOR_SERVICE
    ADD CONSTRAINT PK_DC_SERVICE PRIMARY KEY (SERVICE);

CREATE TABLE DOMIBUS_CONNECTOR_PARTY
(
    PARTY_ID      VARCHAR(255) NOT NULL,
    ROLE          VARCHAR(255) NOT NULL,
    PARTY_ID_TYPE VARCHAR(512)
);
ALTER TABLE DOMIBUS_CONNECTOR_PARTY
    ADD CONSTRAINT PK_DC_PARTY PRIMARY KEY (PARTY_ID, ROLE);

CREATE TABLE DOMIBUS_CONNECTOR_MSG_ERROR
(
    ID            BIGINT        NOT NULL,
    MESSAGE_ID    BIGINT        NOT NULL,
    ERROR_MESSAGE VARCHAR(2048) NOT NULL,
    DETAILED_TEXT LONGTEXT,
    ERROR_SOURCE  LONGTEXT,
    CREATED       TIMESTAMP      NOT NULL
);
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR
    ADD CONSTRAINT PK_DC_MSG_ERROR PRIMARY KEY (ID);

CREATE TABLE DOMIBUS_CONNECTOR_MSG_CONT
(
    ID           BIGINT NOT NULL,
    MESSAGE_ID   BIGINT,
    CONTENT_TYPE VARCHAR(255),
    CONTENT      LONGBLOB,
    CHECKSUM     LONGTEXT,
    CREATED      TIMESTAMP NULL
);
ALTER TABLE DOMIBUS_CONNECTOR_MSG_CONT
    ADD CONSTRAINT PK_DC_MSG_CONT PRIMARY KEY (ID);

CREATE TABLE DOMIBUS_CONNECTOR_BIGDATA
(
    ID          VARCHAR(255) NOT NULL,
    CHECKSUM    LONGTEXT,
    CREATED     TIMESTAMP NULL,
    MESSAGE_ID  BIGINT,
    LAST_ACCESS TIMESTAMP NULL,
    NAME        LONGTEXT,
    CONTENT     LONGBLOB,
    MIMETYPE    VARCHAR(255)
);
ALTER TABLE DOMIBUS_CONNECTOR_BIGDATA
    ADD PRIMARY KEY (ID);

CREATE TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO
(
    ID                   BIGINT NOT NULL,
    MESSAGE_ID           BIGINT NOT NULL,
    CONNECTOR_MESSAGE_ID VARCHAR(255),
    FROM_PARTY_ID        VARCHAR(255),
    FROM_PARTY_ROLE      VARCHAR(255),
    TO_PARTY_ID          VARCHAR(255),
    TO_PARTY_ROLE        VARCHAR(255),
    ORIGINAL_SENDER      VARCHAR(255),
    FINAL_RECIPIENT      VARCHAR(255),
    SERVICE              VARCHAR(255),
    ACTION               VARCHAR(255),
    CREATED              TIMESTAMP NULL,
    UPDATED              TIMESTAMP NULL
);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO
    ADD CONSTRAINT PK_DC_MSG_INFO PRIMARY KEY (ID);

CREATE TABLE DOMIBUS_CONNECTOR_MESSAGE
(
    ID                   BIGINT NOT NULL,
    EBMS_MESSAGE_ID      VARCHAR(255),
    BACKEND_MESSAGE_ID   VARCHAR(255),
    BACKEND_NAME         VARCHAR(255),
    CONNECTOR_MESSAGE_ID VARCHAR(255),
    CONVERSATION_ID      VARCHAR(255),
    DIRECTION            VARCHAR(10),
    HASH_VALUE           LONGTEXT,
    CONFIRMED            TIMESTAMP NULL,
    REJECTED             TIMESTAMP NULL,
    DELIVERED_BACKEND    TIMESTAMP NULL,
    DELIVERED_GW         TIMESTAMP NULL,
    UPDATED              TIMESTAMP NULL,
    CREATED              TIMESTAMP NULL
);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE
    ADD CONSTRAINT PK_DC_MESSAGE PRIMARY KEY (ID);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE
    ADD CONSTRAINT UN_DC_MSG_ID_01 UNIQUE (CONNECTOR_MESSAGE_ID);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE
    ADD CONSTRAINT UN_DC_MSG_EBMS_MSG UNIQUE (EBMS_MESSAGE_ID);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE
    ADD CONSTRAINT UN_DC_MSG_NAT_MSG_01 UNIQUE (BACKEND_MESSAGE_ID);

CREATE TABLE DOMIBUS_CONNECTOR_EVIDENCE
(
    ID                   BIGINT NOT NULL,
    MESSAGE_ID           BIGINT NOT NULL,
    CONNECTOR_MESSAGE_ID VARCHAR(255),
    TYPE                 VARCHAR(255),
    EVIDENCE             LONGTEXT,
    DELIVERED_NAT        TIMESTAMP NULL,
    DELIVERED_GW         TIMESTAMP NULL,
    UPDATED              TIMESTAMP NULL
);
ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE
    ADD CONSTRAINT PK_DC_EVIDENCE PRIMARY KEY (ID);
CREATE INDEX IXFK_DC_EV_01 ON DOMIBUS_CONNECTOR_EVIDENCE (CONNECTOR_MESSAGE_ID);

CREATE TABLE DOMIBUS_CONNECTOR_CONT_TYPE
(
    MESSAGE_CONTENT_TYPE VARCHAR(255) NOT NULL
);
ALTER TABLE DOMIBUS_CONNECTOR_CONT_TYPE
    ADD CONSTRAINT PK_DC_CONT_TYPE PRIMARY KEY (MESSAGE_CONTENT_TYPE);

CREATE TABLE DOMIBUS_CONNECTOR_ACTION
(
    ACTION       VARCHAR(255) NOT NULL,
    PDF_REQUIRED BOOLEAN      NOT NULL
);
ALTER TABLE DOMIBUS_CONNECTOR_ACTION
    ADD CONSTRAINT PK_DC_ACTION PRIMARY KEY (ACTION);

CREATE TABLE DOMIBUS_CONNECTOR_BACKEND_INFO
(
    ID                   BIGINT       NOT NULL,
    BACKEND_NAME         VARCHAR(255) NOT NULL,
    BACKEND_KEY_ALIAS    VARCHAR(255) NOT NULL,
    BACKEND_KEY_PASS     VARCHAR(255),
    BACKEND_SERVICE_TYPE VARCHAR(255),
    BACKEND_ENABLED      BOOLEAN DEFAULT TRUE,
    BACKEND_DEFAULT      BOOLEAN DEFAULT FALSE,
    BACKEND_DESCRIPTION  LONGTEXT,
    BACKEND_PUSH_ADDRESS LONGTEXT
);
ALTER TABLE DOMIBUS_CONNECTOR_BACKEND_INFO
    ADD CONSTRAINT PK_DC_BACK_INFO PRIMARY KEY (ID);

ALTER TABLE DOMIBUS_CONNECTOR_BACKEND_INFO
    ADD CONSTRAINT UN_DC_BACK_01 UNIQUE (BACKEND_NAME);
ALTER TABLE DOMIBUS_CONNECTOR_BACKEND_INFO
    ADD CONSTRAINT UN_DC_BACK_02 UNIQUE (BACKEND_KEY_ALIAS);

CREATE TABLE DOMIBUS_CONNECTOR_BACK_2_S
(
    DOMIBUS_CONNECTOR_SERVICE_ID VARCHAR(255) NOT NULL,
    DOMIBUS_CONNECTOR_BACKEND_ID BIGINT       NOT NULL
);
ALTER TABLE DOMIBUS_CONNECTOR_BACK_2_S
    ADD CONSTRAINT PK_DC_BACK2S PRIMARY KEY (DOMIBUS_CONNECTOR_SERVICE_ID, DOMIBUS_CONNECTOR_BACKEND_ID);

ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR
    ADD CONSTRAINT FK_DC_MSG_ERROR_01 FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID);

ALTER TABLE DOMIBUS_CONNECTOR_MSG_CONT
    ADD CONSTRAINT FK_DC_CON_01 FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID);

ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO
    ADD CONSTRAINT FK_DC_MSG_INFO_01 FOREIGN KEY (ACTION) REFERENCES DOMIBUS_CONNECTOR_ACTION (ACTION);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO
    ADD CONSTRAINT FK_DC_MSG_INFO_02 FOREIGN KEY (SERVICE) REFERENCES DOMIBUS_CONNECTOR_SERVICE (SERVICE);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO
    ADD CONSTRAINT FK_DC_MSG_INFO_03 FOREIGN KEY (FROM_PARTY_ID, FROM_PARTY_ROLE) REFERENCES DOMIBUS_CONNECTOR_PARTY (PARTY_ID, ROLE);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO
    ADD CONSTRAINT FK_DC_MSG_INFO_04 FOREIGN KEY (TO_PARTY_ID, TO_PARTY_ROLE) REFERENCES DOMIBUS_CONNECTOR_PARTY (PARTY_ID, ROLE);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO
    ADD CONSTRAINT FK_DC_MSG_INFO_I FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID);

ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE
    ADD CONSTRAINT FK_DC_EVIDENCES_01 FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID);

ALTER TABLE DOMIBUS_CONNECTOR_BACK_2_S
    ADD CONSTRAINT FK_DC_BACK2S_01 FOREIGN KEY (DOMIBUS_CONNECTOR_BACKEND_ID) REFERENCES DOMIBUS_CONNECTOR_BACKEND_INFO (ID);
ALTER TABLE DOMIBUS_CONNECTOR_BACK_2_S
    ADD CONSTRAINT FK_DC_BACK2S_02 FOREIGN KEY (DOMIBUS_CONNECTOR_SERVICE_ID) REFERENCES DOMIBUS_CONNECTOR_SERVICE (SERVICE);

ALTER TABLE DOMIBUS_CONNECTOR_BIGDATA
    ADD CONSTRAINT FK_DC_BIGDATA_01 FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID);

CREATE TABLE DOMIBUS_CONNECTOR_PROPERTY
(
    ID             BIGINT        NOT NULL,
    PROPERTY_NAME  VARCHAR(512)  NOT NULL,
    PROPERTY_VALUE VARCHAR(1024) NULL
);
ALTER TABLE DOMIBUS_CONNECTOR_PROPERTY
    ADD CONSTRAINT PK_DC_PROPERTY
        PRIMARY KEY (PROPERTY_NAME);


-- USER:

CREATE TABLE DOMIBUS_CONNECTOR_USER
(
    ID                     BIGINT                 NOT NULL,
    USERNAME               VARCHAR(50)            NOT NULL,
    ROLE                   VARCHAR(50)            NOT NULL,
    LOCKED                 BOOLEAN  DEFAULT FALSE NOT NULL,
    NUMBER_OF_GRACE_LOGINS SMALLINT DEFAULT 5     NOT NULL,
    GRACE_LOGINS_USED      SMALLINT DEFAULT 0     NOT NULL,
    CREATED                TIMESTAMP               NOT NULL
);

CREATE TABLE DOMIBUS_CONNECTOR_USER_PWD
(
    ID          BIGINT             NOT NULL,
    USER_ID     BIGINT             NOT NULL,
    PASSWORD    VARCHAR(1024)      NOT NULL,
    SALT        VARCHAR(512)       NOT NULL,
    CURRENT_PWD SMALLINT DEFAULT 0 NOT NULL,
    INITIAL_PWD SMALLINT DEFAULT 0 NOT NULL,
    CREATED     TIMESTAMP           NOT NULL
);

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE DOMIBUS_CONNECTOR_USER
    ADD CONSTRAINT PK_DC_USER
        PRIMARY KEY (ID);

ALTER TABLE DOMIBUS_CONNECTOR_USER_PWD
    ADD CONSTRAINT PK_DC_USER_PWD
        PRIMARY KEY (ID);

CREATE INDEX IXFK_DC_USER_PWD_01
    ON DOMIBUS_CONNECTOR_USER_PWD (USER_ID);

/* Create Foreign Key Constraints */

ALTER TABLE DOMIBUS_CONNECTOR_USER_PWD
    ADD CONSTRAINT FK_DC_USER_PWD_01
        FOREIGN KEY (USER_ID) REFERENCES DOMIBUS_CONNECTOR_USER (ID);

INSERT INTO DOMIBUS_CONNECTOR_USER (ID, USERNAME, ROLE, LOCKED, NUMBER_OF_GRACE_LOGINS, GRACE_LOGINS_USED,
                                    CREATED)
VALUES (1000, 'admin', 'ADMIN', 0, 5, 0, NOW());
INSERT INTO DOMIBUS_CONNECTOR_USER_PWD (ID, USER_ID, PASSWORD, SALT, CURRENT_PWD, INITIAL_PWD, CREATED)
VALUES (1000, 1000,
        '2bf5e637d0d82a75ca43e3be85df2c23febffc0cc221f5e010937005df478a19b5eaab59fe7e4e97f6b43ba648c169effd432e19817f386987d058c239236306',
        '5b424031616564356639', 1, 1, NOW());

INSERT INTO DOMIBUS_CONNECTOR_USER (ID, USERNAME, ROLE, LOCKED, NUMBER_OF_GRACE_LOGINS, GRACE_LOGINS_USED,
                                    CREATED)
VALUES (1001, 'user', 'USER', 0, 5, 0, NOW());
INSERT INTO DOMIBUS_CONNECTOR_USER_PWD (ID, USER_ID, PASSWORD, SALT, CURRENT_PWD, INITIAL_PWD, CREATED)
VALUES (1001, 1001,
        '2bf5e637d0d82a75ca43e3be85df2c23febffc0cc221f5e010937005df478a19b5eaab59fe7e4e97f6b43ba648c169effd432e19817f386987d058c239236306',
        '5b424031616564356639', 1, 1, NOW());

-- the seq store is already updated, see top of this file

-- END USER

CREATE TABLE DC_DB_VERSION
(
    TAG VARCHAR(255) PRIMARY KEY
);
INSERT INTO DC_DB_VERSION (TAG)
VALUES ('V4.1.5');