== Changelog for domibusConnector-4.4.x

=== 4.4.0

==== API changes

* New API web-service methods to support backend pull mechanism with technical message acknowledgement.
* The "role" of parties in message transition model is set to "optional".
* Additional field to give backends the possibility to add the informaiton if the business document of one message is either SIGNATURE_BASED or AUTHENTICATION_BASED. 

For further details see the following chapters of the domibusConnector-Architecture.pdf:

* Chapter 6. Backend message routing
* Chapter 4. domibusConnectorAPI

If the domibusConnectorClient-Libraries are in place, those also need to be upgraded to version 4.4 if this feature should be used. 

==== Backend implementations/features

* Moving a message into a DLQ in case of an error.
* Integrated eCodex security library into domibusConnector sources.
* Integrated evidenceBuilder library into domibusConnector sources.
* JavaKeyStore handling can now be done within database.
* Connector trust store is now seperated from document validation trust-store.
* Support for JTA transactions
* Default backend plugin for connector test messages allows to receive and send connector test messages.
* The ebMS property "role" as part of the ebMS party definition will be set by the connector. 
* Flag PDF_REQUIRED in table DOMIBUS_CONNECTOR_ACTION removed as it is obsolete.

For further details see the following chapters of the domibusConnector-Architecture.pdf:

* Chapter 5. Message Processing


==== UI implementations/features

* New PMode-Set handling.
* UI Configuration support for Link Partners
* UI Configuration support for message routing to the backends.
* UI support to retry messages to link partner.
* UI Support for JMS Monitoring.
* UI Support to see and send Connector Test Messages.

For all new features in the UI online help pages are integrated.

==== Documentation

The maven-site documentation has been replaced by static html documentation.
The documentation can be fully accessed via the UI of the domibusConnector.

Also, some PDF files are generated with content from the static html documentation.
Those PDF documents are shipped in the distribution package.
They are:

* installation_guide.pdf
* Upgrade-Manual.pdf
* domibusConnectorAPI.pdf
* domibusConnector-Architecture.pdf
* Changelog.pdf


=== 4.4.1

* Multiple Fixes within UI

=== 4.4.2

* Fix related to log4j2 security issue  (upgrade to 2.15.0)

=== 4.4.3

* Fix related to log4j2 security issue (upgrade to 2.17.0)

=== 4.4.4

* Fix problems with certificate verification: The CommonCertificateVerifier has ignored any
configured restrictions on AIA checking. This has lead to a very long message processing
if the AIA source was not reachable.


=== 4.4.5

==== Fixes

* Multiple updates of dependentant libraries
* Fix for issues related to pull for web service backends
* UI fix for enable change of message process settings
** EBMS generation
** should generated evidences relayed back to backend
* Fix for DOMIBUS_CONNECTOR_MSG_CONT entity: The created field was not filled by default with the current timestamp.
* Fix for missing class issue [Ticket#55054]: Explicitly added dss-crl-parser-x509crl as dependency.
* Fix issue with 4.4.x initial scripts at table DC_TRANSPORT_STEP => TRANSPORT_MESSAGE column should be TRANSPORTED_MESSAGE
* Add prometheus metrics export interface dependency + documentation
* Extend documentation
* Additional work on slow certificate verification: Under some circumstances message processing is slow. Because the DSS-Tools try to lookup AIA or other certificate related information. This occurs because currently not all Lookup Classes from SecurityToolkit and EvidenceToolkit are using the connector configuration. This has been fixed by removing the DataLoader from CommonCertificateVerifier class (the common config is still not used in every certificate verifier!).
* Removed deprecated parts from installation manual
* Fixed -Dconnector.config.file property is ignored by connector