:description: HA Support
:library: Asciidoctor

:imgdir: ../resources/images/
:imagesdir: ../{imgdir}

= HA Support

== HA Manual

=== Introduction

Shared Components:

==== Message Server

The connector internally uses a queuing system do decouple the message handling processes. As this queuing process
is started by the connector internally running more than one connector requires this connector to be clustered.
So this queuing system has to be configured externally.

==== Filesystem

The connector is also storing payloads on the filesystem. If more than one connector is running at the same time,
every connector needs access to the same storage location.

==== Timer Jobs

Within the connector multiple timer-jobs are triggered by the quartz framework. To avoid triggering it
on every connector node, quartz must also be aware of running within a cluster.

=== Configuration


==== Configure Message Server

The JMS Server is configured by the spring-framework so the default spring-properties can be uses:
A detail overview of the used queues is provided by this document: xref:connector_message_flow.adoc[Connector Message Flow]

Example for ActiveMQ-Configuration:
----
spring.activemq.broker-url=
spring.activemq.password=
spring.activemq.user=
----

Other JMS-providers are also supported as long as they have a spring-support and the required libraries
are on the java-classpath.

==== Configure Quartz

----
spring.quartz.properties.org.quartz.jobStore.isClustered=true
spring.quartz.properties.org.quartz.scheduler.instanceName = DomibusConnectorClusteredScheduler
spring.quartz.properties.org.quartz.scheduler.instanceId = AUTO
----


=== Backend and Gateway Connection

As the connector exposes webservices to gateway and the backends, this
services should be made fault-tolerant with an load-balancer.


