package backend.ecodex.org._1_1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-10-08T13:30:14.933+02:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "BackendService", 
                  wsdlLocation = "file:/D:/Entwicklung/git/connector/ECodexConnector/ECodexConnectorGatewayWebserviceClient/src/main/resources/eu/ecodex/connector/gwc/wsdl/BackendService-1_1.wsdl",
                  targetNamespace = "http://org.ecodex.backend/1_1/") 
public class BackendService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://org.ecodex.backend/1_1/", "BackendService");
    public final static QName BackendPort = new QName("http://org.ecodex.backend/1_1/", "BackendPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Entwicklung/git/connector/ECodexConnector/ECodexConnectorGatewayWebserviceClient/src/main/resources/eu/ecodex/connector/gwc/wsdl/BackendService-1_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BackendService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/Entwicklung/git/connector/ECodexConnector/ECodexConnectorGatewayWebserviceClient/src/main/resources/eu/ecodex/connector/gwc/wsdl/BackendService-1_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BackendService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BackendService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BackendService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns BackendInterface
     */
    @WebEndpoint(name = "BackendPort")
    public BackendInterface getBackendPort() {
        return super.getPort(BackendPort, BackendInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BackendInterface
     */
    @WebEndpoint(name = "BackendPort")
    public BackendInterface getBackendPort(WebServiceFeature... features) {
        return super.getPort(BackendPort, BackendInterface.class, features);
    }

}
