
package backend.ecodex.org._1_1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-10-08T13:30:14.918+02:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "FaultDetail", targetNamespace = "http://org.ecodex.backend/1_1/")
public class DownloadMessageFault extends Exception {
    
    private backend.ecodex.org._1_1.FaultDetail faultDetail;

    public DownloadMessageFault() {
        super();
    }
    
    public DownloadMessageFault(String message) {
        super(message);
    }
    
    public DownloadMessageFault(String message, Throwable cause) {
        super(message, cause);
    }

    public DownloadMessageFault(String message, backend.ecodex.org._1_1.FaultDetail faultDetail) {
        super(message);
        this.faultDetail = faultDetail;
    }

    public DownloadMessageFault(String message, backend.ecodex.org._1_1.FaultDetail faultDetail, Throwable cause) {
        super(message, cause);
        this.faultDetail = faultDetail;
    }

    public backend.ecodex.org._1_1.FaultDetail getFaultInfo() {
        return this.faultDetail;
    }
}
