MERGE INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES (1, 1, 'domibus-blue', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');
MERGE INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES (2, 1, 'domibus-red', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');

MERGE INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION, PDF_REQUIRED) VALUES (1, 1, 'action1', false);
MERGE INTO DOMIBUS_CONNECTOR_SERVICE (ID, FK_PMODE_SET, SERVICE, SERVICE_TYPE) VALUES (1, 1, 'service1', 'servicetype');

MERGE INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION, PDF_REQUIRED) VALUES (2, 1, 'Form_A', false);
MERGE INTO DOMIBUS_CONNECTOR_SERVICE (ID, FK_PMODE_SET, SERVICE, SERVICE_TYPE) VALUES (2, 1, 'EPO', 'servicetype');

