DROP TABLE ECODEX_EVIDENCES;
DROP TABLE ECODEX_MESSAGES;
DROP TABLE ECODEX_SEQ_STORE;
DROP TABLE ECODEX_PARTNER;
DROP TABLE ECODEX_ACTION;
DROP TABLE ECODEX_SERVICE;

CREATE TABLE ECODEX_MESSAGES (
	ID NUMBER(10) NOT NULL,
	EBMS_MESSAGE_ID VARCHAR2(255) UNIQUE,
	NAT_MESSAGE_ID VARCHAR2(255) UNIQUE,
	CONVERSATION_ID VARCHAR2(255),
	DIRECTION VARCHAR2(10),
	HASH_VALUE VARCHAR2(1000),
	CONFIRMED TIMESTAMP,
	REJECTED TIMESTAMP,
	DELIVERED_NAT TIMESTAMP,
	DELIVERED_GW TIMESTAMP,
	UPDATED TIMESTAMP,
	PRIMARY KEY (ID)
);

CREATE TABLE ECODEX_EVIDENCES (
	ID  NUMBER(10) NOT NULL,
	MESSAGE_ID  NUMBER(10) NOT NULL,
	TYPE VARCHAR2(255),
	EVIDENCE CLOB,
	DELIVERED_NAT TIMESTAMP,
	DELIVERED_GW TIMESTAMP,
	UPDATED TIMESTAMP,
	PRIMARY KEY (ID),
	FOREIGN KEY (MESSAGE_ID) REFERENCES ECODEX_MESSAGES (ID)
);

CREATE TABLE ECODEX_SEQ_STORE (
	SEQ_NAME VARCHAR2(255) NOT NULL,
	SEQ_VALUE  NUMBER(10) NOT NULL,
	PRIMARY KEY(SEQ_NAME)
);

INSERT INTO ECODEX_SEQ_STORE VALUES ('ECODEX_MESSAGES.ID', 0);
INSERT INTO ECODEX_SEQ_STORE VALUES ('ECODEX_EVIDENCES.ID', 0);

CREATE TABLE ECODEX_PARTY (
	PARTY_ID VARCHAR2(50) NOT NULL,
	ROLE VARCHAR2(50) NOT NULL,
	PRIMARY KEY (PARTY_ID, ROLE)
);

INSERT INTO ECODEX_PARTY VALUES ('AT', 'GW');
INSERT INTO ECODEX_PARTY VALUES ('DE', 'GW');
INSERT INTO ECODEX_PARTY VALUES ('EE', 'GW');
INSERT INTO ECODEX_PARTY VALUES ('ES', 'GW');
INSERT INTO ECODEX_PARTY VALUES ('EU', 'GW');
INSERT INTO ECODEX_PARTY VALUES ('IT', 'GW');

CREATE TABLE ECODEX_ACTION (
	ECDX_ACTION VARCHAR2(50) NOT NULL,
	PRIMARY KEY (ECDX_ACTION)
);

INSERT INTO ECODEX_ACTION VALUES ('Form_A');
INSERT INTO ECODEX_ACTION VALUES ('Form_B');
INSERT INTO ECODEX_ACTION VALUES ('Form_C');
INSERT INTO ECODEX_ACTION VALUES ('Form_D');
INSERT INTO ECODEX_ACTION VALUES ('Form_E');
INSERT INTO ECODEX_ACTION VALUES ('Form_F');
INSERT INTO ECODEX_ACTION VALUES ('Form_G');
INSERT INTO ECODEX_ACTION VALUES ('SubmissionAcceptanceRejection');
INSERT INTO ECODEX_ACTION VALUES ('RelayREMMDAcceptanceRejection');
INSERT INTO ECODEX_ACTION VALUES ('DeliveryNonDeliveryToRecipient');
INSERT INTO ECODEX_ACTION VALUES ('RetrievalNonRetrievalToRecipient');

CREATE TABLE ECODEX_SERVICE (
	ECDX_SERVICE VARCHAR2(50) NOT NULL,
	PRIMARY KEY (ECDX_SERVICE)
);

INSERT INTO ECODEX_SERVICE VALUES ('EPO');

commit;