package eu.domibus.connector.common.enums;

public enum EvidenceType {
    SUBMISSION_ACCEPTANCE, SUBMISSION_REJECTION, RELAY_REMMD_ACCEPTANCE, RELAY_REMMD_REJECTION, RELAY_REMMD_FAILURE, DELIVERY, NON_DELIVERY, RETRIEVAL, NON_RETRIEVAL;

}
