
package backend.ecodex.org;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-08T10:04:35.289+02:00
 * Generated source version: 2.6.1
 * 
 */
public final class BackendInterface_BackendPort_Client {

    private static final QName SERVICE_NAME = new QName("http://org.ecodex.backend", "BackendService");

    private BackendInterface_BackendPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BackendService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BackendService ss = new BackendService(wsdlURL, SERVICE_NAME);
        BackendInterface port = ss.getBackendPort();  
        
        {
        System.out.println("Invoking downloadMessage...");
        backend.ecodex.org.DownloadMessageRequest _downloadMessage_downloadMessageRequest = new backend.ecodex.org.DownloadMessageRequest();
        _downloadMessage_downloadMessageRequest.setMessageID("MessageID1471874823");
        javax.xml.ws.Holder<backend.ecodex.org.DownloadMessageResponse> _downloadMessage_downloadMessageResponse = new javax.xml.ws.Holder<backend.ecodex.org.DownloadMessageResponse>();
        javax.xml.ws.Holder<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Messaging> _downloadMessage_ebMSHeaderInfo = new javax.xml.ws.Holder<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Messaging>();
        try {
            port.downloadMessage(_downloadMessage_downloadMessageRequest, _downloadMessage_downloadMessageResponse, _downloadMessage_ebMSHeaderInfo);

            System.out.println("downloadMessage._downloadMessage_downloadMessageResponse=" + _downloadMessage_downloadMessageResponse.value);
            System.out.println("downloadMessage._downloadMessage_ebMSHeaderInfo=" + _downloadMessage_ebMSHeaderInfo.value);
        } catch (DownloadMessageFault e) { 
            System.out.println("Expected exception: downloadMessageFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking sendMessageWithReference...");
        backend.ecodex.org.SendRequestURL _sendMessageWithReference_sendRequestURL = new backend.ecodex.org.SendRequestURL();
        java.util.List<java.lang.String> _sendMessageWithReference_sendRequestURLPayload = new java.util.ArrayList<java.lang.String>();
        java.lang.String _sendMessageWithReference_sendRequestURLPayloadVal1 = "_sendMessageWithReference_sendRequestURLPayloadVal1211561620";
        _sendMessageWithReference_sendRequestURLPayload.add(_sendMessageWithReference_sendRequestURLPayloadVal1);
        _sendMessageWithReference_sendRequestURL.getPayload().addAll(_sendMessageWithReference_sendRequestURLPayload);
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Messaging _sendMessageWithReference_ebMSHeaderInfo = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Messaging();
        java.util.List<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.SignalMessage> _sendMessageWithReference_ebMSHeaderInfoSignalMessage = new java.util.ArrayList<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.SignalMessage>();
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.SignalMessage _sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1 = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.SignalMessage();
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.MessageInfo _sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1MessageInfo = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.MessageInfo();
        _sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1MessageInfo.setTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2012-08-08T10:04:35.320+02:00"));
        _sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1MessageInfo.setMessageId("MessageId252378274");
        _sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1MessageInfo.setRefToMessageId("RefToMessageId-1875068311");
        _sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1.setMessageInfo(_sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1MessageInfo);
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PullRequest _sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1PullRequest = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PullRequest();
        java.util.List<java.lang.Object> _sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1PullRequestAny = new java.util.ArrayList<java.lang.Object>();
        _sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1PullRequest.getAny().addAll(_sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1PullRequestAny);
        _sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1PullRequest.setMpc("Mpc-1054873125");
        _sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1.setPullRequest(_sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1PullRequest);
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Receipt _sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1Receipt = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Receipt();
        java.util.List<java.lang.Object> _sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1ReceiptAny = new java.util.ArrayList<java.lang.Object>();
        _sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1Receipt.getAny().addAll(_sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1ReceiptAny);
        _sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1.setReceipt(_sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1Receipt);
        java.util.List<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Error> _sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1Error = new java.util.ArrayList<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Error>();
        _sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1.getError().addAll(_sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1Error);
        java.util.List<java.lang.Object> _sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1Any = new java.util.ArrayList<java.lang.Object>();
        _sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1.getAny().addAll(_sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1Any);
        _sendMessageWithReference_ebMSHeaderInfoSignalMessage.add(_sendMessageWithReference_ebMSHeaderInfoSignalMessageVal1);
        _sendMessageWithReference_ebMSHeaderInfo.getSignalMessage().addAll(_sendMessageWithReference_ebMSHeaderInfoSignalMessage);
        java.util.List<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.UserMessage> _sendMessageWithReference_ebMSHeaderInfoUserMessage = new java.util.ArrayList<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.UserMessage>();
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.UserMessage _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1 = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.UserMessage();
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.MessageInfo _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1MessageInfo = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.MessageInfo();
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1MessageInfo.setTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2012-08-08T10:04:35.320+02:00"));
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1MessageInfo.setMessageId("MessageId-1790232621");
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1MessageInfo.setRefToMessageId("RefToMessageId1262136523");
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1.setMessageInfo(_sendMessageWithReference_ebMSHeaderInfoUserMessageVal1MessageInfo);
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartyInfo _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1PartyInfo = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartyInfo();
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.From _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1PartyInfoFrom = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.From();
        java.util.List<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartyId> _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1PartyInfoFromPartyId = new java.util.ArrayList<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartyId>();
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1PartyInfoFrom.getPartyId().addAll(_sendMessageWithReference_ebMSHeaderInfoUserMessageVal1PartyInfoFromPartyId);
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1PartyInfoFrom.setRole("Role-82337518");
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1PartyInfo.setFrom(_sendMessageWithReference_ebMSHeaderInfoUserMessageVal1PartyInfoFrom);
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.To _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1PartyInfoTo = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.To();
        java.util.List<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartyId> _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1PartyInfoToPartyId = new java.util.ArrayList<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartyId>();
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1PartyInfoTo.getPartyId().addAll(_sendMessageWithReference_ebMSHeaderInfoUserMessageVal1PartyInfoToPartyId);
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1PartyInfoTo.setRole("Role-2001407051");
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1PartyInfo.setTo(_sendMessageWithReference_ebMSHeaderInfoUserMessageVal1PartyInfoTo);
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1.setPartyInfo(_sendMessageWithReference_ebMSHeaderInfoUserMessageVal1PartyInfo);
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.CollaborationInfo _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1CollaborationInfo = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.CollaborationInfo();
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.AgreementRef _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1CollaborationInfoAgreementRef = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.AgreementRef();
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1CollaborationInfoAgreementRef.setValue("Value-1114507991");
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1CollaborationInfoAgreementRef.setType("Type-179891010");
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1CollaborationInfoAgreementRef.setPmode("Pmode-127836297");
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1CollaborationInfo.setAgreementRef(_sendMessageWithReference_ebMSHeaderInfoUserMessageVal1CollaborationInfoAgreementRef);
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Service _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1CollaborationInfoService = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Service();
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1CollaborationInfoService.setValue("Value392592184");
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1CollaborationInfoService.setType("Type167729450");
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1CollaborationInfo.setService(_sendMessageWithReference_ebMSHeaderInfoUserMessageVal1CollaborationInfoService);
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1CollaborationInfo.setAction("Action1903268952");
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1CollaborationInfo.setConversationId("ConversationId-1008548180");
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1.setCollaborationInfo(_sendMessageWithReference_ebMSHeaderInfoUserMessageVal1CollaborationInfo);
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.MessageProperties _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1MessageProperties = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.MessageProperties();
        java.util.List<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Property> _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1MessagePropertiesProperty = new java.util.ArrayList<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Property>();
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1MessageProperties.getProperty().addAll(_sendMessageWithReference_ebMSHeaderInfoUserMessageVal1MessagePropertiesProperty);
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1.setMessageProperties(_sendMessageWithReference_ebMSHeaderInfoUserMessageVal1MessageProperties);
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PayloadInfo _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1PayloadInfo = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PayloadInfo();
        java.util.List<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartInfo> _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1PayloadInfoPartInfo = new java.util.ArrayList<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartInfo>();
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1PayloadInfo.getPartInfo().addAll(_sendMessageWithReference_ebMSHeaderInfoUserMessageVal1PayloadInfoPartInfo);
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1.setPayloadInfo(_sendMessageWithReference_ebMSHeaderInfoUserMessageVal1PayloadInfo);
        _sendMessageWithReference_ebMSHeaderInfoUserMessageVal1.setMpc("Mpc-1912672681");
        _sendMessageWithReference_ebMSHeaderInfoUserMessage.add(_sendMessageWithReference_ebMSHeaderInfoUserMessageVal1);
        _sendMessageWithReference_ebMSHeaderInfo.getUserMessage().addAll(_sendMessageWithReference_ebMSHeaderInfoUserMessage);
        java.util.List<java.lang.Object> _sendMessageWithReference_ebMSHeaderInfoAny = new java.util.ArrayList<java.lang.Object>();
        java.lang.Object _sendMessageWithReference_ebMSHeaderInfoAnyVal1 = null;
        _sendMessageWithReference_ebMSHeaderInfoAny.add(_sendMessageWithReference_ebMSHeaderInfoAnyVal1);
        _sendMessageWithReference_ebMSHeaderInfo.getAny().addAll(_sendMessageWithReference_ebMSHeaderInfoAny);
        _sendMessageWithReference_ebMSHeaderInfo.setId("Id-898532476");
        _sendMessageWithReference_ebMSHeaderInfo.setMustUnderstand(Boolean.valueOf(false));
        try {
            port.sendMessageWithReference(_sendMessageWithReference_sendRequestURL, _sendMessageWithReference_ebMSHeaderInfo);

        } catch (SendMessageWithReferenceFault e) { 
            System.out.println("Expected exception: sendMessageWithReferenceFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking sendMessage...");
        backend.ecodex.org.SendRequest _sendMessage_sendRequest = new backend.ecodex.org.SendRequest();
        java.util.List<javax.activation.DataHandler> _sendMessage_sendRequestPayload = new java.util.ArrayList<javax.activation.DataHandler>();
        javax.activation.DataHandler _sendMessage_sendRequestPayloadVal1 = null;
        _sendMessage_sendRequestPayload.add(_sendMessage_sendRequestPayloadVal1);
        _sendMessage_sendRequest.getPayload().addAll(_sendMessage_sendRequestPayload);
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Messaging _sendMessage_ebMSHeaderInfo = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Messaging();
        java.util.List<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.SignalMessage> _sendMessage_ebMSHeaderInfoSignalMessage = new java.util.ArrayList<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.SignalMessage>();
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.SignalMessage _sendMessage_ebMSHeaderInfoSignalMessageVal1 = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.SignalMessage();
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.MessageInfo _sendMessage_ebMSHeaderInfoSignalMessageVal1MessageInfo = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.MessageInfo();
        _sendMessage_ebMSHeaderInfoSignalMessageVal1MessageInfo.setTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2012-08-08T10:04:35.335+02:00"));
        _sendMessage_ebMSHeaderInfoSignalMessageVal1MessageInfo.setMessageId("MessageId-2001610438");
        _sendMessage_ebMSHeaderInfoSignalMessageVal1MessageInfo.setRefToMessageId("RefToMessageId879128107");
        _sendMessage_ebMSHeaderInfoSignalMessageVal1.setMessageInfo(_sendMessage_ebMSHeaderInfoSignalMessageVal1MessageInfo);
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PullRequest _sendMessage_ebMSHeaderInfoSignalMessageVal1PullRequest = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PullRequest();
        java.util.List<java.lang.Object> _sendMessage_ebMSHeaderInfoSignalMessageVal1PullRequestAny = new java.util.ArrayList<java.lang.Object>();
        _sendMessage_ebMSHeaderInfoSignalMessageVal1PullRequest.getAny().addAll(_sendMessage_ebMSHeaderInfoSignalMessageVal1PullRequestAny);
        _sendMessage_ebMSHeaderInfoSignalMessageVal1PullRequest.setMpc("Mpc1496724035");
        _sendMessage_ebMSHeaderInfoSignalMessageVal1.setPullRequest(_sendMessage_ebMSHeaderInfoSignalMessageVal1PullRequest);
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Receipt _sendMessage_ebMSHeaderInfoSignalMessageVal1Receipt = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Receipt();
        java.util.List<java.lang.Object> _sendMessage_ebMSHeaderInfoSignalMessageVal1ReceiptAny = new java.util.ArrayList<java.lang.Object>();
        _sendMessage_ebMSHeaderInfoSignalMessageVal1Receipt.getAny().addAll(_sendMessage_ebMSHeaderInfoSignalMessageVal1ReceiptAny);
        _sendMessage_ebMSHeaderInfoSignalMessageVal1.setReceipt(_sendMessage_ebMSHeaderInfoSignalMessageVal1Receipt);
        java.util.List<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Error> _sendMessage_ebMSHeaderInfoSignalMessageVal1Error = new java.util.ArrayList<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Error>();
        _sendMessage_ebMSHeaderInfoSignalMessageVal1.getError().addAll(_sendMessage_ebMSHeaderInfoSignalMessageVal1Error);
        java.util.List<java.lang.Object> _sendMessage_ebMSHeaderInfoSignalMessageVal1Any = new java.util.ArrayList<java.lang.Object>();
        _sendMessage_ebMSHeaderInfoSignalMessageVal1.getAny().addAll(_sendMessage_ebMSHeaderInfoSignalMessageVal1Any);
        _sendMessage_ebMSHeaderInfoSignalMessage.add(_sendMessage_ebMSHeaderInfoSignalMessageVal1);
        _sendMessage_ebMSHeaderInfo.getSignalMessage().addAll(_sendMessage_ebMSHeaderInfoSignalMessage);
        java.util.List<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.UserMessage> _sendMessage_ebMSHeaderInfoUserMessage = new java.util.ArrayList<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.UserMessage>();
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.UserMessage _sendMessage_ebMSHeaderInfoUserMessageVal1 = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.UserMessage();
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.MessageInfo _sendMessage_ebMSHeaderInfoUserMessageVal1MessageInfo = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.MessageInfo();
        _sendMessage_ebMSHeaderInfoUserMessageVal1MessageInfo.setTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2012-08-08T10:04:35.335+02:00"));
        _sendMessage_ebMSHeaderInfoUserMessageVal1MessageInfo.setMessageId("MessageId-567329787");
        _sendMessage_ebMSHeaderInfoUserMessageVal1MessageInfo.setRefToMessageId("RefToMessageId1455507455");
        _sendMessage_ebMSHeaderInfoUserMessageVal1.setMessageInfo(_sendMessage_ebMSHeaderInfoUserMessageVal1MessageInfo);
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartyInfo _sendMessage_ebMSHeaderInfoUserMessageVal1PartyInfo = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartyInfo();
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.From _sendMessage_ebMSHeaderInfoUserMessageVal1PartyInfoFrom = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.From();
        java.util.List<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartyId> _sendMessage_ebMSHeaderInfoUserMessageVal1PartyInfoFromPartyId = new java.util.ArrayList<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartyId>();
        _sendMessage_ebMSHeaderInfoUserMessageVal1PartyInfoFrom.getPartyId().addAll(_sendMessage_ebMSHeaderInfoUserMessageVal1PartyInfoFromPartyId);
        _sendMessage_ebMSHeaderInfoUserMessageVal1PartyInfoFrom.setRole("Role-870329338");
        _sendMessage_ebMSHeaderInfoUserMessageVal1PartyInfo.setFrom(_sendMessage_ebMSHeaderInfoUserMessageVal1PartyInfoFrom);
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.To _sendMessage_ebMSHeaderInfoUserMessageVal1PartyInfoTo = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.To();
        java.util.List<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartyId> _sendMessage_ebMSHeaderInfoUserMessageVal1PartyInfoToPartyId = new java.util.ArrayList<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartyId>();
        _sendMessage_ebMSHeaderInfoUserMessageVal1PartyInfoTo.getPartyId().addAll(_sendMessage_ebMSHeaderInfoUserMessageVal1PartyInfoToPartyId);
        _sendMessage_ebMSHeaderInfoUserMessageVal1PartyInfoTo.setRole("Role-1824115888");
        _sendMessage_ebMSHeaderInfoUserMessageVal1PartyInfo.setTo(_sendMessage_ebMSHeaderInfoUserMessageVal1PartyInfoTo);
        _sendMessage_ebMSHeaderInfoUserMessageVal1.setPartyInfo(_sendMessage_ebMSHeaderInfoUserMessageVal1PartyInfo);
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.CollaborationInfo _sendMessage_ebMSHeaderInfoUserMessageVal1CollaborationInfo = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.CollaborationInfo();
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.AgreementRef _sendMessage_ebMSHeaderInfoUserMessageVal1CollaborationInfoAgreementRef = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.AgreementRef();
        _sendMessage_ebMSHeaderInfoUserMessageVal1CollaborationInfoAgreementRef.setValue("Value-324909311");
        _sendMessage_ebMSHeaderInfoUserMessageVal1CollaborationInfoAgreementRef.setType("Type602954066");
        _sendMessage_ebMSHeaderInfoUserMessageVal1CollaborationInfoAgreementRef.setPmode("Pmode-1696042041");
        _sendMessage_ebMSHeaderInfoUserMessageVal1CollaborationInfo.setAgreementRef(_sendMessage_ebMSHeaderInfoUserMessageVal1CollaborationInfoAgreementRef);
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Service _sendMessage_ebMSHeaderInfoUserMessageVal1CollaborationInfoService = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Service();
        _sendMessage_ebMSHeaderInfoUserMessageVal1CollaborationInfoService.setValue("Value-464369094");
        _sendMessage_ebMSHeaderInfoUserMessageVal1CollaborationInfoService.setType("Type1082853662");
        _sendMessage_ebMSHeaderInfoUserMessageVal1CollaborationInfo.setService(_sendMessage_ebMSHeaderInfoUserMessageVal1CollaborationInfoService);
        _sendMessage_ebMSHeaderInfoUserMessageVal1CollaborationInfo.setAction("Action990879338");
        _sendMessage_ebMSHeaderInfoUserMessageVal1CollaborationInfo.setConversationId("ConversationId-622776465");
        _sendMessage_ebMSHeaderInfoUserMessageVal1.setCollaborationInfo(_sendMessage_ebMSHeaderInfoUserMessageVal1CollaborationInfo);
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.MessageProperties _sendMessage_ebMSHeaderInfoUserMessageVal1MessageProperties = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.MessageProperties();
        java.util.List<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Property> _sendMessage_ebMSHeaderInfoUserMessageVal1MessagePropertiesProperty = new java.util.ArrayList<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Property>();
        _sendMessage_ebMSHeaderInfoUserMessageVal1MessageProperties.getProperty().addAll(_sendMessage_ebMSHeaderInfoUserMessageVal1MessagePropertiesProperty);
        _sendMessage_ebMSHeaderInfoUserMessageVal1.setMessageProperties(_sendMessage_ebMSHeaderInfoUserMessageVal1MessageProperties);
        org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PayloadInfo _sendMessage_ebMSHeaderInfoUserMessageVal1PayloadInfo = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PayloadInfo();
        java.util.List<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartInfo> _sendMessage_ebMSHeaderInfoUserMessageVal1PayloadInfoPartInfo = new java.util.ArrayList<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartInfo>();
        _sendMessage_ebMSHeaderInfoUserMessageVal1PayloadInfo.getPartInfo().addAll(_sendMessage_ebMSHeaderInfoUserMessageVal1PayloadInfoPartInfo);
        _sendMessage_ebMSHeaderInfoUserMessageVal1.setPayloadInfo(_sendMessage_ebMSHeaderInfoUserMessageVal1PayloadInfo);
        _sendMessage_ebMSHeaderInfoUserMessageVal1.setMpc("Mpc1413981752");
        _sendMessage_ebMSHeaderInfoUserMessage.add(_sendMessage_ebMSHeaderInfoUserMessageVal1);
        _sendMessage_ebMSHeaderInfo.getUserMessage().addAll(_sendMessage_ebMSHeaderInfoUserMessage);
        java.util.List<java.lang.Object> _sendMessage_ebMSHeaderInfoAny = new java.util.ArrayList<java.lang.Object>();
        java.lang.Object _sendMessage_ebMSHeaderInfoAnyVal1 = null;
        _sendMessage_ebMSHeaderInfoAny.add(_sendMessage_ebMSHeaderInfoAnyVal1);
        _sendMessage_ebMSHeaderInfo.getAny().addAll(_sendMessage_ebMSHeaderInfoAny);
        _sendMessage_ebMSHeaderInfo.setId("Id-1568556447");
        _sendMessage_ebMSHeaderInfo.setMustUnderstand(Boolean.valueOf(false));
        try {
            port.sendMessage(_sendMessage_sendRequest, _sendMessage_ebMSHeaderInfo);

        } catch (SendMessageFault e) { 
            System.out.println("Expected exception: sendMessageFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking listPendingMessages...");
        java.lang.Object _listPendingMessages_listPendingMessagesRequest = null;
        try {
            backend.ecodex.org.ListPendingMessagesResponse _listPendingMessages__return = port.listPendingMessages(_listPendingMessages_listPendingMessagesRequest);
            System.out.println("listPendingMessages.result=" + _listPendingMessages__return);

        } catch (ListPendingMessagesFault e) { 
            System.out.println("Expected exception: listPendingMessagesFault has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
