
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package backend.ecodex.org;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-08T10:04:35.398+02:00
 * Generated source version: 2.6.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "BackendService",
                      portName = "BackendPort",
                      targetNamespace = "http://org.ecodex.backend",
                      wsdlLocation = "http://www.ecodex.org/eCODEX?wsdl",
                      endpointInterface = "backend.ecodex.org.BackendInterface")
                      
public class BackendInterfaceImpl implements BackendInterface {

    private static final Logger LOG = Logger.getLogger(BackendInterfaceImpl.class.getName());

    /* (non-Javadoc)
     * @see backend.ecodex.org.BackendInterface#downloadMessage(backend.ecodex.org.DownloadMessageRequest  downloadMessageRequest ,)backend.ecodex.org.DownloadMessageResponse  downloadMessageResponse ,)org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Messaging  ebMSHeaderInfo )*
     */
    public void downloadMessage(DownloadMessageRequest downloadMessageRequest,javax.xml.ws.Holder<DownloadMessageResponse> downloadMessageResponse,javax.xml.ws.Holder<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Messaging> ebMSHeaderInfo) throws DownloadMessageFault    { 
        LOG.info("Executing operation downloadMessage");
        System.out.println(downloadMessageRequest);
        try {
            backend.ecodex.org.DownloadMessageResponse downloadMessageResponseValue = new backend.ecodex.org.DownloadMessageResponse();
            java.util.List<javax.activation.DataHandler> downloadMessageResponseValuePayload = new java.util.ArrayList<javax.activation.DataHandler>();
            javax.activation.DataHandler downloadMessageResponseValuePayloadVal1 = null;
            downloadMessageResponseValuePayload.add(downloadMessageResponseValuePayloadVal1);
            downloadMessageResponseValue.getPayload().addAll(downloadMessageResponseValuePayload);
            downloadMessageResponse.value = downloadMessageResponseValue;
            org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Messaging ebMSHeaderInfoValue = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Messaging();
            java.util.List<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.SignalMessage> ebMSHeaderInfoValueSignalMessage = new java.util.ArrayList<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.SignalMessage>();
            org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.SignalMessage ebMSHeaderInfoValueSignalMessageVal1 = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.SignalMessage();
            org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.MessageInfo ebMSHeaderInfoValueSignalMessageVal1MessageInfo = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.MessageInfo();
            ebMSHeaderInfoValueSignalMessageVal1MessageInfo.setTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2012-08-08T10:04:35.398+02:00"));
            ebMSHeaderInfoValueSignalMessageVal1MessageInfo.setMessageId("MessageId-1795379212");
            ebMSHeaderInfoValueSignalMessageVal1MessageInfo.setRefToMessageId("RefToMessageId-893614994");
            ebMSHeaderInfoValueSignalMessageVal1.setMessageInfo(ebMSHeaderInfoValueSignalMessageVal1MessageInfo);
            org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PullRequest ebMSHeaderInfoValueSignalMessageVal1PullRequest = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PullRequest();
            java.util.List<java.lang.Object> ebMSHeaderInfoValueSignalMessageVal1PullRequestAny = new java.util.ArrayList<java.lang.Object>();
            ebMSHeaderInfoValueSignalMessageVal1PullRequest.getAny().addAll(ebMSHeaderInfoValueSignalMessageVal1PullRequestAny);
            ebMSHeaderInfoValueSignalMessageVal1PullRequest.setMpc("Mpc-303644187");
            ebMSHeaderInfoValueSignalMessageVal1.setPullRequest(ebMSHeaderInfoValueSignalMessageVal1PullRequest);
            org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Receipt ebMSHeaderInfoValueSignalMessageVal1Receipt = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Receipt();
            java.util.List<java.lang.Object> ebMSHeaderInfoValueSignalMessageVal1ReceiptAny = new java.util.ArrayList<java.lang.Object>();
            ebMSHeaderInfoValueSignalMessageVal1Receipt.getAny().addAll(ebMSHeaderInfoValueSignalMessageVal1ReceiptAny);
            ebMSHeaderInfoValueSignalMessageVal1.setReceipt(ebMSHeaderInfoValueSignalMessageVal1Receipt);
            java.util.List<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Error> ebMSHeaderInfoValueSignalMessageVal1Error = new java.util.ArrayList<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Error>();
            ebMSHeaderInfoValueSignalMessageVal1.getError().addAll(ebMSHeaderInfoValueSignalMessageVal1Error);
            java.util.List<java.lang.Object> ebMSHeaderInfoValueSignalMessageVal1Any = new java.util.ArrayList<java.lang.Object>();
            ebMSHeaderInfoValueSignalMessageVal1.getAny().addAll(ebMSHeaderInfoValueSignalMessageVal1Any);
            ebMSHeaderInfoValueSignalMessage.add(ebMSHeaderInfoValueSignalMessageVal1);
            ebMSHeaderInfoValue.getSignalMessage().addAll(ebMSHeaderInfoValueSignalMessage);
            java.util.List<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.UserMessage> ebMSHeaderInfoValueUserMessage = new java.util.ArrayList<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.UserMessage>();
            org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.UserMessage ebMSHeaderInfoValueUserMessageVal1 = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.UserMessage();
            org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.MessageInfo ebMSHeaderInfoValueUserMessageVal1MessageInfo = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.MessageInfo();
            ebMSHeaderInfoValueUserMessageVal1MessageInfo.setTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2012-08-08T10:04:35.398+02:00"));
            ebMSHeaderInfoValueUserMessageVal1MessageInfo.setMessageId("MessageId-1847540943");
            ebMSHeaderInfoValueUserMessageVal1MessageInfo.setRefToMessageId("RefToMessageId1507317589");
            ebMSHeaderInfoValueUserMessageVal1.setMessageInfo(ebMSHeaderInfoValueUserMessageVal1MessageInfo);
            org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartyInfo ebMSHeaderInfoValueUserMessageVal1PartyInfo = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartyInfo();
            org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.From ebMSHeaderInfoValueUserMessageVal1PartyInfoFrom = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.From();
            java.util.List<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartyId> ebMSHeaderInfoValueUserMessageVal1PartyInfoFromPartyId = new java.util.ArrayList<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartyId>();
            ebMSHeaderInfoValueUserMessageVal1PartyInfoFrom.getPartyId().addAll(ebMSHeaderInfoValueUserMessageVal1PartyInfoFromPartyId);
            ebMSHeaderInfoValueUserMessageVal1PartyInfoFrom.setRole("Role-1140409745");
            ebMSHeaderInfoValueUserMessageVal1PartyInfo.setFrom(ebMSHeaderInfoValueUserMessageVal1PartyInfoFrom);
            org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.To ebMSHeaderInfoValueUserMessageVal1PartyInfoTo = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.To();
            java.util.List<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartyId> ebMSHeaderInfoValueUserMessageVal1PartyInfoToPartyId = new java.util.ArrayList<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartyId>();
            ebMSHeaderInfoValueUserMessageVal1PartyInfoTo.getPartyId().addAll(ebMSHeaderInfoValueUserMessageVal1PartyInfoToPartyId);
            ebMSHeaderInfoValueUserMessageVal1PartyInfoTo.setRole("Role765347857");
            ebMSHeaderInfoValueUserMessageVal1PartyInfo.setTo(ebMSHeaderInfoValueUserMessageVal1PartyInfoTo);
            ebMSHeaderInfoValueUserMessageVal1.setPartyInfo(ebMSHeaderInfoValueUserMessageVal1PartyInfo);
            org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.CollaborationInfo ebMSHeaderInfoValueUserMessageVal1CollaborationInfo = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.CollaborationInfo();
            org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.AgreementRef ebMSHeaderInfoValueUserMessageVal1CollaborationInfoAgreementRef = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.AgreementRef();
            ebMSHeaderInfoValueUserMessageVal1CollaborationInfoAgreementRef.setValue("Value1196192681");
            ebMSHeaderInfoValueUserMessageVal1CollaborationInfoAgreementRef.setType("Type-1042366482");
            ebMSHeaderInfoValueUserMessageVal1CollaborationInfoAgreementRef.setPmode("Pmode802284802");
            ebMSHeaderInfoValueUserMessageVal1CollaborationInfo.setAgreementRef(ebMSHeaderInfoValueUserMessageVal1CollaborationInfoAgreementRef);
            org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Service ebMSHeaderInfoValueUserMessageVal1CollaborationInfoService = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Service();
            ebMSHeaderInfoValueUserMessageVal1CollaborationInfoService.setValue("Value1823881229");
            ebMSHeaderInfoValueUserMessageVal1CollaborationInfoService.setType("Type-1104099330");
            ebMSHeaderInfoValueUserMessageVal1CollaborationInfo.setService(ebMSHeaderInfoValueUserMessageVal1CollaborationInfoService);
            ebMSHeaderInfoValueUserMessageVal1CollaborationInfo.setAction("Action-1728979699");
            ebMSHeaderInfoValueUserMessageVal1CollaborationInfo.setConversationId("ConversationId304299817");
            ebMSHeaderInfoValueUserMessageVal1.setCollaborationInfo(ebMSHeaderInfoValueUserMessageVal1CollaborationInfo);
            org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.MessageProperties ebMSHeaderInfoValueUserMessageVal1MessageProperties = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.MessageProperties();
            java.util.List<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Property> ebMSHeaderInfoValueUserMessageVal1MessagePropertiesProperty = new java.util.ArrayList<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Property>();
            ebMSHeaderInfoValueUserMessageVal1MessageProperties.getProperty().addAll(ebMSHeaderInfoValueUserMessageVal1MessagePropertiesProperty);
            ebMSHeaderInfoValueUserMessageVal1.setMessageProperties(ebMSHeaderInfoValueUserMessageVal1MessageProperties);
            org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PayloadInfo ebMSHeaderInfoValueUserMessageVal1PayloadInfo = new org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PayloadInfo();
            java.util.List<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartInfo> ebMSHeaderInfoValueUserMessageVal1PayloadInfoPartInfo = new java.util.ArrayList<org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.PartInfo>();
            ebMSHeaderInfoValueUserMessageVal1PayloadInfo.getPartInfo().addAll(ebMSHeaderInfoValueUserMessageVal1PayloadInfoPartInfo);
            ebMSHeaderInfoValueUserMessageVal1.setPayloadInfo(ebMSHeaderInfoValueUserMessageVal1PayloadInfo);
            ebMSHeaderInfoValueUserMessageVal1.setMpc("Mpc1474716785");
            ebMSHeaderInfoValueUserMessage.add(ebMSHeaderInfoValueUserMessageVal1);
            ebMSHeaderInfoValue.getUserMessage().addAll(ebMSHeaderInfoValueUserMessage);
            java.util.List<java.lang.Object> ebMSHeaderInfoValueAny = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object ebMSHeaderInfoValueAnyVal1 = null;
            ebMSHeaderInfoValueAny.add(ebMSHeaderInfoValueAnyVal1);
            ebMSHeaderInfoValue.getAny().addAll(ebMSHeaderInfoValueAny);
            ebMSHeaderInfoValue.setId("Id-1680706727");
            ebMSHeaderInfoValue.setMustUnderstand(Boolean.valueOf(false));
            ebMSHeaderInfo.value = ebMSHeaderInfoValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DownloadMessageFault("downloadMessageFault...");
    }

    /* (non-Javadoc)
     * @see backend.ecodex.org.BackendInterface#sendMessageWithReference(backend.ecodex.org.SendRequestURL  sendRequestURL ,)org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Messaging  ebMSHeaderInfo )*
     */
    public void sendMessageWithReference(SendRequestURL sendRequestURL,org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Messaging ebMSHeaderInfo) throws SendMessageWithReferenceFault    { 
        LOG.info("Executing operation sendMessageWithReference");
        System.out.println(sendRequestURL);
        System.out.println(ebMSHeaderInfo);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SendMessageWithReferenceFault("sendMessageWithReferenceFault...");
    }

    /* (non-Javadoc)
     * @see backend.ecodex.org.BackendInterface#sendMessage(backend.ecodex.org.SendRequest  sendRequest ,)org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Messaging  ebMSHeaderInfo )*
     */
    public void sendMessage(SendRequest sendRequest,org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704.Messaging ebMSHeaderInfo) throws SendMessageFault    { 
        LOG.info("Executing operation sendMessage");
        System.out.println(sendRequest);
        System.out.println(ebMSHeaderInfo);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SendMessageFault("sendMessageFault...");
    }

    /* (non-Javadoc)
     * @see backend.ecodex.org.BackendInterface#listPendingMessages(java.lang.Object  listPendingMessagesRequest )*
     */
    public backend.ecodex.org.ListPendingMessagesResponse listPendingMessages(java.lang.Object listPendingMessagesRequest) throws ListPendingMessagesFault    { 
        LOG.info("Executing operation listPendingMessages");
        System.out.println(listPendingMessagesRequest);
        try {
            backend.ecodex.org.ListPendingMessagesResponse _return = new backend.ecodex.org.ListPendingMessagesResponse();
            java.util.List<java.lang.String> _returnMessageID = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnMessageIDVal1 = "_returnMessageIDVal-770349730";
            _returnMessageID.add(_returnMessageIDVal1);
            _return.getMessageID().addAll(_returnMessageID);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ListPendingMessagesFault("listPendingMessagesFault...");
    }

}
