package backend.ecodex.org;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.1 2013-01-15T08:40:49.490+01:00
 * Generated source version: 2.6.1
 * 
 */

public class BackendInterface_BackendPort_Server {

    protected BackendInterface_BackendPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new BackendService();
        String address = "http://www.ecodex.org/eCODEX";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new BackendInterface_BackendPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
