package eu.domibus.connector.domain.enums;

import org.apache.logging.log4j.message.Message;

import java.util.stream.Stream;

import static eu.domibus.connector.domain.enums.MessageTargetSource.*;

public enum DomibusConnectorMessageDirection {
    /**
     * used to mark a transport which is received by the backend
     * and transported to the gateway
     */
    BACKEND_TO_GATEWAY(BACKEND, GATEWAY),
    /**
     * used to mark a transport which is received by the gateway
     * and transported to the backend
     */
    GATEWAY_TO_BACKEND(GATEWAY, BACKEND),
    /**
     * used to mark a transport which is generated by the connector
     * (usually confirmation messages, like relayREMMDRejection, deliveryRejection
     * and transported to the gateway
     */
    CONNECTOR_TO_GATEWAY(CONNECTOR, GATEWAY),
    /**
     * used to mark a transport which is generated by the connector
     * (usually confirmation messages, like SUBMISSION_ACCEPTANCE, SUBMISSION_REJECTION
     * and transported back to the gateway
     */
    CONNECTOR_TO_BACKEND(CONNECTOR, BACKEND);

    private DomibusConnectorMessageDirection(MessageTargetSource source, MessageTargetSource target) {
        this.source = source;
        this.target = target;
    }

    private MessageTargetSource source;
    private MessageTargetSource target;

    public static DomibusConnectorMessageDirection fromMessageTargetSource(MessageTargetSource directionSource, MessageTargetSource directionTarget) {
        if (directionSource == null) {
            throw new IllegalArgumentException("Direction Source is not allowed to be null!");
        }
        if (directionTarget == null) {
            throw new IllegalArgumentException("Direction target is not allowed to be null!");
        }
        return Stream.of(DomibusConnectorMessageDirection.values())
                .filter(d -> d.getSource() == directionSource && d.getTarget() == directionTarget)
                .findFirst()
                .get();
    }

    public MessageTargetSource getSource() {
        return source;
    }

    public MessageTargetSource getTarget() {
        return target;
    }
}

