package eu.domibus.connector.security.aes;

import eu.ecodex.dc5.message.model.DomibusConnectorMessage;
import eu.domibus.connector.security.configuration.DCBusinessDocumentValidationConfigurationProperties;
import eu.ecodex.dss.service.ECodexTechnicalValidationService;

public interface DCAuthenticationBasedTechnicalValidationServiceFactory {

    ECodexTechnicalValidationService createTechnicalValidationService(DomibusConnectorMessage message, DCBusinessDocumentValidationConfigurationProperties.AuthenticationValidationConfigurationProperties config);

}
