package eu.domibus.connector.ws.gateway.submission.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-03-01T09:43:04.608+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://connector.domibus.eu/ws/gateway/submission/webservice", name = "DomibusConnectorGatewaySubmissionWebService")
@XmlSeeAlso({eu.domibus.connector.domain.transition.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DomibusConnectorGatewaySubmissionWebService {

    @WebMethod
    @WebResult(name = "submitMessageResponse", targetNamespace = "", partName = "submitMessageResponse")
    public eu.domibus.connector.domain.transition.DomibsConnectorAcknowledgementType submitMessage(
        @WebParam(partName = "submitMessageRequest", name = "submitMessageRequest", targetNamespace = "")
        eu.domibus.connector.domain.transition.DomibusConnectorMessageType submitMessageRequest
    );
}
