-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: db/changelog/install/initial-4.0.xml
-- Ran at: 11.04.18 14:43
-- Against: CONNECTORNEW@jdbc:oracle:thin:connectornew//@localhost:1521/xe
-- Liquibase version: 3.5.3
-- *********************************************************************

SET DEFINE OFF;

-- Create Database Lock Table
CREATE TABLE DATABASECHANGELOGLOCK (ID INTEGER NOT NULL, LOCKED NUMBER(1) NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR2(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID));

-- Initialize Database Lock Table
DELETE FROM DATABASECHANGELOGLOCK;

INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, 0);

-- Lock Database
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = 'PC65589 (172.31.33.137)', LOCKGRANTED = to_timestamp('2018-04-11 14:43:31.458', 'YYYY-MM-DD HH24:MI:SS.FF') WHERE ID = 1 AND LOCKED = 0;

-- Create Database Change Log Table
CREATE TABLE DATABASECHANGELOG (ID VARCHAR2(255) NOT NULL, AUTHOR VARCHAR2(255) NOT NULL, FILENAME VARCHAR2(255) NOT NULL, DATEEXECUTED TIMESTAMP NOT NULL, ORDEREXECUTED INTEGER NOT NULL, EXECTYPE VARCHAR2(10) NOT NULL, MD5SUM VARCHAR2(35), DESCRIPTION VARCHAR2(255), COMMENTS VARCHAR2(255), TAG VARCHAR2(255), LIQUIBASE VARCHAR2(20), CONTEXTS VARCHAR2(255), LABELS VARCHAR2(255), DEPLOYMENT_ID VARCHAR2(10));

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_1::StephanSpindler
CREATE TABLE DOMIBUS_CONNECTOR_SEQ_STORE (SEQ_NAME VARCHAR2(255 CHAR) NOT NULL, SEQ_VALUE NUMBER(10) NOT NULL);

ALTER TABLE DOMIBUS_CONNECTOR_SEQ_STORE ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_SEQ_STORE PRIMARY KEY (SEQ_NAME);

CREATE INDEX PK_DOMIBUS_CONNECTOR_SEQ_STORE ON DOMIBUS_CONNECTOR_SEQ_STORE(SEQ_NAME);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_1', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 1, '7:2e584da7a6e6b724143dcb8123094e0a', 'createTable tableName=DOMIBUS_CONNECTOR_SEQ_STORE; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_SEQ_STORE, tableName=DOMIBUS_CONNECTOR_SEQ_STORE; createIndex indexName=INDEX_PK_DOMIBUS_CONNECTOR_SEQ_STORE, tableName=DOMIBUS_CONNECTOR_SEQ_STORE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_2::StephanSpindler
CREATE TABLE DOMIBUS_CONNECTOR_SERVICE (SERVICE VARCHAR2(255 CHAR) NOT NULL, SERVICE_TYPE VARCHAR2(255 CHAR) NOT NULL);

ALTER TABLE DOMIBUS_CONNECTOR_SERVICE ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_SERVICE PRIMARY KEY (SERVICE);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_2', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 2, '7:2f2a0bba064baf129f6f439bae4926fc', 'createTable tableName=DOMIBUS_CONNECTOR_SERVICE; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_SERVICE, tableName=DOMIBUS_CONNECTOR_SERVICE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_3::StephanSpindler
CREATE TABLE DOMIBUS_CONNECTOR_PARTY (PARTY_ID VARCHAR2(255 CHAR) NOT NULL, ROLE VARCHAR2(255 CHAR) NOT NULL, PARTY_ID_TYPE VARCHAR2(512 CHAR));

ALTER TABLE DOMIBUS_CONNECTOR_PARTY ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_PARTY PRIMARY KEY (PARTY_ID, ROLE);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_3', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 3, '7:432aeac4fdb7028dc546c43559ccfed2', 'createTable tableName=DOMIBUS_CONNECTOR_PARTY; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_PARTY, tableName=DOMIBUS_CONNECTOR_PARTY', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_4::StephanSpindler
CREATE TABLE DOMIBUS_CONNECTOR_MSG_ERROR (ID DECIMAL(10, 0) NOT NULL, MESSAGE_ID DECIMAL(10, 0) NOT NULL, ERROR_MESSAGE VARCHAR2(512 CHAR) NOT NULL, DETAILED_TEXT CLOB, ERROR_SOURCE CLOB, CREATED TIMESTAMP NOT NULL);

ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_MSG_ERROR PRIMARY KEY (ID);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_4', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 4, '7:3a47c2c867483093d1730efd10403d73', 'createTable tableName=DOMIBUS_CONNECTOR_MSG_ERROR; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_MSG_ERROR, tableName=DOMIBUS_CONNECTOR_MSG_ERROR', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_5::StephanSpindler
CREATE TABLE DOMIBUS_CONNECTOR_MSG_CONT (ID DECIMAL(10, 0) NOT NULL, MESSAGE_ID DECIMAL(10, 0), CONTENT_TYPE VARCHAR2(255 CHAR), CONTENT BLOB, CHECKSUM CLOB, CREATED TIMESTAMP);

ALTER TABLE DOMIBUS_CONNECTOR_MSG_CONT ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_MSG__01 PRIMARY KEY (ID);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_5', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 5, '7:fbd73c7e0100efc910f7254fa4d0e345', 'createTable tableName=DOMIBUS_CONNECTOR_MSG_CONT; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_MSG__01, tableName=DOMIBUS_CONNECTOR_MSG_CONT', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_6::StephanSpindler
CREATE TABLE DOMIBUS_CONNECTOR_BIGDATA (ID VARCHAR2(255 CHAR) NOT NULL, CHECKSUM CLOB, CREATED TIMESTAMP, MESSAGE_ID DECIMAL(10, 0), LAST_ACCESS TIMESTAMP, NAME CLOB, CONTENT BLOB, MIMETYPE VARCHAR2(255 CHAR));

ALTER TABLE DOMIBUS_CONNECTOR_BIGDATA ADD PRIMARY KEY (ID);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_6', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 6, '7:61c3dafb68215f822deb0500336ffc6b', 'createTable tableName=DOMIBUS_CONNECTOR_BIGDATA; addPrimaryKey tableName=DOMIBUS_CONNECTOR_BIGDATA', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_7::StephanSpindler
CREATE TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO (ID DECIMAL(10, 0) NOT NULL, MESSAGE_ID DECIMAL(10, 0) NOT NULL, CONNECTOR_MESSAGE_ID VARCHAR2(255 CHAR), FROM_PARTY_ID VARCHAR2(255 CHAR), FROM_PARTY_ROLE VARCHAR2(255 CHAR), TO_PARTY_ID VARCHAR2(255 CHAR), TO_PARTY_ROLE VARCHAR2(255 CHAR), ORIGINAL_SENDER VARCHAR2(255 CHAR), FINAL_RECIPIENT VARCHAR2(255 CHAR), SERVICE VARCHAR2(255 CHAR), ACTION VARCHAR2(255 CHAR), CREATED TIMESTAMP, UPDATED TIMESTAMP);

ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT PK_CONNECTOR_MESSAGE_INFO PRIMARY KEY (ID);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_7', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 7, '7:3ed5d0a9914002501c4a94294018f49b', 'createTable tableName=DOMIBUS_CONNECTOR_MESSAGE_INFO; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_MESSAGE_INFO, tableName=DOMIBUS_CONNECTOR_MESSAGE_INFO', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_8::StephanSpindler
CREATE TABLE DOMIBUS_CONNECTOR_MESSAGE (ID DECIMAL(10, 0) NOT NULL, EBMS_MESSAGE_ID VARCHAR2(255 CHAR), BACKEND_MESSAGE_ID VARCHAR2(255 CHAR), BACKEND_NAME VARCHAR2(255 CHAR), CONNECTOR_MESSAGE_ID VARCHAR2(255 CHAR), CONVERSATION_ID VARCHAR2(255 CHAR), DIRECTION VARCHAR2(10), HASH_VALUE CLOB, CONFIRMED TIMESTAMP, REJECTED TIMESTAMP, DELIVERED_BACKEND TIMESTAMP, DELIVERED_GW TIMESTAMP, UPDATED TIMESTAMP, CREATED TIMESTAMP);

ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_MESSAGE PRIMARY KEY (ID);

ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE ADD CONSTRAINT UNIQUE_CONNECTOR_MESSAGE_ID UNIQUE (CONNECTOR_MESSAGE_ID);

ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE ADD CONSTRAINT UQ_DOMIBUS_CONNE_EBMS_MESSAGE UNIQUE (EBMS_MESSAGE_ID);

ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE ADD CONSTRAINT UQ_DOMIBUS_CONNE_NAT_MESSAGE_ UNIQUE (BACKEND_MESSAGE_ID);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_8', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 8, '7:9d2c70447b5541a8c50d755d73c56305', 'createTable tableName=DOMIBUS_CONNECTOR_MESSAGE; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_MESSAGE, tableName=DOMIBUS_CONNECTOR_MESSAGE; addUniqueConstraint constraintName=UNIQUE_CONNECTOR_MESSAGE_ID, tableName=DOMIBUS_CONNECTOR_MESSAGE; a...', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_9::StephanSpindler
CREATE TABLE DOMIBUS_CONNECTOR_EVIDENCE (ID DECIMAL(10, 0) NOT NULL, MESSAGE_ID DECIMAL(10, 0) NOT NULL, TYPE VARCHAR2(255 CHAR), EVIDENCE CLOB, DELIVERED_NAT TIMESTAMP, DELIVERED_GW TIMESTAMP, UPDATED TIMESTAMP);

ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_EVIDENCE PRIMARY KEY (ID);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_9', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 9, '7:3a5add3e93854cc4b53973d44f4a3d41', 'createTable tableName=DOMIBUS_CONNECTOR_EVIDENCE; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_EVIDENCE, tableName=DOMIBUS_CONNECTOR_EVIDENCE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_10::StephanSpindler
CREATE TABLE DOMIBUS_CONNECTOR_CONT_TYPE (MESSAGE_CONTENT_TYPE VARCHAR2(255 CHAR) NOT NULL);

ALTER TABLE DOMIBUS_CONNECTOR_CONT_TYPE ADD CONSTRAINT PK_DOMIBUS_CONN_02 PRIMARY KEY (MESSAGE_CONTENT_TYPE);

CREATE TABLE DOMIBUS_CONNECTOR_ACTION (ACTION VARCHAR2(255 CHAR) NOT NULL, PDF_REQUIRED DECIMAL(1, 0) NOT NULL);

ALTER TABLE DOMIBUS_CONNECTOR_ACTION ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_ACTION PRIMARY KEY (ACTION);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_10', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 10, '7:505c55a53f80e4b0be9614c8aa550716', 'createTable tableName=DOMIBUS_CONNECTOR_CONT_TYPE; addPrimaryKey constraintName=PK_DOMIBUS_CONN_02, tableName=DOMIBUS_CONNECTOR_CONT_TYPE; createTable tableName=DOMIBUS_CONNECTOR_ACTION; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_ACTION, ta...', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_11::StephanSpindler
CREATE TABLE DOMIBUS_CONNECTOR_BACKEND_INFO (ID DECIMAL(10, 0) NOT NULL, BACKEND_NAME VARCHAR2(255 CHAR) NOT NULL, BACKEND_KEY_ALIAS VARCHAR2(255 CHAR) NOT NULL, BACKEND_KEY_PASS VARCHAR2(255 CHAR), BACKEND_SERVICE_TYPE VARCHAR2(255 CHAR), BACKEND_ENABLED NUMBER(1) DEFAULT 1, BACKEND_DEFAULT NUMBER(1) DEFAULT 0, BACKEND_DESCRIPTION CLOB, BACKEND_PUSH_ADDRESS CLOB);

ALTER TABLE DOMIBUS_CONNECTOR_BACKEND_INFO ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_BACK_01 PRIMARY KEY (ID);

ALTER TABLE DOMIBUS_CONNECTOR_BACKEND_INFO ADD CONSTRAINT UN_DOMIBUS_CONNECTOR_BACK_01 UNIQUE (BACKEND_NAME);

ALTER TABLE DOMIBUS_CONNECTOR_BACKEND_INFO ADD CONSTRAINT UN_DOMIBUS_CONNECTOR_BACK_02 UNIQUE (BACKEND_KEY_ALIAS);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_11', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 11, '7:c9dd1c142f0349be27dbb43d2f280e9e', 'createTable tableName=DOMIBUS_CONNECTOR_BACKEND_INFO; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_BACK_01, tableName=DOMIBUS_CONNECTOR_BACKEND_INFO; addUniqueConstraint constraintName=UN_DOMIBUS_CONNECTOR_BACK_01, tableName=DOMIBUS_CONNECTOR...', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_12::StephanSpindler
CREATE TABLE DOMIBUS_CONNECTOR_BACK_2_S (DOMIBUS_CONNECTOR_SERVICE_ID VARCHAR2(255 CHAR) NOT NULL, DOMIBUS_CONNECTOR_BACKEND_ID DECIMAL(10, 0) NOT NULL);

ALTER TABLE DOMIBUS_CONNECTOR_BACK_2_S ADD CONSTRAINT PK_DOMIBUS_CONN_01 PRIMARY KEY (DOMIBUS_CONNECTOR_SERVICE_ID, DOMIBUS_CONNECTOR_BACKEND_ID);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_12', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 12, '7:302920d7ab0ebc9bbc339e491527f06c', 'createTable tableName=DOMIBUS_CONNECTOR_BACK_2_S; addPrimaryKey constraintName=PK_DOMIBUS_CONN_01, tableName=DOMIBUS_CONNECTOR_BACK_2_S', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_13::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MSG_ERROR FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_13', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 13, '7:df71593e1116807cd89bc97b3b6269f9', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_MSG_ERROR, constraintName=FK_DOMIBUS_CONNECTOR_MSG_ERROR, referencedTableName=DOMIBUS_CONNECTOR_MESSAGE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_14::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_MSG_CONT ADD CONSTRAINT FK_DOMIBUS_CONN_DOMIBUS_CON_04 FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_14', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 14, '7:79940f7647fa5b32ba163f93ec7dc443', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_MSG_CONT, constraintName=FK_DOMIBUS_CONN_DOMIBUS_CON_04, referencedTableName=DOMIBUS_CONNECTOR_MESSAGE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_15::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_1 FOREIGN KEY (ACTION) REFERENCES DOMIBUS_CONNECTOR_ACTION (ACTION);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_15', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 15, '7:d4a1db943fc545fda77b01e06774383e', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_MESSAGE_INFO, constraintName=FK_DOMIBUS_CONNECTOR_MESSAGE_1, referencedTableName=DOMIBUS_CONNECTOR_ACTION', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_16::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_2 FOREIGN KEY (SERVICE) REFERENCES DOMIBUS_CONNECTOR_SERVICE (service);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_16', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 16, '7:65567928a17beed8178f4308c02a94cb', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_MESSAGE_INFO, constraintName=FK_DOMIBUS_CONNECTOR_MESSAGE_2, referencedTableName=DOMIBUS_CONNECTOR_SERVICE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_17::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_3 FOREIGN KEY (FROM_PARTY_ID, FROM_PARTY_ROLE) REFERENCES DOMIBUS_CONNECTOR_PARTY (PARTY_ID, ROLE);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_17', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 17, '7:64df2871727e11981a6f06cfdfc67123', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_MESSAGE_INFO, constraintName=FK_DOMIBUS_CONNECTOR_MESSAGE_3, referencedTableName=DOMIBUS_CONNECTOR_PARTY', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_18::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_4 FOREIGN KEY (TO_PARTY_ID, TO_PARTY_ROLE) REFERENCES DOMIBUS_CONNECTOR_PARTY (PARTY_ID, ROLE);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_18', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 18, '7:75eb3ba07f1a851f7e310f7614b668c5', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_MESSAGE_INFO, constraintName=FK_DOMIBUS_CONNECTOR_MESSAGE_4, referencedTableName=DOMIBUS_CONNECTOR_PARTY', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_19::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_I FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_19', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 19, '7:a1988a2bc083b550439d2309b34d7c4d', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_MESSAGE_INFO, constraintName=FK_DOMIBUS_CONNECTOR_MESSAGE_I, referencedTableName=DOMIBUS_CONNECTOR_MESSAGE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_20::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_EVIDENCES FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_20', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 20, '7:78539cc81c1e1b40db24b041e763ece6', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_EVIDENCE, constraintName=FK_DOMIBUS_CONNECTOR_EVIDENCES, referencedTableName=DOMIBUS_CONNECTOR_MESSAGE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_21::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_BACK_2_S ADD CONSTRAINT FK_DOMIBUS_CONN_DOMIBUS_CON_01 FOREIGN KEY (DOMIBUS_CONNECTOR_BACKEND_ID) REFERENCES DOMIBUS_CONNECTOR_BACKEND_INFO (ID);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_21', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 21, '7:36227a8cd1e0cdb690047bac2a6c5a21', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_BACK_2_S, constraintName=FK_DOMIBUS_CONN_DOMIBUS_CON_01, referencedTableName=DOMIBUS_CONNECTOR_BACKEND_INFO', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_22::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_BACK_2_S ADD CONSTRAINT FK_DOMIBUS_CONN_DOMIBUS_CON_02 FOREIGN KEY (DOMIBUS_CONNECTOR_SERVICE_ID) REFERENCES DOMIBUS_CONNECTOR_SERVICE (SERVICE);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_22', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 22, '7:49f051a349b138a5e072780022152398', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_BACK_2_S, constraintName=FK_DOMIBUS_CONN_DOMIBUS_CON_02, referencedTableName=DOMIBUS_CONNECTOR_SERVICE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_23::StephanSpindler
ALTER TABLE DOMIBUS_CONNECTOR_BIGDATA ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_BIGDATA FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID);

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_23', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 23, '7:34f4a9d6269a7dfa4e99b88a0fa71ee7', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_BIGDATA, constraintName=FK_DOMIBUS_CONNECTOR_BIGDATA, referencedTableName=DOMIBUS_CONNECTOR_MESSAGE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::tag-db-domibus-4.0::StephanSpindler
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID, TAG) VALUES ('tag-db-domibus-4.0', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 24, '7:9154cc53e107d3186ebc05f34ddc6844', 'tagDatabase', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126', 'DOMIBUS_DB_V4.0');

-- Changeset db/changelog/install/initial-changelog-webadmin.xml::changelog-1.0::StephanSpindler
-- Create default admin user with username admin and password admin
CREATE TABLE DOMIBUS_WEBADMIN_USER (USERNAME VARCHAR2(30) NOT NULL, "PASSWORD" VARCHAR2(150), SALT VARCHAR2(64), ROLE VARCHAR2(20), CONSTRAINT PK_DOMIBUS_WEBADMIN_USER PRIMARY KEY (USERNAME));

CREATE TABLE DOMIBUS_WEBADMIN_PROPERTIES (PROPERTIES_KEY VARCHAR2(30), PROPERTIES_VALUE VARCHAR2(100));

INSERT INTO DOMIBUS_WEBADMIN_USER (USERNAME, "PASSWORD", SALT, ROLE) VALUES ('admin', '2bf5e637d0d82a75ca43e3be85df2c23febffc0cc221f5e010937005df478a19b5eaab59fe7e4e97f6b43ba648c169effd432e19817f386987d058c239236306', '5b424031616564356639', 'admin');

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-1.0', 'StephanSpindler', 'db/changelog/install/initial-changelog-webadmin.xml', SYSTIMESTAMP, 25, '7:f46e013f2c94606e27c904326f5b19ea', 'createTable tableName=DOMIBUS_WEBADMIN_USER; createTable tableName=DOMIBUS_WEBADMIN_PROPERTIES; insert tableName=DOMIBUS_WEBADMIN_USER', 'Create default admin user with username admin and password admin', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Release Database Lock
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;
