-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: db/changelog/install/initial-4.0.xml
-- Ran at: 11.04.18 14:43
-- Against: CONNECTORNEW@jdbc:oracle:thin:connectornew//@localhost:1521/xe
-- Liquibase version: 3.5.3
-- *********************************************************************

SET DEFINE OFF;

-- Create Database Lock Table
CREATE TABLE CONNECTORNEW.DATABASECHANGELOGLOCK (ID INTEGER NOT NULL, LOCKED NUMBER(1) NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR2(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID));

-- Initialize Database Lock Table
DELETE FROM CONNECTORNEW.DATABASECHANGELOGLOCK;

INSERT INTO CONNECTORNEW.DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, 0);

-- Lock Database
UPDATE CONNECTORNEW.DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = 'PC65589 (172.31.33.137)', LOCKGRANTED = to_timestamp('2018-04-11 14:43:31.458', 'YYYY-MM-DD HH24:MI:SS.FF') WHERE ID = 1 AND LOCKED = 0;

-- Create Database Change Log Table
CREATE TABLE CONNECTORNEW.DATABASECHANGELOG (ID VARCHAR2(255) NOT NULL, AUTHOR VARCHAR2(255) NOT NULL, FILENAME VARCHAR2(255) NOT NULL, DATEEXECUTED TIMESTAMP NOT NULL, ORDEREXECUTED INTEGER NOT NULL, EXECTYPE VARCHAR2(10) NOT NULL, MD5SUM VARCHAR2(35), DESCRIPTION VARCHAR2(255), COMMENTS VARCHAR2(255), TAG VARCHAR2(255), LIQUIBASE VARCHAR2(20), CONTEXTS VARCHAR2(255), LABELS VARCHAR2(255), DEPLOYMENT_ID VARCHAR2(10));

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_1::StephanSpindler
CREATE TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_SEQ_STORE (SEQ_NAME VARCHAR2(255 CHAR) NOT NULL, SEQ_VALUE NUMBER(10) NOT NULL);

ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_SEQ_STORE ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_SEQ_STORE PRIMARY KEY (SEQ_NAME);

CREATE INDEX CONNECTORNEW.INDEX_PK_DOMIBUS_CONNECTOR_SEQ_STORE ON CONNECTORNEW.DOMIBUS_CONNECTOR_SEQ_STORE(SEQ_NAME);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_1', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 1, '7:2e584da7a6e6b724143dcb8123094e0a', 'createTable tableName=DOMIBUS_CONNECTOR_SEQ_STORE; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_SEQ_STORE, tableName=DOMIBUS_CONNECTOR_SEQ_STORE; createIndex indexName=INDEX_PK_DOMIBUS_CONNECTOR_SEQ_STORE, tableName=DOMIBUS_CONNECTOR_SEQ_STORE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_2::StephanSpindler
CREATE TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_SERVICE (SERVICE VARCHAR2(255 CHAR) NOT NULL, SERVICE_TYPE VARCHAR2(255 CHAR) NOT NULL);

ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_SERVICE ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_SERVICE PRIMARY KEY (SERVICE);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_2', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 2, '7:2f2a0bba064baf129f6f439bae4926fc', 'createTable tableName=DOMIBUS_CONNECTOR_SERVICE; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_SERVICE, tableName=DOMIBUS_CONNECTOR_SERVICE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_3::StephanSpindler
CREATE TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_PARTY (PARTY_ID VARCHAR2(255 CHAR) NOT NULL, ROLE VARCHAR2(255 CHAR) NOT NULL, PARTY_ID_TYPE VARCHAR2(512 CHAR));

ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_PARTY ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_PARTY PRIMARY KEY (PARTY_ID, ROLE);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_3', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 3, '7:432aeac4fdb7028dc546c43559ccfed2', 'createTable tableName=DOMIBUS_CONNECTOR_PARTY; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_PARTY, tableName=DOMIBUS_CONNECTOR_PARTY', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_4::StephanSpindler
CREATE TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_MSG_ERROR (ID DECIMAL(10, 0) NOT NULL, MESSAGE_ID DECIMAL(10, 0) NOT NULL, ERROR_MESSAGE VARCHAR2(512 CHAR) NOT NULL, DETAILED_TEXT CLOB, ERROR_SOURCE CLOB, CREATED TIMESTAMP NOT NULL);

ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_MSG_ERROR ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_MSG_ERROR PRIMARY KEY (ID);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_4', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 4, '7:3a47c2c867483093d1730efd10403d73', 'createTable tableName=DOMIBUS_CONNECTOR_MSG_ERROR; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_MSG_ERROR, tableName=DOMIBUS_CONNECTOR_MSG_ERROR', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_5::StephanSpindler
CREATE TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_MSG_CONT (ID DECIMAL(10, 0) NOT NULL, MESSAGE_ID DECIMAL(10, 0), CONTENT_TYPE VARCHAR2(255 CHAR), CONTENT BLOB, CHECKSUM CLOB, CREATED TIMESTAMP);

ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_MSG_CONT ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_MSG__01 PRIMARY KEY (ID);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_5', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 5, '7:fbd73c7e0100efc910f7254fa4d0e345', 'createTable tableName=DOMIBUS_CONNECTOR_MSG_CONT; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_MSG__01, tableName=DOMIBUS_CONNECTOR_MSG_CONT', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_6::StephanSpindler
CREATE TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_BIGDATA (ID VARCHAR2(255 CHAR) NOT NULL, CHECKSUM CLOB, CREATED TIMESTAMP, MESSAGE_ID DECIMAL(10, 0), LAST_ACCESS TIMESTAMP, NAME CLOB, CONTENT BLOB, MIMETYPE VARCHAR2(255 CHAR));

ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_BIGDATA ADD PRIMARY KEY (ID);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_6', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 6, '7:61c3dafb68215f822deb0500336ffc6b', 'createTable tableName=DOMIBUS_CONNECTOR_BIGDATA; addPrimaryKey tableName=DOMIBUS_CONNECTOR_BIGDATA', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_7::StephanSpindler
CREATE TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_MESSAGE_INFO (ID DECIMAL(10, 0) NOT NULL, MESSAGE_ID DECIMAL(10, 0) NOT NULL, CONNECTOR_MESSAGE_ID VARCHAR2(255 CHAR), FROM_PARTY_ID VARCHAR2(255 CHAR), FROM_PARTY_ROLE VARCHAR2(255 CHAR), TO_PARTY_ID VARCHAR2(255 CHAR), TO_PARTY_ROLE VARCHAR2(255 CHAR), ORIGINAL_SENDER VARCHAR2(255 CHAR), FINAL_RECIPIENT VARCHAR2(255 CHAR), SERVICE VARCHAR2(255 CHAR), ACTION VARCHAR2(255 CHAR), CREATED TIMESTAMP, UPDATED TIMESTAMP);

ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_MESSAGE_INFO PRIMARY KEY (ID);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_7', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 7, '7:3ed5d0a9914002501c4a94294018f49b', 'createTable tableName=DOMIBUS_CONNECTOR_MESSAGE_INFO; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_MESSAGE_INFO, tableName=DOMIBUS_CONNECTOR_MESSAGE_INFO', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_8::StephanSpindler
CREATE TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_MESSAGE (ID DECIMAL(10, 0) NOT NULL, EBMS_MESSAGE_ID VARCHAR2(255 CHAR), BACKEND_MESSAGE_ID VARCHAR2(255 CHAR), BACKEND_NAME VARCHAR2(255 CHAR), CONNECTOR_MESSAGE_ID VARCHAR2(255 CHAR), CONVERSATION_ID VARCHAR2(255 CHAR), DIRECTION VARCHAR2(10), HASH_VALUE CLOB, CONFIRMED TIMESTAMP, REJECTED TIMESTAMP, DELIVERED_BACKEND TIMESTAMP, DELIVERED_GW TIMESTAMP, UPDATED TIMESTAMP, CREATED TIMESTAMP);

ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_MESSAGE ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_MESSAGE PRIMARY KEY (ID);

ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_MESSAGE ADD CONSTRAINT UNIQUE_CONNECTOR_MESSAGE_ID UNIQUE (CONNECTOR_MESSAGE_ID);

ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_MESSAGE ADD CONSTRAINT UQ_DOMIBUS_CONNE_EBMS_MESSAGE UNIQUE (EBMS_MESSAGE_ID);

ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_MESSAGE ADD CONSTRAINT UQ_DOMIBUS_CONNE_NAT_MESSAGE_ UNIQUE (BACKEND_MESSAGE_ID);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_8', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 8, '7:9d2c70447b5541a8c50d755d73c56305', 'createTable tableName=DOMIBUS_CONNECTOR_MESSAGE; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_MESSAGE, tableName=DOMIBUS_CONNECTOR_MESSAGE; addUniqueConstraint constraintName=UNIQUE_CONNECTOR_MESSAGE_ID, tableName=DOMIBUS_CONNECTOR_MESSAGE; a...', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_9::StephanSpindler
CREATE TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_EVIDENCE (ID DECIMAL(10, 0) NOT NULL, MESSAGE_ID DECIMAL(10, 0) NOT NULL, TYPE VARCHAR2(255 CHAR), EVIDENCE CLOB, DELIVERED_NAT TIMESTAMP, DELIVERED_GW TIMESTAMP, UPDATED TIMESTAMP);

ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_EVIDENCE ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_EVIDENCE PRIMARY KEY (ID);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_9', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 9, '7:3a5add3e93854cc4b53973d44f4a3d41', 'createTable tableName=DOMIBUS_CONNECTOR_EVIDENCE; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_EVIDENCE, tableName=DOMIBUS_CONNECTOR_EVIDENCE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_10::StephanSpindler
CREATE TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_CONT_TYPE (MESSAGE_CONTENT_TYPE VARCHAR2(255 CHAR) NOT NULL);

ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_CONT_TYPE ADD CONSTRAINT PK_DOMIBUS_CONN_02 PRIMARY KEY (MESSAGE_CONTENT_TYPE);

CREATE TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_ACTION (ACTION VARCHAR2(255 CHAR) NOT NULL, PDF_REQUIRED DECIMAL(1, 0) NOT NULL);

ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_ACTION ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_ACTION PRIMARY KEY (ACTION);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_10', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 10, '7:505c55a53f80e4b0be9614c8aa550716', 'createTable tableName=DOMIBUS_CONNECTOR_CONT_TYPE; addPrimaryKey constraintName=PK_DOMIBUS_CONN_02, tableName=DOMIBUS_CONNECTOR_CONT_TYPE; createTable tableName=DOMIBUS_CONNECTOR_ACTION; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_ACTION, ta...', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_11::StephanSpindler
CREATE TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_BACKEND_INFO (ID DECIMAL(10, 0) NOT NULL, BACKEND_NAME VARCHAR2(255 CHAR) NOT NULL, BACKEND_KEY_ALIAS VARCHAR2(255 CHAR) NOT NULL, BACKEND_KEY_PASS VARCHAR2(255 CHAR), BACKEND_SERVICE_TYPE VARCHAR2(255 CHAR), BACKEND_ENABLED NUMBER(1) DEFAULT 1, BACKEND_DEFAULT NUMBER(1) DEFAULT 0, BACKEND_DESCRIPTION CLOB, BACKEND_PUSH_ADDRESS CLOB);

ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_BACKEND_INFO ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_BACK_01 PRIMARY KEY (ID);

ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_BACKEND_INFO ADD CONSTRAINT UN_DOMIBUS_CONNECTOR_BACK_01 UNIQUE (BACKEND_NAME);

ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_BACKEND_INFO ADD CONSTRAINT UN_DOMIBUS_CONNECTOR_BACK_02 UNIQUE (BACKEND_KEY_ALIAS);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_11', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 11, '7:c9dd1c142f0349be27dbb43d2f280e9e', 'createTable tableName=DOMIBUS_CONNECTOR_BACKEND_INFO; addPrimaryKey constraintName=PK_DOMIBUS_CONNECTOR_BACK_01, tableName=DOMIBUS_CONNECTOR_BACKEND_INFO; addUniqueConstraint constraintName=UN_DOMIBUS_CONNECTOR_BACK_01, tableName=DOMIBUS_CONNECTOR...', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_12::StephanSpindler
CREATE TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_BACK_2_S (DOMIBUS_CONNECTOR_SERVICE_ID VARCHAR2(255 CHAR) NOT NULL, DOMIBUS_CONNECTOR_BACKEND_ID DECIMAL(10, 0) NOT NULL);

ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_BACK_2_S ADD CONSTRAINT PK_DOMIBUS_CONN_01 PRIMARY KEY (DOMIBUS_CONNECTOR_SERVICE_ID, DOMIBUS_CONNECTOR_BACKEND_ID);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_12', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 12, '7:302920d7ab0ebc9bbc339e491527f06c', 'createTable tableName=DOMIBUS_CONNECTOR_BACK_2_S; addPrimaryKey constraintName=PK_DOMIBUS_CONN_01, tableName=DOMIBUS_CONNECTOR_BACK_2_S', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_13::StephanSpindler
ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_MSG_ERROR ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MSG_ERROR FOREIGN KEY (MESSAGE_ID) REFERENCES CONNECTORNEW.DOMIBUS_CONNECTOR_MESSAGE (ID);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_13', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 13, '7:df71593e1116807cd89bc97b3b6269f9', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_MSG_ERROR, constraintName=FK_DOMIBUS_CONNECTOR_MSG_ERROR, referencedTableName=DOMIBUS_CONNECTOR_MESSAGE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_14::StephanSpindler
ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_MSG_CONT ADD CONSTRAINT FK_DOMIBUS_CONN_DOMIBUS_CON_04 FOREIGN KEY (MESSAGE_ID) REFERENCES CONNECTORNEW.DOMIBUS_CONNECTOR_MESSAGE (ID);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_14', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 14, '7:79940f7647fa5b32ba163f93ec7dc443', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_MSG_CONT, constraintName=FK_DOMIBUS_CONN_DOMIBUS_CON_04, referencedTableName=DOMIBUS_CONNECTOR_MESSAGE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_15::StephanSpindler
ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_1 FOREIGN KEY (ACTION) REFERENCES CONNECTORNEW.DOMIBUS_CONNECTOR_ACTION (ACTION);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_15', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 15, '7:d4a1db943fc545fda77b01e06774383e', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_MESSAGE_INFO, constraintName=FK_DOMIBUS_CONNECTOR_MESSAGE_1, referencedTableName=DOMIBUS_CONNECTOR_ACTION', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_16::StephanSpindler
ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_2 FOREIGN KEY (SERVICE) REFERENCES CONNECTORNEW.DOMIBUS_CONNECTOR_SERVICE (service);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_16', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 16, '7:65567928a17beed8178f4308c02a94cb', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_MESSAGE_INFO, constraintName=FK_DOMIBUS_CONNECTOR_MESSAGE_2, referencedTableName=DOMIBUS_CONNECTOR_SERVICE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_17::StephanSpindler
ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_3 FOREIGN KEY (FROM_PARTY_ID, FROM_PARTY_ROLE) REFERENCES CONNECTORNEW.DOMIBUS_CONNECTOR_PARTY (PARTY_ID, ROLE);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_17', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 17, '7:64df2871727e11981a6f06cfdfc67123', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_MESSAGE_INFO, constraintName=FK_DOMIBUS_CONNECTOR_MESSAGE_3, referencedTableName=DOMIBUS_CONNECTOR_PARTY', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_18::StephanSpindler
ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_4 FOREIGN KEY (TO_PARTY_ID, TO_PARTY_ROLE) REFERENCES CONNECTORNEW.DOMIBUS_CONNECTOR_PARTY (PARTY_ID, ROLE);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_18', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 18, '7:75eb3ba07f1a851f7e310f7614b668c5', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_MESSAGE_INFO, constraintName=FK_DOMIBUS_CONNECTOR_MESSAGE_4, referencedTableName=DOMIBUS_CONNECTOR_PARTY', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_19::StephanSpindler
ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_I FOREIGN KEY (MESSAGE_ID) REFERENCES CONNECTORNEW.DOMIBUS_CONNECTOR_MESSAGE (ID);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_19', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 19, '7:a1988a2bc083b550439d2309b34d7c4d', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_MESSAGE_INFO, constraintName=FK_DOMIBUS_CONNECTOR_MESSAGE_I, referencedTableName=DOMIBUS_CONNECTOR_MESSAGE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_20::StephanSpindler
ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_EVIDENCE ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_EVIDENCES FOREIGN KEY (MESSAGE_ID) REFERENCES CONNECTORNEW.DOMIBUS_CONNECTOR_MESSAGE (ID);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_20', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 20, '7:78539cc81c1e1b40db24b041e763ece6', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_EVIDENCE, constraintName=FK_DOMIBUS_CONNECTOR_EVIDENCES, referencedTableName=DOMIBUS_CONNECTOR_MESSAGE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_21::StephanSpindler
ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_BACK_2_S ADD CONSTRAINT FK_DOMIBUS_CONN_DOMIBUS_CON_01 FOREIGN KEY (DOMIBUS_CONNECTOR_BACKEND_ID) REFERENCES CONNECTORNEW.DOMIBUS_CONNECTOR_BACKEND_INFO (ID);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_21', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 21, '7:36227a8cd1e0cdb690047bac2a6c5a21', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_BACK_2_S, constraintName=FK_DOMIBUS_CONN_DOMIBUS_CON_01, referencedTableName=DOMIBUS_CONNECTOR_BACKEND_INFO', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_22::StephanSpindler
ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_BACK_2_S ADD CONSTRAINT FK_DOMIBUS_CONN_DOMIBUS_CON_02 FOREIGN KEY (DOMIBUS_CONNECTOR_SERVICE_ID) REFERENCES CONNECTORNEW.DOMIBUS_CONNECTOR_SERVICE (SERVICE);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_22', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 22, '7:49f051a349b138a5e072780022152398', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_BACK_2_S, constraintName=FK_DOMIBUS_CONN_DOMIBUS_CON_02, referencedTableName=DOMIBUS_CONNECTOR_SERVICE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::changelog-domibus-4.0_23::StephanSpindler
ALTER TABLE CONNECTORNEW.DOMIBUS_CONNECTOR_BIGDATA ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_BIGDATA FOREIGN KEY (MESSAGE_ID) REFERENCES CONNECTORNEW.DOMIBUS_CONNECTOR_MESSAGE (ID);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-domibus-4.0_23', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 23, '7:34f4a9d6269a7dfa4e99b88a0fa71ee7', 'addForeignKeyConstraint baseTableName=DOMIBUS_CONNECTOR_BIGDATA, constraintName=FK_DOMIBUS_CONNECTOR_BIGDATA, referencedTableName=DOMIBUS_CONNECTOR_MESSAGE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset /db/changelog/install/initial-changelog-domibus.xml::tag-db-domibus-4.0::StephanSpindler
INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID, TAG) VALUES ('tag-db-domibus-4.0', 'StephanSpindler', '/db/changelog/install/initial-changelog-domibus.xml', SYSTIMESTAMP, 24, '7:9154cc53e107d3186ebc05f34ddc6844', 'tagDatabase', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126', 'DOMIBUS_DB_V4.0');

-- Changeset db/changelog/install/initial-changelog-webadmin.xml::changelog-1.0::StephanSpindler
-- Create default admin user with username admin and password admin
CREATE TABLE CONNECTORNEW.DOMIBUS_WEBADMIN_USER (USERNAME VARCHAR2(30) NOT NULL, "PASSWORD" VARCHAR2(150), SALT VARCHAR2(64), ROLE VARCHAR2(20), CONSTRAINT PK_DOMIBUS_WEBADMIN_USER PRIMARY KEY (USERNAME));

CREATE TABLE CONNECTORNEW.DOMIBUS_WEBADMIN_PROPERTIES (PROPERTIES_KEY VARCHAR2(30), PROPERTIES_VALUE VARCHAR2(100));

INSERT INTO CONNECTORNEW.DOMIBUS_WEBADMIN_USER (USERNAME, "PASSWORD", SALT, ROLE) VALUES ('admin', '2bf5e637d0d82a75ca43e3be85df2c23febffc0cc221f5e010937005df478a19b5eaab59fe7e4e97f6b43ba648c169effd432e19817f386987d058c239236306', '5b424031616564356639', 'admin');

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('changelog-1.0', 'StephanSpindler', 'db/changelog/install/initial-changelog-webadmin.xml', SYSTIMESTAMP, 25, '7:f46e013f2c94606e27c904326f5b19ea', 'createTable tableName=DOMIBUS_WEBADMIN_USER; createTable tableName=DOMIBUS_WEBADMIN_PROPERTIES; insert tableName=DOMIBUS_WEBADMIN_USER', 'Create default admin user with username admin and password admin', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-1::StephanSpindler
CREATE TABLE CONNECTORNEW.DCON_QRTZ_JOB_DETAILS (SCHED_NAME VARCHAR2(120) NOT NULL, JOB_NAME VARCHAR2(200) NOT NULL, JOB_GROUP VARCHAR2(200) NOT NULL, DESCRIPTION VARCHAR2(250), JOB_CLASS_NAME VARCHAR2(250) NOT NULL, IS_DURABLE NUMBER(1) NOT NULL, IS_NONCONCURRENT NUMBER(1) NOT NULL, IS_UPDATE_DATA NUMBER(1) NOT NULL, REQUESTS_RECOVERY NUMBER(1) NOT NULL, JOB_DATA BLOB, CONSTRAINT PK_DCON_QRTZ_JOB_DETAILS PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP));

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-1', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 26, '7:6894318992d3a73f450e8b1086afb840', 'createTable tableName=DCON_QRTZ_JOB_DETAILS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-2::StephanSpindler
CREATE TABLE CONNECTORNEW.DCON_QRTZ_TRIGGERS (SCHED_NAME VARCHAR2(120) NOT NULL, TRIGGER_NAME VARCHAR2(200) NOT NULL, TRIGGER_GROUP VARCHAR2(200) NOT NULL, JOB_NAME VARCHAR2(200) NOT NULL, JOB_GROUP VARCHAR2(200) NOT NULL, DESCRIPTION VARCHAR2(250), NEXT_FIRE_TIME NUMBER(38, 0), PREV_FIRE_TIME NUMBER(38, 0), PRIORITY INTEGER, TRIGGER_STATE VARCHAR2(16) NOT NULL, TRIGGER_TYPE VARCHAR2(8) NOT NULL, START_TIME NUMBER(38, 0) NOT NULL, END_TIME NUMBER(38, 0), CALENDAR_NAME VARCHAR2(200), MISFIRE_INSTR NUMBER(5), JOB_DATA BLOB);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-2', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 27, '7:539e3dfe79119381bf27285bb77f124e', 'createTable tableName=DCON_QRTZ_TRIGGERS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-2.1::StephanSpindler
ALTER TABLE CONNECTORNEW.DCON_QRTZ_TRIGGERS ADD PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-2.1', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 28, '7:7716981b9630467ef2715f42537c57e2', 'addPrimaryKey tableName=DCON_QRTZ_TRIGGERS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-2.2::StephanSpindler
ALTER TABLE CONNECTORNEW.DCON_QRTZ_TRIGGERS ADD CONSTRAINT fk_sched_to_job_details FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP) REFERENCES CONNECTORNEW.DCON_QRTZ_JOB_DETAILS (SCHED_NAME, JOB_NAME, JOB_GROUP);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-2.2', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 29, '7:c21ee8df7e25cca1fa0c37af97476ee6', 'addForeignKeyConstraint baseTableName=DCON_QRTZ_TRIGGERS, constraintName=fk_sched_to_job_details, referencedTableName=DCON_QRTZ_JOB_DETAILS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-3::StephanSpindler
CREATE TABLE CONNECTORNEW.DCON_QRTZ_SIMPLE_TRIGGERS (SCHED_NAME VARCHAR2(120) NOT NULL, TRIGGER_NAME VARCHAR2(200) NOT NULL, TRIGGER_GROUP VARCHAR2(200) NOT NULL, REPEAT_COUNT NUMBER(38, 0) NOT NULL, REPEAT_INTERVAL NUMBER(38, 0) NOT NULL, TIMES_TRIGGERED NUMBER(38, 0) NOT NULL);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-3', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 30, '7:a38afb2aee37dee6b09fec22a0f910d4', 'createTable tableName=DCON_QRTZ_SIMPLE_TRIGGERS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-3.1::StephanSpindler
ALTER TABLE CONNECTORNEW.DCON_QRTZ_SIMPLE_TRIGGERS ADD PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-3.1', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 31, '7:21f48283a32a3dec4cf1abd2dbf742c0', 'addPrimaryKey tableName=DCON_QRTZ_SIMPLE_TRIGGERS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-3.2::StephanSpindler
ALTER TABLE CONNECTORNEW.DCON_QRTZ_SIMPLE_TRIGGERS ADD CONSTRAINT fk_schedtrigger_to_qrtz_triggers FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES CONNECTORNEW.DCON_QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-3.2', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 32, '7:8df85236d15f024b78af784f30adc02f', 'addForeignKeyConstraint baseTableName=DCON_QRTZ_SIMPLE_TRIGGERS, constraintName=fk_schedtrigger_to_qrtz_triggers, referencedTableName=DCON_QRTZ_TRIGGERS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-4::StephanSpindler
CREATE TABLE CONNECTORNEW.DCON_QRTZ_CRON_TRIGGERS (SCHED_NAME VARCHAR2(120) NOT NULL, TRIGGER_NAME VARCHAR2(200) NOT NULL, TRIGGER_GROUP VARCHAR2(200) NOT NULL, CRON_EXPRESSION VARCHAR2(120) NOT NULL, TIME_ZONE_ID VARCHAR2(80));

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-4', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 33, '7:8debd5cadfd8ffb4f0e73f2ffe33d2df', 'createTable tableName=DCON_QRTZ_CRON_TRIGGERS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-4.1::StephanSpindler
ALTER TABLE CONNECTORNEW.DCON_QRTZ_CRON_TRIGGERS ADD PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-4.1', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 34, '7:ae455f628acdb815d8ded9a5c9a89763', 'addPrimaryKey tableName=DCON_QRTZ_CRON_TRIGGERS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-4.2::StephanSpindler
ALTER TABLE CONNECTORNEW.DCON_QRTZ_CRON_TRIGGERS ADD CONSTRAINT fk_qrtzcrontriggers_to_qrtztriggers FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES CONNECTORNEW.DCON_QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-4.2', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 35, '7:9e550e4d2fa5d396c4309d4e4fad0d77', 'addForeignKeyConstraint baseTableName=DCON_QRTZ_CRON_TRIGGERS, constraintName=fk_qrtzcrontriggers_to_qrtztriggers, referencedTableName=DCON_QRTZ_TRIGGERS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-5::StephanSpindler
CREATE TABLE CONNECTORNEW.DCON_QRTZ_SIMPROP_TRIGGERS (SCHED_NAME VARCHAR2(120) NOT NULL, TRIGGER_NAME VARCHAR2(200) NOT NULL, TRIGGER_GROUP VARCHAR2(200) NOT NULL, STR_PROP_1 VARCHAR2(512), STR_PROP_2 VARCHAR2(512), STR_PROP_3 VARCHAR2(512), INT_PROP_1 INTEGER, INT_PROP_2 INTEGER, LONG_PROP_1 NUMBER(38, 0), LONG_PROP_2 NUMBER(38, 0), DEC_PROP_1 DECIMAL(13, 4), DEC_PROP_2 DECIMAL(13, 4), BOOL_PROP_1 VARCHAR2(5), BOOL_PROP_2 VARCHAR2(5));

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-5', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 36, '7:66ee4c4d3135bbee96aa34173f0e2d49', 'createTable tableName=DCON_QRTZ_SIMPROP_TRIGGERS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-5.1::StephanSpindler
ALTER TABLE CONNECTORNEW.DCON_QRTZ_SIMPROP_TRIGGERS ADD PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-5.1', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 37, '7:02b1bd28f4c895ccb829900500c7eb78', 'addPrimaryKey tableName=DCON_QRTZ_SIMPROP_TRIGGERS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-5.2::StephanSpindler
ALTER TABLE CONNECTORNEW.DCON_QRTZ_SIMPROP_TRIGGERS ADD CONSTRAINT fk_qrtzsimproptriggers_to_qrtztriggers FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES CONNECTORNEW.DCON_QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-5.2', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 38, '7:f464c17850bc99f3510e8fc80aea4d6f', 'addForeignKeyConstraint baseTableName=DCON_QRTZ_SIMPROP_TRIGGERS, constraintName=fk_qrtzsimproptriggers_to_qrtztriggers, referencedTableName=DCON_QRTZ_TRIGGERS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-6::StephanSpindler
CREATE TABLE CONNECTORNEW.DCON_QRTZ_BLOB_TRIGGERS (SCHED_NAME VARCHAR2(120) NOT NULL, TRIGGER_NAME VARCHAR2(200) NOT NULL, TRIGGER_GROUP VARCHAR2(200) NOT NULL, BLOB_DATA BLOB);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-6', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 39, '7:5fd25df814449af5e22a060edc1321cb', 'createTable tableName=DCON_QRTZ_BLOB_TRIGGERS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-6.1::StephanSpindler
ALTER TABLE CONNECTORNEW.DCON_QRTZ_BLOB_TRIGGERS ADD PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-6.1', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 40, '7:566db542d801eee7819fbadebcac1eee', 'addPrimaryKey tableName=DCON_QRTZ_BLOB_TRIGGERS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-6.2::StephanSpindler
ALTER TABLE CONNECTORNEW.DCON_QRTZ_BLOB_TRIGGERS ADD CONSTRAINT fk_qrtzblobtriggers_to_qrtztriggers FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES CONNECTORNEW.DCON_QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-6.2', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 41, '7:647bc81fe358908ad047ca9357cfdda0', 'addForeignKeyConstraint baseTableName=DCON_QRTZ_BLOB_TRIGGERS, constraintName=fk_qrtzblobtriggers_to_qrtztriggers, referencedTableName=DCON_QRTZ_TRIGGERS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-7::StephanSpindler
CREATE TABLE CONNECTORNEW.DCON_QRTZ_CALENDARS (SCHED_NAME VARCHAR2(120) NOT NULL, CALENDAR_NAME VARCHAR2(200) NOT NULL, CALENDAR BLOB NOT NULL);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-7', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 42, '7:8f95cf8890d2f3ff3d3c83ad5dd15099', 'createTable tableName=DCON_QRTZ_CALENDARS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-7.1::StephanSpindler
ALTER TABLE CONNECTORNEW.DCON_QRTZ_CALENDARS ADD PRIMARY KEY (SCHED_NAME, CALENDAR_NAME);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-7.1', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 43, '7:c72e09a57afa5cf5b4c01d28466c92c2', 'addPrimaryKey tableName=DCON_QRTZ_CALENDARS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-8::StephanSpindler
CREATE TABLE CONNECTORNEW.DCON_QRTZ_PAUSED_TRIGGER_GRPS (SCHED_NAME VARCHAR2(120) NOT NULL, TRIGGER_GROUP VARCHAR2(200) NOT NULL);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-8', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 44, '7:b4476fbcf8de45d511c82056e676b68d', 'createTable tableName=DCON_QRTZ_PAUSED_TRIGGER_GRPS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-8.1::StephanSpindler
ALTER TABLE CONNECTORNEW.DCON_QRTZ_PAUSED_TRIGGER_GRPS ADD PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-8.1', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 45, '7:580d53a416ab28b2a95ba461f540f73b', 'addPrimaryKey tableName=DCON_QRTZ_PAUSED_TRIGGER_GRPS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-9::StephanSpindler
CREATE TABLE CONNECTORNEW.DCON_QRTZ_FIRED_TRIGGERS (SCHED_NAME VARCHAR2(120) NOT NULL, ENTRY_ID VARCHAR2(95) NOT NULL, TRIGGER_NAME VARCHAR2(200) NOT NULL, TRIGGER_GROUP VARCHAR2(200) NOT NULL, INSTANCE_NAME VARCHAR2(200) NOT NULL, FIRED_TIME NUMBER(38, 0) NOT NULL, SCHED_TIME NUMBER(38, 0) NOT NULL, PRIORITY INTEGER NOT NULL, STATE VARCHAR2(16) NOT NULL, JOB_NAME VARCHAR2(200), JOB_GROUP VARCHAR2(200), IS_NONCONCURRENT NUMBER(1), REQUESTS_RECOVERY NUMBER(1));

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-9', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 46, '7:5231b128ad234361291c2f3e9ca356ea', 'createTable tableName=DCON_QRTZ_FIRED_TRIGGERS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-9.1::StephanSpindler
ALTER TABLE CONNECTORNEW.DCON_QRTZ_FIRED_TRIGGERS ADD PRIMARY KEY (SCHED_NAME, ENTRY_ID);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-9.1', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 47, '7:1e0b8f34085a929ec25ba251a9461bf7', 'addPrimaryKey tableName=DCON_QRTZ_FIRED_TRIGGERS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-10::StephanSpindler
CREATE TABLE CONNECTORNEW.DCON_QRTZ_SCHEDULER_STATE (SCHED_NAME VARCHAR2(120) NOT NULL, INSTANCE_NAME VARCHAR2(200) NOT NULL, LAST_CHECKIN_TIME NUMBER(38, 0) NOT NULL, CHECKIN_INTERVAL NUMBER(38, 0) NOT NULL);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-10', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 48, '7:a00b396e75af85fc13849873bb250f8d', 'createTable tableName=DCON_QRTZ_SCHEDULER_STATE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-10.1::StephanSpindler
ALTER TABLE CONNECTORNEW.DCON_QRTZ_SCHEDULER_STATE ADD PRIMARY KEY (SCHED_NAME, INSTANCE_NAME);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-10.1', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 49, '7:1b5429580d7f93c001cc97f32920e65b', 'addPrimaryKey tableName=DCON_QRTZ_SCHEDULER_STATE', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-11::StephanSpindler
CREATE TABLE CONNECTORNEW.DCON_QRTZ_LOCKS (SCHED_NAME VARCHAR2(120) NOT NULL, LOCK_NAME VARCHAR2(40) NOT NULL);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-11', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 50, '7:66b900e0c7e794e5270e7a0d852b4446', 'createTable tableName=DCON_QRTZ_LOCKS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::init-quartz-11.1::StephanSpindler
ALTER TABLE CONNECTORNEW.DCON_QRTZ_LOCKS ADD PRIMARY KEY (SCHED_NAME, LOCK_NAME);

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('init-quartz-11.1', 'StephanSpindler', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 51, '7:6c1aea2f594dcd2acaa9ab33fc45e3a6', 'addPrimaryKey tableName=DCON_QRTZ_LOCKS', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Changeset db/changelog/install/initial-changelog-quartz.xml::StephanSpindler::init-quartz-finished
INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID, TAG) VALUES ('StephanSpindler', 'init-quartz-finished', 'db/changelog/install/initial-changelog-quartz.xml', SYSTIMESTAMP, 52, '7:b20200175c5324a76b29c1e64e146046', 'tagDatabase', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126', 'QUARTZ_DB ');

-- Changeset /db/changelog/install/initial-changelog-data.sql::initialData_1::StephanSpindler
INSERT INTO DOMIBUS_CONNECTOR_SEQ_STORE VALUES ('DOMIBUS_CONNECTOR_MESSAGES.ID', 0);

INSERT INTO DOMIBUS_CONNECTOR_SEQ_STORE VALUES ('DOMIBUS_CONNECTOR_EVIDENCES.ID', 0);

INSERT INTO DOMIBUS_CONNECTOR_SEQ_STORE VALUES ('DOMIBUS_CONNECTOR_MESSAGE_INFO.ID', 0);

INSERT INTO DOMIBUS_CONNECTOR_SEQ_STORE VALUES ('DOMIBUS_CONNECTOR_MSG_ERROR.ID', 0);

INSERT INTO DOMIBUS_CONNECTOR_PARTY VALUES ('ARHS', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');

INSERT INTO DOMIBUS_CONNECTOR_PARTY VALUES ('AT', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');

INSERT INTO DOMIBUS_CONNECTOR_PARTY VALUES ('CTP', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');

INSERT INTO DOMIBUS_CONNECTOR_PARTY VALUES ('CZ', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');

INSERT INTO DOMIBUS_CONNECTOR_PARTY VALUES ('DE', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');

INSERT INTO DOMIBUS_CONNECTOR_PARTY VALUES ('EC', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');

INSERT INTO DOMIBUS_CONNECTOR_PARTY VALUES ('EE', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');

INSERT INTO DOMIBUS_CONNECTOR_PARTY VALUES ('ES', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');

INSERT INTO DOMIBUS_CONNECTOR_PARTY VALUES ('FR', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');

INSERT INTO DOMIBUS_CONNECTOR_PARTY VALUES ('GR', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');

INSERT INTO DOMIBUS_CONNECTOR_PARTY VALUES ('IT', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');

INSERT INTO DOMIBUS_CONNECTOR_PARTY VALUES ('ITIC', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');

INSERT INTO DOMIBUS_CONNECTOR_PARTY VALUES ('MT', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');

INSERT INTO DOMIBUS_CONNECTOR_PARTY VALUES ('NL', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');

INSERT INTO DOMIBUS_CONNECTOR_PARTY VALUES ('PL', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');

INSERT INTO DOMIBUS_CONNECTOR_ACTION VALUES ('Form_A', 1);

INSERT INTO DOMIBUS_CONNECTOR_ACTION VALUES ('Form_B', 1);

INSERT INTO DOMIBUS_CONNECTOR_ACTION VALUES ('Form_C', 1);

INSERT INTO DOMIBUS_CONNECTOR_ACTION VALUES ('Form_D', 1);

INSERT INTO DOMIBUS_CONNECTOR_ACTION VALUES ('Form_E', 1);

INSERT INTO DOMIBUS_CONNECTOR_ACTION VALUES ('Form_F', 1);

INSERT INTO DOMIBUS_CONNECTOR_ACTION VALUES ('Form_G', 1);

INSERT INTO DOMIBUS_CONNECTOR_ACTION VALUES ('FreeFormLetter', 1);

INSERT INTO DOMIBUS_CONNECTOR_ACTION VALUES ('FreeFormLetterIn', 1);

INSERT INTO DOMIBUS_CONNECTOR_ACTION VALUES ('FreeFormLetterOut', 1);

INSERT INTO DOMIBUS_CONNECTOR_ACTION VALUES ('SubmissionAcceptanceRejection', 0);

INSERT INTO DOMIBUS_CONNECTOR_ACTION VALUES ('RelayREMMDAcceptanceRejection', 0);

INSERT INTO DOMIBUS_CONNECTOR_ACTION VALUES ('RelayREMMDFailure', 0);

INSERT INTO DOMIBUS_CONNECTOR_ACTION VALUES ('DeliveryNonDeliveryToRecipient', 0);

INSERT INTO DOMIBUS_CONNECTOR_ACTION VALUES ('RetrievalNonRetrievalToRecipient', 0);

INSERT INTO DOMIBUS_CONNECTOR_ACTION VALUES ('Test_Form', 0);

INSERT INTO DOMIBUS_CONNECTOR_ACTION VALUES ('TEST-ping-connector', 0);

INSERT INTO DOMIBUS_CONNECTOR_SERVICE VALUES ('EPO', 'urn:e-codex:services:');

INSERT INTO DOMIBUS_CONNECTOR_SERVICE VALUES ('SmallClaims', 'urn:e-codex:services:');

INSERT INTO DOMIBUS_CONNECTOR_SERVICE VALUES ('Connector-TEST', 'urn:e-codex:services:');

INSERT INTO DOMIBUS_CONNECTOR_SERVICE VALUES ('TEST-ping-connector', 'urn:e-codex:services:');

INSERT INTO CONNECTORNEW.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('initialData_1', 'StephanSpindler', '/db/changelog/install/initial-changelog-data.sql', SYSTIMESTAMP, 53, '7:d299ac405108642b0b8b4dbb75cfbb29', 'sql', '', 'EXECUTED', NULL, NULL, '3.5.3', '3450612126');

-- Release Database Lock
UPDATE CONNECTORNEW.DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;
