= Changelog

== 4.0.x

=== 4.0.1
Bugfix: Reading and respecting of property "connector.backend.ws.trust.store.path" to correctly address the backend's truststore.

== 4.0.2

Bugfix: The truststore for the security library to verify documents signatures and received ASIC-S containers initializes default values that load an invalid truststore if properties "connector.security.truststore.path" and "connector.security.truststore.password" are not set properly.
Bugfix: When submission to the gateway fails no further message processing is executed and no stacktrace is logged. A "RELAY_REMMD_REJECTION" should be produced and sent back to the backend.
Bugfix: Example property "gateway.endpoint.address" should document that this is used for the creation of the evidences. So the external known address of the gateway should be entered.
Bugfix: Property "connector.gatewaylink.ws.submissionEndpointAddress" is used for transmission to the gateway. This is not documented in the example properties.
The property "gateway.name" is only used for evidence generation. Therefore it's place and documentation within the example properties changed.
The property "gateway.role" is not used within the domibusConnector. Therefore it is deleted from the example properties.

Bigfix: The WSDL definitions of the gateway webservices were adapted to initialize the web services correctly.
Bugfix: The web service endpoint definition within the domibusConnectorGatewayLink was adopted to initialize the DomibusConnectorGatewayDeliveryWebService correctly.
Bugfix: Message Content handling with Oracle - SQL-Error 17226.
domibusConnectorClient:

The new domibusConnectorAPI referenced.
windows line ending replaced with unix lineending in unix startscripts
domibus-connector-plugin:

Bugfix: The property "connector.delivery.service.endpoint.address" has to be set in the "domibus.properties". Documentation in the example configuration added. Property within example configuration removed.
Bugfix: To initialize the DomibusConnectorGatewaySubmissionWebService accoringly the endpoint configuration in the example configuration was adapted.
Update of the domibusConnectorAPI to have corrected version of the WSDL definitions.

== 4.1.x

=== 4.1.0-RELEASE

Feature: Filesystem handling for streaming of attachments.
Feature: WS-Security at gateway webservice side
Bugfix: Cleanup of Message Contents after successfull submission.
Feature: Connector properties can be loaded from database
Feature: The logging of the domibusConnector will be improved.
Logging of message related operations will be driven by connectorId (connectorId is put into the MDC (Mapped Diagnostik Context) of the logging engine). Filtering possibilities.
Warning in logging if messages are not confirmed by evidencs within configurable period.
Warning in case of a red TrustOKToken.
Seperation between technical and message logging.

Feature: Enhancements of the administration console:
New design
Further imports from PModes
Configuration of properties over administration console if properties are loaded from database
User/role concept introduction
Monitoring of messages
domibus-connector-plugin:

Adaptions for domibus gateway 4.0.
Feature: Configuration improvements - seperate properties file for plugin.
Feature: WS-Security on webservices to connector.

=== 4.1.1-RELEASE


Bugfix:
Security problems with fileupload-commons
Compatibility problems with cxf

=== 4.1.2-RELEASE
Bugfix
Fix errors in evidence timeout processor

=== 4.1.3
Bugfix:
Fix difference between documented property for connector2connector Test
Fix NON_DELIVERY creation if pushing to backend fails: The connector will now immediately create a NON_DELIVERY if the push to a push backend fails
Fix File resources not released causes "too many open files" error.
Fix Empty folders of deprecated messages not deleted.

=== 4.1.4
Bugfix:
Fix Folder not deleted Problem
Fix Resource not released problem

=== 4.1.5
Bugfix
Internal Bugfix for automatic Mysql DB initialization (solves Problem key too long on mysql inno db)

=== 4.1.6
Bugfix
Fixed failing tests during CI Build because of outdated certificate

=== 4.1.7
Bugfix:
Fixed Issue JUEUSW-114, related to Key too long Problem

=== 4.1.8
Bugfix
Upgraded to latest e-Codex Security Library 1.12.2 (this includes the DSS Update to 5.2) This enables the usage of newer Algorithms
Added ID column in Table DOMIBUS_CONNECTOR_PROPERTY, check the migration scripts

=== 4.1.9
Bugfix: 

* Fixes the with the connector distributed documentation artifacts
* Fixes errors within the migration scripts and initial database scripts for pre 4.1.8 to upgrade to 4.1.8 database

=== 4.1.10
Bugfix:

* Fix issue when generating an evidence and no Reason is set. Default reason is now 'OTHER'
* Fix issue when UI is opened and an error occures in the WebMessagesService. The fix just logs the exception and the UI can still be opened