
ifndef::basepath[]
:basepath: ../../../../
endif::basepath[]

ifndef::header[]
include::{basepath}/doc/header.adoc[]
endif::header[]


ifndef::mvnbasedir[]
:mvnbasedir: {basepath}/../../../../../
endif::mvnbasedir[]


= Connector Workflows / Business Processing


== Abstract

This document summarizes the whole message/business proecessing of domibusConnector.

This document splits the message processing process into different detail levels:

* Detail Level 0: a very raw overview
* Detail Level 1: give more details
* Detail Level 3: a very detailed view of a specific activity/step, also holds a lot of implementation details

== Transaction handling

The concept of transactions will be the usage only of database based transactions. This means the only source of the current state will be the database. The JMS is only used for distributing the load over multiple instances and increase processing speed. Any lost jms message will be recovered by timer jobs which are checking the database for any stuck workflows.

//detail level 0 general flow
== Detail Level 0

include::level0/l0_process_message.adoc[leveloffset=+2]

//processes....
== Detail Level 1

include::level1/l1_message_receive.adoc[leveloffset=+2]
include::level1/l1_lookup_workflow_business_domain.adoc[leveloffset=+2]
include::level1/l1_process_message.adoc[leveloffset=+2]
include::level1/l1_send_message.adoc[leveloffset=+2]
include::level1/l1_process_send_event.adoc[leveloffset=+2]

//tasks, activities, steps
== Detail Level 2

include::level2/l2_lookup_backend.adoc[leveloffset=+2]
include::level2/l2_lookup_business_domain.adoc[leveloffset=+2]
include::level2/l2_lookup_workflow.adoc[leveloffset=+2]

== Implementation Details

=== Events

Sending a event shortly after a commit can be done by spring-events: https://www.baeldung.com/spring-events
Using spring-events should also make it possible to make JMS completely optional!

Still if the event is lost somehow timerjobs must look for these stuck messages and put them back on the queue/in the process.


==== Other problems/issues

===== Evidence Ordering

The ordering of evidences is necessary, but if a message is lost or at least retried on GW level the ordering might be wrong. For this case there is no strategy in place to resolve this issue.
Possible solutions:

|===

| Title | Description

| Always transport all known evidences together in a message
| Every message (confirmation message or business message) will contain all to the connector currently known and related evidences. So if the connector sends a DELIVERY confirmation message this message will also hold the RELAY_REMMD_ACCEPTANCE evidence. With this approach the initial sending connector will not run into any problems due a missing RELAY_REMMD_ACCEPTANCE evidence.

|===

NOTE: This migh only be a problem if RETRIEVAL evidences are created/required. In all other cases the message should fail anyway.

