update DOMIBUS_CONNECTOR_SEQ_STORE set SEQ_VALUE=(select SEQ_VALUE from ECODEX_SEQ_STORE where SEQ_NAME='ECODEX_MESSAGES.ID') where SEQ_NAME = 'DOMIBUS_CONNECTOR_MESSAGES.ID';
update DOMIBUS_CONNECTOR_SEQ_STORE set SEQ_VALUE=(select SEQ_VALUE from ECODEX_SEQ_STORE where SEQ_NAME='ECODEX_EVIDENCES.ID') where SEQ_NAME = 'DOMIBUS_CONNECTOR_EVIDENCES.ID';
update DOMIBUS_CONNECTOR_SEQ_STORE set SEQ_VALUE=(select SEQ_VALUE from ECODEX_SEQ_STORE where SEQ_NAME='ECODEX_MESSAGE_INFO.ID') where SEQ_NAME = 'DOMIBUS_CONNECTOR_MESSAGE_INFO.ID';

commit;

insert into DOMIBUS_CONNECTOR_MESSAGES select * from ECODEX_MESSAGES;

commit;

insert into DOMIBUS_CONNECTOR_EVIDENCES select * from ECODEX_EVIDENCES;

commit;

insert into DOMIBUS_CONNECTOR_MESSAGE_INFO select * from ECODEX_MESSAGE_INFO;

commit;
