package eu.domibus.connector.ws.backend.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-02-28T06:51:50.050+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://connector.domibus.eu/ws/backend/webservice", name = "DomibusConnectorBackendWebService")
@XmlSeeAlso({eu.domibus.connector.domain.transition.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DomibusConnectorBackendWebService {

    @WebMethod
    @WebResult(name = "requestMessagesResponse", targetNamespace = "", partName = "requestMessagesResponse")
    public eu.domibus.connector.domain.transition.DomibusConnectorMessagesType requestMessages(
        @WebParam(partName = "requestMessagesRequest", name = "requestMessagesRequest", targetNamespace = "")
        EmptyRequestType requestMessagesRequest
    );

    @WebMethod
    @WebResult(name = "submitMessageResponse", targetNamespace = "", partName = "submitMessageResponse")
    public eu.domibus.connector.domain.transition.DomibsConnectorAcknowledgementType submitMessage(
        @WebParam(partName = "submitMessageRequest", name = "submitMessageRequest", targetNamespace = "")
        eu.domibus.connector.domain.transition.DomibusConnectorMessageType submitMessageRequest
    );
}
