--  *********************************************************************
--  Update Database Script
--  *********************************************************************
-- It updates a 3.5 Connector Database to the 4.0 Database Schema
-- Before you execute this script make sure you have created a BACKUP of your current database
-- The script assumes, that there have been no changes made to the 3.5 database! 
--
-- It also requires that you delete your Foreign keys!
--

SET foreign_key_checks = 0;

-- DROP ALL FOREIGN KEYS
-- THIS WILL LIKELY FAIL, BECAUSE THE FOREIGN KEYS MAYBE NAMED DIFFERENT IN YOUR DATABASE
-- SO PLEASE REMOVE YOUR FOREIGN KEYS MANUALLY
-- 
-- The following statement will generate a list of drop statements for your foreign keys
-- you have to replace schemaname with your database schema!
-- SELECT concat('ALTER TABLE ', TABLE_NAME, ' DROP FOREIGN KEY ', CONSTRAINT_NAME, ';') 
-- FROM information_schema.key_column_usage 
-- WHERE CONSTRAINT_SCHEMA = 'schemaname' 
-- AND referenced_table_name IS NOT NULL;

SET autocommit = OFF;


ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCES DROP FOREIGN KEY dc_evidences_fk_message;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO DROP FOREIGN KEY dc_msg_info_fk_message;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO DROP FOREIGN KEY dc_msg_info_fk_to_party;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO DROP FOREIGN KEY dc_msg_info_fk_from_party;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO DROP FOREIGN KEY dc_msg_info_fk_service;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO DROP FOREIGN KEY dc_msg_info_fk_action;
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR DROP FOREIGN KEY dc_msg_error_fk_message;






-- drop quartz tables
DROP TABLE DCON_QRTZ_BLOB_TRIGGERS;
DROP TABLE DCON_QRTZ_CALENDARS;
DROP TABLE DCON_QRTZ_CRON_TRIGGERS;
DROP TABLE DCON_QRTZ_FIRED_TRIGGERS;
DROP TABLE DCON_QRTZ_LOCKS;
DROP TABLE DCON_QRTZ_PAUSED_TRIGGER_GRPS;
DROP TABLE DCON_QRTZ_SCHEDULER_STATE;
DROP TABLE DCON_QRTZ_SIMPLE_TRIGGERS;
DROP TABLE DCON_QRTZ_SIMPROP_TRIGGERS;
DROP TABLE DCON_QRTZ_TRIGGERS;
DROP TABLE DCON_QRTZ_JOB_DETAILS;




ALTER TABLE DOMIBUS_CONNECTOR_ACTION DROP PRIMARY KEY;
ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCES DROP PRIMARY KEY;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO DROP PRIMARY KEY;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGES DROP PRIMARY KEY;
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR DROP PRIMARY KEY;
ALTER TABLE DOMIBUS_CONNECTOR_PARTY DROP PRIMARY KEY;
ALTER TABLE DOMIBUS_CONNECTOR_SEQ_STORE DROP PRIMARY KEY;
ALTER TABLE DOMIBUS_CONNECTOR_SERVICE DROP PRIMARY KEY;
ALTER TABLE DOMIBUS_WEBADMIN_USER DROP PRIMARY KEY;

ALTER TABLE DOMIBUS_CONNECTOR_SERVICE MODIFY SERVICE VARCHAR(255) NOT NULL;
ALTER TABLE DOMIBUS_CONNECTOR_SERVICE MODIFY SERVICE_TYPE VARCHAR(512);


ALTER TABLE DOMIBUS_CONNECTOR_PARTY MODIFY PARTY_ID VARCHAR(255) NOT NULL;
ALTER TABLE DOMIBUS_CONNECTOR_PARTY MODIFY ROLE VARCHAR(255) NOT NULL;
ALTER TABLE DOMIBUS_CONNECTOR_PARTY MODIFY PARTY_ID_TYPE VARCHAR(512);


ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR MODIFY ID numeric(10, 0) NOT NULL;
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR MODIFY MESSAGE_ID numeric(10, 0);
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR MODIFY ERROR_MESSAGE VARCHAR(512);
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR MODIFY CREATED timestamp DEFAULT CURRENT_TIMESTAMP ;
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR MODIFY DETAILED_TEXT LONGTEXT;
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR MODIFY ERROR_SOURCE LONGTEXT;


CREATE TABLE DOMIBUS_CONNECTOR_MSG_CONT (ID numeric(10, 0) NOT NULL, MESSAGE_ID numeric(10, 0) NOT NULL, CONTENT_TYPE VARCHAR(255) NULL, CONTENT BLOB NULL, CHECKSUM LONGTEXT NULL, CREATED datetime NULL);
ALTER TABLE DOMIBUS_CONNECTOR_MSG_CONT ADD PRIMARY KEY (ID);


ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY ID numeric(10, 0) NOT NULL;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY MESSAGE_ID numeric(10, 0);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY FROM_PARTY_ID VARCHAR(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY FROM_PARTY_ROLE VARCHAR(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY TO_PARTY_ID VARCHAR(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY TO_PARTY_ROLE VARCHAR(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY ORIGINAL_SENDER VARCHAR(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY FINAL_RECIPIENT VARCHAR(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY SERVICE VARCHAR(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY ACTION VARCHAR(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY CREATED timestamp DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY UPDATED timestamp NULL DEFAULT NULL;

ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT MSG_INFO_UNIQ_MSG_ID UNIQUE (MESSAGE_ID);


ALTER TABLE DOMIBUS_CONNECTOR_MESSAGES RENAME TO DOMIBUS_CONNECTOR_MESSAGE;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE MODIFY ID numeric(10, 0) NOT NULL;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE CHANGE NAT_MESSAGE_ID BACKEND_MESSAGE_ID VARCHAR(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE MODIFY CONFIRMED timestamp NULL DEFAULT NULL;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE MODIFY REJECTED timestamp NULL DEFAULT NULL;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE MODIFY DELIVERED_GW timestamp NULL DEFAULT NULL;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE MODIFY UPDATED timestamp NULL DEFAULT NULL;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE CHANGE DELIVERED_NAT DELIVERED_BACKEND timestamp NULL DEFAULT NULL;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE ADD BACKEND_NAME VARCHAR(255) NULL;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE ADD CONNECTOR_MESSAGE_ID VARCHAR(255) NULL;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE MODIFY HASH_VALUE LONGTEXT;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE ADD PRIMARY KEY (ID);

ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCES RENAME TO DOMIBUS_CONNECTOR_EVIDENCE;
ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE MODIFY ID numeric(10, 0) NOT NULL;
ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE MODIFY MESSAGE_ID numeric(10, 0);
ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE MODIFY EVIDENCE LONGTEXT;
ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE MODIFY DELIVERED_NAT timestamp NULL DEFAULT NULL;
ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE MODIFY DELIVERED_GW timestamp NULL DEFAULT NULL;

ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE ADD PRIMARY KEY (ID);

CREATE TABLE DOMIBUS_CONNECTOR_BACKEND_INFO (ID numeric(10, 0) NOT NULL, BACKEND_NAME VARCHAR(255) NOT NULL, BACKEND_KEY_ALIAS VARCHAR(255) NOT NULL, BACKEND_KEY_PASS VARCHAR(255) NULL, BACKEND_SERVICE_TYPE VARCHAR(512) NULL, BACKEND_ENABLED BIT(1) DEFAULT 1 NULL, BACKEND_DEFAULT BIT(1) DEFAULT 0 NULL, BACKEND_DESCRIPTION LONGTEXT NULL, BACKEND_PUSH_ADDRESS LONGTEXT NULL);
ALTER TABLE DOMIBUS_CONNECTOR_BACKEND_INFO ADD PRIMARY KEY (ID);
ALTER TABLE DOMIBUS_CONNECTOR_BACKEND_INFO ADD CONSTRAINT UN_DOMIBUS_CONNECTOR_BACK_01 UNIQUE (BACKEND_NAME);
ALTER TABLE DOMIBUS_CONNECTOR_BACKEND_INFO ADD CONSTRAINT UN_DOMIBUS_CONNECTOR_BACK_02 UNIQUE (BACKEND_KEY_ALIAS);

CREATE TABLE DOMIBUS_CONNECTOR_BACK_2_S (DOMIBUS_CONNECTOR_SERVICE_ID VARCHAR(255) NOT NULL, DOMIBUS_CONNECTOR_BACKEND_ID numeric(10, 0) NOT NULL);
ALTER TABLE DOMIBUS_CONNECTOR_BACK_2_S ADD PRIMARY KEY (DOMIBUS_CONNECTOR_SERVICE_ID, DOMIBUS_CONNECTOR_BACKEND_ID);

ALTER TABLE DOMIBUS_CONNECTOR_ACTION MODIFY ACTION VARCHAR(255) NOT NULL;
ALTER TABLE DOMIBUS_CONNECTOR_ACTION ALTER PDF_REQUIRED SET DEFAULT 0;

CREATE TABLE DOMIBUS_CONNECTOR_CONT_TYPE (MESSAGE_CONTENT_TYPE VARCHAR(255) NOT NULL);
ALTER TABLE DOMIBUS_CONNECTOR_CONT_TYPE ADD PRIMARY KEY (MESSAGE_CONTENT_TYPE);

CREATE TABLE DOMIBUS_CONNECTOR_BIGDATA (ID VARCHAR(255) NOT NULL, CHECKSUM LONGTEXT NULL, CREATED datetime NULL, MESSAGE_ID DECIMAL(10, 0) NULL, LAST_ACCESS datetime NULL, NAME LONGTEXT NULL, CONTENT LONGBLOB NULL, MIMETYPE VARCHAR(255) NULL);
ALTER TABLE DOMIBUS_CONNECTOR_BIGDATA ADD PRIMARY KEY (ID);
ALTER TABLE DOMIBUS_CONNECTOR_BIGDATA ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_BIGDATA FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;


ALTER TABLE DOMIBUS_WEBADMIN_USER MODIFY USERNAME VARCHAR(512) NOT NULL;
ALTER TABLE DOMIBUS_WEBADMIN_USER MODIFY PASSWORD VARCHAR(512);
ALTER TABLE DOMIBUS_WEBADMIN_USER MODIFY SALT VARCHAR(255);
ALTER TABLE DOMIBUS_WEBADMIN_USER MODIFY ROLE VARCHAR(255);
ALTER TABLE DOMIBUS_WEBADMIN_USER ADD PRIMARY KEY (USERNAME);

ALTER TABLE DOMIBUS_WEBADMIN_PROPERTIES DROP PRIMARY KEY;
ALTER TABLE DOMIBUS_WEBADMIN_PROPERTIES RENAME TO DOMIBUS_WEBADMIN_PROPERTY;
ALTER TABLE DOMIBUS_WEBADMIN_PROPERTY CHANGE PROPERTIES_KEY `KEY` VARCHAR(512);
ALTER TABLE DOMIBUS_WEBADMIN_PROPERTY MODIFY `KEY` VARCHAR(512) NOT NULL;
ALTER TABLE DOMIBUS_WEBADMIN_PROPERTY CHANGE PROPERTIES_VALUE VALUE VARCHAR(512);
ALTER TABLE DOMIBUS_WEBADMIN_PROPERTY MODIFY VALUE VARCHAR(512);
ALTER TABLE DOMIBUS_WEBADMIN_PROPERTY ADD PRIMARY KEY (`KEY`);

ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MSG_ERROR FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE DOMIBUS_CONNECTOR_MSG_CONT ADD CONSTRAINT FK_DOMIBUS_CONN_DOMIBUS_CON_04 FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;


ALTER TABLE DOMIBUS_CONNECTOR_ACTION ADD PRIMARY KEY (ACTION);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD PRIMARY KEY (ID);
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR ADD PRIMARY KEY (ID);
ALTER TABLE DOMIBUS_CONNECTOR_PARTY ADD PRIMARY KEY (PARTY_ID, ROLE);
ALTER TABLE DOMIBUS_CONNECTOR_SEQ_STORE ADD PRIMARY KEY (SEQ_NAME);
ALTER TABLE DOMIBUS_CONNECTOR_SERVICE ADD PRIMARY KEY (SERVICE);


ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_MSGI_ACTION FOREIGN KEY (ACTION) REFERENCES DOMIBUS_CONNECTOR_ACTION (ACTION) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_MSGI_SERVICE FOREIGN KEY (SERVICE) REFERENCES DOMIBUS_CONNECTOR_SERVICE (service) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_MSGI_FROM_PARTY FOREIGN KEY (FROM_PARTY_ID, FROM_PARTY_ROLE) REFERENCES DOMIBUS_CONNECTOR_PARTY (PARTY_ID, ROLE) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_MSGI_TO_PARTY FOREIGN KEY (TO_PARTY_ID, TO_PARTY_ROLE) REFERENCES DOMIBUS_CONNECTOR_PARTY (PARTY_ID, ROLE) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_MSGI_MSGID FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_EVIDENCES FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE DOMIBUS_CONNECTOR_BACK_2_S ADD CONSTRAINT FK_DOMIBUS_CONN_DOMIBUS_CON_01 FOREIGN KEY (DOMIBUS_CONNECTOR_BACKEND_ID) REFERENCES DOMIBUS_CONNECTOR_BACKEND_INFO (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE DOMIBUS_CONNECTOR_BACK_2_S ADD CONSTRAINT FK_DOMIBUS_CONN_DOMIBUS_CON_02 FOREIGN KEY (DOMIBUS_CONNECTOR_SERVICE_ID) REFERENCES DOMIBUS_CONNECTOR_SERVICE (SERVICE) ON UPDATE NO ACTION ON DELETE NO ACTION;





COMMIT;
SET foreign_key_checks = 1;