-- *********************************************************************
-- Update Database Script - from domibusConnector 3.5 to 4.0
-- *********************************************************************
-- updates the connector database from an 3.5 connector version to 4.0
-- remove all Foreign Keys first before executing this script, otherwise there
-- will be some errors at the end of the script, when the foreign keys are
-- recreated with specific names
-- 


-- drop quartz tables
DROP TABLE DCON_QRTZ_BLOB_TRIGGERS;
DROP TABLE DCON_QRTZ_CALENDARS;
DROP TABLE DCON_QRTZ_CRON_TRIGGERS;
DROP TABLE DCON_QRTZ_FIRED_TRIGGERS;
DROP TABLE DCON_QRTZ_LOCKS;
DROP TABLE DCON_QRTZ_PAUSED_TRIGGER_GRPS;
DROP TABLE DCON_QRTZ_SCHEDULER_STATE;
DROP TABLE DCON_QRTZ_SIMPLE_TRIGGERS;
DROP TABLE DCON_QRTZ_SIMPROP_TRIGGERS;
DROP TABLE DCON_QRTZ_TRIGGERS;
DROP TABLE DCON_QRTZ_JOB_DETAILS;


SET DEFINE OFF;

ALTER TABLE DOMIBUS_CONNECTOR_SERVICE MODIFY SERVICE VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_SERVICE MODIFY SERVICE_TYPE VARCHAR2(512);

ALTER TABLE DOMIBUS_CONNECTOR_PARTY MODIFY PARTY_ID VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_PARTY MODIFY ROLE VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_PARTY MODIFY PARTY_ID_TYPE VARCHAR2(512);

ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR MODIFY ID NUMBER(10);
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR MODIFY MESSAGE_ID NUMBER(10);
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR MODIFY ERROR_MESSAGE VARCHAR2(512);
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR MODIFY CREATED TIMESTAMP;

ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR ADD ERROR_SOURCE_TEMP CLOB;
UPDATE DOMIBUS_CONNECTOR_MSG_ERROR SET ERROR_SOURCE_TEMP=ERROR_SOURCE;
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR DROP COLUMN ERROR_SOURCE;
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR RENAME COLUMN ERROR_SOURCE_TEMP TO ERROR_SOURCE;

CREATE TABLE DOMIBUS_CONNECTOR_MSG_CONT (ID NUMBER(10) NOT NULL, MESSAGE_ID NUMBER(10) NOT NULL, CONTENT_TYPE VARCHAR2(255), CONTENT BLOB, CHECKSUM CLOB, CREATED TIMESTAMP);
ALTER TABLE DOMIBUS_CONNECTOR_MSG_CONT ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_MSG__01 PRIMARY KEY (ID);

ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY ID NUMBER(10);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY MESSAGE_ID NUMBER(10);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY FROM_PARTY_ID VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY FROM_PARTY_ROLE VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY TO_PARTY_ID VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY TO_PARTY_ROLE VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY ORIGINAL_SENDER VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY FINAL_RECIPIENT VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY SERVICE VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY ACTION VARCHAR2(255);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY CREATED TIMESTAMP;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO MODIFY UPDATED TIMESTAMP;


ALTER TABLE DOMIBUS_CONNECTOR_MESSAGES RENAME TO DOMIBUS_CONNECTOR_MESSAGE;


ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE MODIFY ID NUMBER(10);


ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE RENAME COLUMN NAT_MESSAGE_ID TO BACKEND_MESSAGE_ID;


ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE MODIFY CONFIRMED TIMESTAMP;


ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE MODIFY REJECTED TIMESTAMP;


ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE MODIFY DELIVERED_GW TIMESTAMP;


ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE MODIFY UPDATED TIMESTAMP;


ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE RENAME COLUMN DELIVERED_NAT TO DELIVERED_BACKEND;


ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE ADD BACKEND_NAME VARCHAR2(255);

ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE ADD CONNECTOR_MESSAGE_ID VARCHAR2(255 CHAR);

ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE ADD CREATED TIMESTAMP;


ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE ADD HASH_VALUE_TEMP CLOB;
UPDATE DOMIBUS_CONNECTOR_MESSAGE SET HASH_VALUE_TEMP=HASH_VALUE;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE DROP COLUMN HASH_VALUE;
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE RENAME COLUMN HASH_VALUE_TEMP TO HASH_VALUE;


ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCES RENAME TO DOMIBUS_CONNECTOR_EVIDENCE;


ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE MODIFY ID NUMBER(10);


ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE MODIFY MESSAGE_ID NUMBER(10);


ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE ADD EVIDENCE_TEMP CLOB;
UPDATE DOMIBUS_CONNECTOR_EVIDENCE SET EVIDENCE_TEMP = EVIDENCE;
ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE DROP COLUMN EVIDENCE;
ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE RENAME COLUMN EVIDENCE_TEMP TO EVIDENCE;


ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE MODIFY DELIVERED_NAT TIMESTAMP;


ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE MODIFY DELIVERED_GW TIMESTAMP;


CREATE TABLE DOMIBUS_CONNECTOR_BACKEND_INFO (ID NUMBER(10) NOT NULL, BACKEND_NAME VARCHAR2(255) NOT NULL, BACKEND_KEY_ALIAS VARCHAR2(255) NOT NULL, BACKEND_KEY_PASS VARCHAR2(255) NOT NULL, BACKEND_SERVICE_TYPE VARCHAR2(255), BACKEND_ENABLED NUMBER(1), BACKEND_DEFAULT NUMBER(1), BACKEND_DESCRIPTION CLOB, BACKEND_PUSH_ADDRESS VARCHAR2(512));
ALTER TABLE DOMIBUS_CONNECTOR_BACKEND_INFO ADD CONSTRAINT PK_DOMIBUS_CONNECTOR_BACK_01 PRIMARY KEY (ID);
ALTER TABLE DOMIBUS_CONNECTOR_BACKEND_INFO ADD CONSTRAINT UN_DOMIBUS_CONNECTOR_BACK_01 UNIQUE (BACKEND_NAME);
ALTER TABLE DOMIBUS_CONNECTOR_BACKEND_INFO ADD CONSTRAINT UN_DOMIBUS_CONNECTOR_BACK_02 UNIQUE (BACKEND_KEY_ALIAS);


CREATE TABLE DOMIBUS_CONNECTOR_BACK_2_S (DOMIBUS_CONNECTOR_SERVICE_ID VARCHAR2(255) NOT NULL, DOMIBUS_CONNECTOR_BACKEND_ID NUMBER(10) NOT NULL);


ALTER TABLE DOMIBUS_CONNECTOR_ACTION MODIFY ACTION VARCHAR2(255);


CREATE TABLE DOMIBUS_CONNECTOR_BIGDATA (ID VARCHAR2(255) NOT NULL, CHECKSUM CLOB, CREATED TIMESTAMP, MESSAGE_ID DECIMAL(10, 0), LAST_ACCESS TIMESTAMP, NAME CLOB, CONTENT BLOB, MIMETYPE VARCHAR2(255));
ALTER TABLE DOMIBUS_CONNECTOR_BIGDATA ADD PRIMARY KEY (ID);

ALTER TABLE DOMIBUS_CONNECTOR_BIGDATA ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_BIGDATA FOREIGN KEY (MESSAGE_ID) REFERENCES WEBCONNECTOR.DOMIBUS_CONNECTOR_MESSAGE (ID);


-- ADDING FOREIGN KEY CONSTRAINTS
ALTER TABLE DOMIBUS_CONNECTOR_MSG_ERROR ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MSG_ERROR FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID);
ALTER TABLE DOMIBUS_CONNECTOR_MSG_CONT ADD CONSTRAINT FK_DOMIBUS_CONN_DOMIBUS_CON_04 FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_1 FOREIGN KEY (ACTION) REFERENCES DOMIBUS_CONNECTOR_ACTION (ACTION);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_2 FOREIGN KEY (SERVICE) REFERENCES DOMIBUS_CONNECTOR_SERVICE (service);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_3 FOREIGN KEY (FROM_PARTY_ID, FROM_PARTY_ROLE) REFERENCES DOMIBUS_CONNECTOR_PARTY (PARTY_ID, ROLE);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_4 FOREIGN KEY (TO_PARTY_ID, TO_PARTY_ROLE) REFERENCES DOMIBUS_CONNECTOR_PARTY (PARTY_ID, ROLE);
ALTER TABLE DOMIBUS_CONNECTOR_MESSAGE_INFO ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_MESSAGE_I FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID);
ALTER TABLE DOMIBUS_CONNECTOR_EVIDENCE ADD CONSTRAINT FK_DOMIBUS_CONNECTOR_EVIDENCES FOREIGN KEY (MESSAGE_ID) REFERENCES DOMIBUS_CONNECTOR_MESSAGE (ID);
ALTER TABLE DOMIBUS_CONNECTOR_BACK_2_S ADD CONSTRAINT FK_DOMIBUS_CONN_DOMIBUS_CON_01 FOREIGN KEY (DOMIBUS_CONNECTOR_BACKEND_ID) REFERENCES DOMIBUS_CONNECTOR_BACKEND_INFO (ID);
ALTER TABLE DOMIBUS_CONNECTOR_BACK_2_S ADD CONSTRAINT FK_DOMIBUS_CONN_DOMIBUS_CON_02 FOREIGN KEY (DOMIBUS_CONNECTOR_SERVICE_ID) REFERENCES DOMIBUS_CONNECTOR_SERVICE (SERVICE);
