DROP TABLE ECODEX_EVIDENCES;
DROP TABLE ECODEX_MESSAGE_INFO;
DROP TABLE ECODEX_MESSAGES;
DROP TABLE ECODEX_SEQ_STORE;
DROP TABLE ECODEX_PARTY;
DROP TABLE ECODEX_ACTION;
DROP TABLE ECODEX_SERVICE;