package eu.ecodex.connector.common.enums;

public enum ECodexEvidenceType {
    SUBMISSION_ACCEPTANCE, SUBMISSION_REJECTION, RELAY_REMMD_ACCEPTANCE, RELAY_REMMD_REJECTION, RELAY_REMMD_FAILURE, DELIVERY, NON_DELIVERY, RETRIEVAL, NON_RETRIEVAL;

}
