--liquibase formatted sql
--
--changeset connector:initialPersistenceTestdata_1
----------------------- Values for DOMIBUS_CONNECTOR_BACKEND_INFO ------------------------------

INSERT INTO DOMIBUS_CONNECTOR_BACKEND_INFO (ID, BACKEND_NAME, BACKEND_KEY_ALIAS, BACKEND_KEY_PASS, BACKEND_SERVICE_TYPE, BACKEND_DESCRIPTION, BACKEND_PUSH_ADDRESS)
VALUES (1, 'bob', 'bob', '', 'EPO', 'a epo backend', null);

INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES
  (1, 'domibus-blue', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');

INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES
  (2, 'domibus-red', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');


--changeset connector:initialPersistenceTestdataPmodes_2
----------------------- Values for Services,Actions,Parties ------------------------------

----------------------- Values for DOMIBUS_CONNECTOR_SERVICE ------------------------------
INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION) VALUES (1, 1, 'action1');
INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION) VALUES (2, 1, 'action2');
INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION) VALUES (3, 1, 'action3');
INSERT INTO DOMIBUS_CONNECTOR_SERVICE (ID, FK_PMODE_SET, SERVICE, SERVICE_TYPE) VALUES (2, 1, 'service1', 'servicetype');
INSERT INTO DOMIBUS_CONNECTOR_SERVICE (ID, FK_PMODE_SET, SERVICE, SERVICE_TYPE) VALUES (3, 1, 'service2', 'servicetype');
INSERT INTO DOMIBUS_CONNECTOR_SERVICE (ID, FK_PMODE_SET, SERVICE, SERVICE_TYPE) VALUES (4, 1, 'service3', 'servicetype');
INSERT INTO DOMIBUS_CONNECTOR_SERVICE (ID, FK_PMODE_SET, SERVICE, SERVICE_TYPE) VALUES (11, 1, 'EPO', 'urn:e-codex:services:');
INSERT INTO DOMIBUS_CONNECTOR_SERVICE (ID, FK_PMODE_SET, SERVICE, SERVICE_TYPE) VALUES (12, 1, 'SmallClaims', 'urn:e-codex:services:');
INSERT INTO DOMIBUS_CONNECTOR_SERVICE (ID, FK_PMODE_SET, SERVICE, SERVICE_TYPE) VALUES (13, 1, 'Connector-TEST', 'urn:e-codex:services:');
INSERT INTO DOMIBUS_CONNECTOR_SERVICE (ID, FK_PMODE_SET, SERVICE, SERVICE_TYPE) VALUES (14, 1, 'TEST-ping-connector', 'urn:e-codex:services:');

----------------------- Values for DOMIBUS_CONNECTOR_PARTY ------------------------------

INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES (11, 1, 'ARHS', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');
INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES (12, 1, 'AT', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');
INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES (13, 1, 'CTP', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');
INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES (14, 1, 'CZ', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');
INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES (15, 1, 'DE', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');
INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES (16, 1, 'EC', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');
INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES (17, 1, 'EE', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');
INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES (18, 1, 'ES', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');
INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES (19, 1, 'FR', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');
INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES (20, 1, 'GR', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');
INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES (21, 1, 'IT', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');
INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES (22, 1, 'ITIC', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');
INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES (23, 1, 'MT', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');
INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES (24, 1, 'NL', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');
INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES (25, 1, 'PL', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:iso3166-1');
----------------------- Values for DOMIBUS_CONNECTOR_ACTION ------------------------------1,

INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION) VALUES (11, 1, 'Form_A');
INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION) VALUES (12, 1, 'Form_B');
INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION) VALUES (13, 1, 'Form_C');
INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION) VALUES (14, 1, 'Form_D');
INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION) VALUES (15, 1, 'Form_E');
INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION) VALUES (16, 1, 'Form_F');
INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION) VALUES (17, 1, 'Form_G');
INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION) VALUES (18, 1, 'FreeFormLetter');
INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION) VALUES (19, 1, 'FreeFormLetterIn');
INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION) VALUES (20, 1, 'FreeFormLetterOut');
INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION) VALUES (21, 1, 'SubmissionAcceptanceRejection');
INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION) VALUES (22, 1, 'RelayREMMDAcceptanceRejection');
INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION) VALUES (23, 1, 'RelayREMMDFailure');
INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION) VALUES (24, 1, 'DeliveryNonDeliveryToRecipient');
INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION) VALUES (25, 1, 'RetrievalNonRetrievalToRecipient');
INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION) VALUES (26, 1, 'Test_Form');
INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, ACTION) VALUES (27, 1, 'TEST-ping-connector');



INSERT INTO DOMIBUS_CONNECTOR_SEQ_STORE (SEQ_NAME, SEQ_VALUE) VALUES ('DOMIBUS_CONNECTOR_MESSAGE.ID', 1000);
INSERT INTO DOMIBUS_CONNECTOR_SEQ_STORE (SEQ_NAME, SEQ_VALUE) VALUES ('DOMIBUS_CONNECTOR_MESSAGE_INFO.ID', 1000);
INSERT INTO DOMIBUS_CONNECTOR_SEQ_STORE (SEQ_NAME, SEQ_VALUE) VALUES ('DOMIBUS_CONNECTOR_MSG_CONT.ID', 1000);
INSERT INTO DOMIBUS_CONNECTOR_SEQ_STORE (SEQ_NAME, SEQ_VALUE) VALUES ('DOMIBUS_CONNECTOR_EVIDENCE.ID', 1000);

